set -g history-limit 10000

set-option -g default-shell "/usr/bin/zsh"

bind C-z setw synchronize-panes
setw -g window-status-current-format '#{?pane_synchronized,#[bg=red],}#I:#W'
setw -g window-status-format         '#{?pane_synchronized,#[bg=red],}#I:#W'
