#! /bin/bash

name="$1"; shift
size="$1"; shift
fstype="$1"; shift
sopt="-L $size"

if (echo "$size"|grep '%'); then
  sopt="-l $size"
fi

if /sbin/lvcreate $sopt -n "$name" vd; then
  makefs="/sbin/mkfs -t $fstype"
  if [ "x$fstype" = "xswap" ]; then
    makefs="/sbin/mkswap"
  fi
  if ! $makefs "$@" "/dev/vd/$name"; then
    /sbin/lvremove "vd/$name"
    exit 1
  else
    exit 0
  fi
fi
exit 1
