#!/bin/bash
if [ `cat /etc/cluster` == eqiad ]; then
	/usr/local/bin/dologmsg "$USER is doing a graceful restart of all apaches"
fi

dsh -F20 -g apaches -cM '/usr/bin/apache-sanity-check && sudo /usr/sbin/apache2ctl graceful'

if [ `cat /etc/cluster` == eqiad ]; then
	/usr/local/bin/dologmsg "!log $USER gracefulled all apaches"
fi
