# This is the conftool cluster name, don't be confused
cluster: kubernetes
# cluster_name is used to look up cluster settings from kubernetes_clusters hiera key.
profile::kubernetes::cluster_name: "%{::site}"

profile::base::overlayfs: true

profile::firewall::ferm_icinga_retry_interval: 15

# Enable ipip encapsulation
profile::lvs::realserver::ipip::enabled: true
# but disable MSS clamping
profile::lvs::realserver::ipip::clamping_enabled: false
# Allow to disable rp_filter on ipip interfaces (by setting all to disabled) and retain strict mode for all other interfaces
profile::base::enable_rp_filter:
  all_rp_filter: 0
  default_rp_filter: 1

# Defined in the private repo
#profile::kubernetes::node::docker_kubernetes_user_password

# This is set to true when a worker is hosting mw-experimental T276994
profile::kubernetes::node::mw_experimental: false
# We don't need conftool safe restart scripts on k8s.
profile::lvs::realserver::use_conftool: false
profile::lvs::realserver::pools:
  mathoid: {}
  zotero: {}
  eventgate-analytics: {}
  eventgate-main: {}
  eventgate-logging-external: {}
  eventgate-analytics-external: {}
  citoid: {}
  cxserver: {}
  sessionstore: {}
  termbox: {}
  wikifeeds: {}
  echostore: {}
  eventstreams: {}
  proton: {}
  mobileapps: {}
  mwdebug: {}
  mwdebug-next: {}
  push-notifications: {}
  recommendation-api: {}
  apertium: {}
  shellbox: {}
  shellbox-constraints: {}
  shellbox-media: {}
  shellbox-syntaxhighlight: {}
  shellbox-timeline: {}
  shellbox-video: {}
  thumbor: {}
  toolhub: {}
  linkrecommendation: {}
  tegola-vector-tiles: {}
  k8s-ingress-wikikube: {}
  mw-api-ext: {}
  mw-api-ext-next: {}
  mw-api-int: {}
  mw-jobrunner: {}
  mw-web: {}
  mw-web-next: {}
  device-analytics: {}
  rest-gateway: {}
  kartotherian-k8s-ssl: {}

prometheus::node_exporter::collectors_extra:
  - processes
profile::contacts::role_contacts: ['ServiceOps']
profile::base::production::role_description: 'Kubernetes worker node'

# Disable requestctl ferm rules and definitions from etcd
profile::firewall::defs_from_etcd: false
profile::firewall::defs_from_etcd_nft: false

# Experimental for T327300
profile::server_depool:
  policy: k8s
