class { 'openstack::controller':
  admin_email          => 'root@localhost',
  admin_password       => 'password',
  allowed_hosts        => ['127.0.0.%', '192.168.1.%'],
  cinder_db_password   => 'password',
  cinder_user_password => 'password',
  glance_db_password   => 'password',
  glance_user_password => 'password',
  keystone_admin_token => '12345',
  keystone_db_password => 'password',
  mysql_root_password  => 'password',
  nova_db_password     => 'password',
  nova_user_password   => 'password',
  private_interface    => 'eth1',
  public_address       => $::ipaddress_eth0,
  public_interface     => 'eth0',
  neutron              => false,
  rabbit_password      => 'password',
  secret_key           => '12345',
}
