# SPDX-License-Identifier: Apache-2.0
# Any value that needs to be injected in the template should be passed
# as environment variable (see https://www.benthos.dev/docs/configuration/interpolation/)
#
http:
  enabled: true
  address: "0.0.0.0:${PORT}"
  debug_endpoints: ${ENABLE_DEBUG}

input:
  label: "syslog"
  socket_server:
    network: tcp
    address: "${SOCKET_ADDRESS}"
    codec: lines

buffer:
 memory:
   limit: ${BUFFER_MEMORY_LIMIT_BYTES}
   batch_policy:
     enabled: false

pipeline:
  threads: ${PIPELINE_THREADS}
  processors:
    - label: grok
      grok:
        expressions:
          - "%{HPDATA}"
        pattern_definitions:
          HPDATA: |-
            [%{NOTSPACE:debug}] %{NOTSPACE:id}: type=str <%{DATA:payload}>
    - label: remove_errored
      mapping: |
        root = if errored() { deleted() }
    - label: main_mapping
      mapping: |
        root = this.payload.parse_json()
        root.id = this.id
        root."$schema" = "/analytics/haproxy_requestctl/1.0.1"
        root.meta.stream = "analytics.haproxy_requestctl"
        # root.dt /could/ be set by haproxy, but if not let's use now()
        let dt = now().ts_format("2006-01-02T15:04:05Z", "UTC")
        if root.dt == null {
            root.dt = $dt
        }
        # meta.dt is always set by benthos
        root.meta.dt = $dt

logger:
  level: WARN
  format: logfmt

output:
  switch:
    cases:
      - check: errored()
        output:
          label: "dlq"
          kafka_franz:
            seed_brokers: [ "${KAFKA_BROKERS}" ]
            topic: "${MSG_TOPIC}_error"
            compression: "snappy"
            tls:
              enabled: true
              root_cas_file: "${ROOT_CAS_FILE}"
              skip_cert_verify: false
          processors:
            - mapping: |
                root = this
                root.error = error()
      - output:
          label: "broker"
          broker:
            pattern: fan_out # https://docs.redpanda.com/redpanda-connect/components/outputs/broker/#patterns
            outputs:
              - label: "http"
                http_client:
                  url: "${EVENTGATE_URL}"
                  verb: POST
                  headers:
                    Content-Type: application/json
                  rate_limit: ""
                  timeout: 1s
                  retries: 2
                  retry_period: 1s
                  max_in_flight: 64
                  batch_as_multipart: false
                  tls:
                    enabled: true
                    root_cas_file: "${ROOT_CAS_FILE}"
                    skip_cert_verify: false
              - label: "kafka"
                kafka_franz:
                  seed_brokers: [ "${KAFKA_BROKERS}" ]
                  topic: "${MSG_TOPIC}"
                  compression: "snappy"
                  tls:
                    enabled: true
                    root_cas_file: "${ROOT_CAS_FILE}"
                    skip_cert_verify: false

tests:
  - name: simple parsing
    target_processors: /pipeline/processors
    environment: {}
    input_batch:
      - content: '[debug] test-reqctl: type=str <{"host":"localhost","src":"127.0.0.1","path":"/"}>'
    output_batches:
      - - bloblang: '(this.meta.dt.ts_parse("2006-01-02T15:04:05Z").type() == "timestamp") && (this.dt.ts_parse("2006-01-02T15:04:05Z").type() == "timestamp")'
          json_contains: '{"$schema":"/analytics/haproxy_requestctl/1.0.1","host":"localhost","id":"test-reqctl","meta":{"stream":"analytics.haproxy_requestctl"},"path":"/","src":"127.0.0.1"}'
  - name: test for root.dt provided by haproxy and unmodified by benthos
    target_processors: /pipeline/processors
    environment: {}
    input_batch:
      - content: '[debug] test-reqctl: type=str <{"dt":"2024-12-13T17:45:00Z","host":"localhost","src":"127.0.0.1","path":"/"}>'
    output_batches:
      - - bloblang: '(this.meta.dt.ts_parse("2006-01-02T15:04:05Z").type() == "timestamp") && (this.dt.ts_parse("2006-01-02T15:04:05Z").type() == "timestamp")'
          json_contains: '{"dt":"2024-12-13T17:45:00Z","$schema":"/analytics/haproxy_requestctl/1.0.1","host":"localhost","id":"test-reqctl","meta":{"stream":"analytics.haproxy_requestctl"},"path":"/","src":"127.0.0.1"}'
  - name: test for root.dt set by benthos
    target_processors: /pipeline/processors
    environment: {}
    input_batch:
      - content: '[debug] test-reqctl: type=str <{"host":"localhost","src":"127.0.0.1","path":"/"}>'
    output_batches:
      - - bloblang: '(this.meta.dt.ts_parse("2006-01-02T15:04:05Z").type() == "timestamp") && (this.dt.ts_parse("2006-01-02T15:04:05Z").type() == "timestamp")'
          json_contains: '{"$schema":"/analytics/haproxy_requestctl/1.0.1","host":"localhost","id":"test-reqctl","meta":{"stream":"analytics.haproxy_requestctl"},"path":"/","src":"127.0.0.1"}'
  - name: drop malformed content
    target_processors: /pipeline/processors
    environment: {}
    input_batch:
      - content: '[debug] none type=str 1234'
    output_batches: []
  - name: drop invalid content
    target_processors: /pipeline/processors
    environment: {}
    input_batch:
      - content: '[debug] test-reqctl: type=int <{"host":"localhost","src":"127.0.0.1","path":"/"}>'
    output_batches: []
