# SPDX-License-Identifier: Apache-2.0
# Any value that needs to be injected in the template should be passed
# as environment variable (see https://www.benthos.dev/docs/configuration/interpolation/)
#
http:
  enabled: true
  address: "0.0.0.0:${PORT}"
  debug_endpoints: true

input:
  label: "webrequest_sampled_in"
  kafka_franz:
    seed_brokers: [ "${KAFKA_BROKERS}" ]
    topics: [ "${KAFKA_TOPICS}" ]
    tls:
      enabled: true
      root_cas_file: /etc/ssl/certs/wmf-ca-certificates.crt
      skip_cert_verify: false
    consumer_group: 'benthos-webrequest_live'
    start_from_oldest: false
    batching:
      count: 4096
      period: 500ms

pipeline:
  # webrequest_frontend (text + upload) topics have 24 partitions each
  # make sure we can process at least webrequest_frontend_text in parallel
  threads: 24
  processors:
  - label: "sample"
    bloblang: |
      root = if meta("kafka_offset").number() % env("SAMPLING").number() != 0 { deleted() }

  - label: "geoip"
    bloblang: |
      root = this
      root.as_number = this.ip.geoip_asn(path: "/usr/share/GeoIP/GeoIP2-ISP.mmdb").AutonomousSystemNumber
      root.isp = this.ip.geoip_isp(path: "/usr/share/GeoIP/GeoIP2-ISP.mmdb").ISP
      root.country_code = this.ip.geoip_country(path: "/usr/share/GeoIP/GeoIP2-Country.mmdb").Country.IsoCode
      root.continent = this.ip.geoip_country(path: "/usr/share/GeoIP/GeoIP2-Country.mmdb").Continent.Names.en

  - label: "meta"
    # Kafka topics are named webrequest_frontend_text and webrequest_frontend_upload
    # We need to use the 3rd item of the split-by _ as the webrequest_source value
    bloblang: |
      root = this
      root.webrequest_source = (
          meta("kafka_topic").split("_").index(2)
      ).catch("-")

  - label: "analytics"
    bloblang: |
      root = this
      root.is_pageview = "-"
      root.x_analytics_data = (
        (this.x_analytics.split(";").map_each(
          field -> {(field.split("=").index(0)): (field.split("=").index(1))}
        )).squash()
      ).catch({})

      root.is_from_public_cloud = root.x_analytics_data.public_cloud.or("0")
      root.requestctl = root.x_analytics_data.requestctl.or("0")
      root.is_debug = root.x_analytics_data.is_debug.or("0")
      root.https = root.x_analytics_data.https.or("0")
      root.nocookies = root.x_analytics_data.nocookies.or("0")
      root.authorization = root.x_analytics_data.authorization.or("-")
      root.wmfuniq_days = root.x_analytics_data.wmfuniq_days.or("-")
      root.wmfuniq_weeks = root.x_analytics_data.wmfuniq_weeks.or("-")
      root.wmfuniq_freq = root.x_analytics_data.wmfuniq_freq.or("-")
      root.ja3n = root.x_analytics_data.ja3n.or("-")
      root.ja4h = root.x_analytics_data.ja4h.or("-")
      root.x_is_browser = root.x_analytics_data.x_is_browser.or("-")
      root.res_proxy = root.x_analytics_data.res_proxy.or("-")
      root.x_trusted_request = root.x_analytics_data.trusted_req.or("-")
      root.x_wmf_ratelimit_class = root.x_analytics_data.rl_class.or("-")
      root.is_thumb_generated = root.x_analytics_data.thumb_generated.or("0")

      root.x_analytics_data = deleted()
      root.x_analytics = deleted()

  - label: "provenance"
    bloblang: |
      root = this
      root.x_provenance_data = (
        (this.x_provenance.split(";").map_each(
          field -> {(field.split("=").index(0)): (field.split("=").index(1))}
        )).squash()
      ).catch({})
      root.top_historical_webrequest = if root.x_provenance_data.top_historical_webrequest.or("") == "true" { "1" } else { "0" }
      root.datacenter = if root.x_provenance_data.datacenter.or("") == "true" { "1" } else { "0" }

      root.x_provenance_data = deleted()
      root.x_provenance = deleted()

  - label: "tls_data"
    bloblang: |
      root = this
      root.tls_data = (
          (this.tls.split(";").map_each(
              field -> {
                 (field.split("=").index(0)): (field.split("=").index(1))
              })
          ).squash()
      ).catch({})
      root.tls_version = root.tls_data.get("vers").catch("-")
      root.tls_key_exchange = root.tls_data.get("keyx").catch("-")
      root.tls_auth = root.tls_data.get("auth").catch("-")
      root.tls_cipher = root.tls_data.get("ciph").catch("-")
      root.tls_sess = root.tls_data.get("sess").catch("-")

      root.tls_data = deleted()
      root.tls = deleted()

output:
  label: "webrequest_sampled_out"
  kafka_franz:
    seed_brokers: [ "${KAFKA_BROKERS}" ]
    topic: webrequest_sampled
    compression: "snappy"
    tls:
      enabled: true
      root_cas_file: /etc/ssl/certs/wmf-ca-certificates.crt
      skip_cert_verify: false

metrics:
  prometheus:
    use_histogram_timing: true
    add_process_metrics: true
    add_go_metrics: true
  mapping: |
    root = "benthos_" + this


tests:
  - name: tls_data parsing
    target_processors: 'tls_data'
    environment: {}
    input_batch:
      - content: '{"tls": "vers=TLSv1.3;keyx=UNKNOWN;auth=ECDSA;ciph=AES-256-GCM-SHA384;prot=h2;sess=new"}'
    output_batches:
      -
        - json_equals:
             tls_version: TLSv1.3
             tls_auth: ECDSA
             tls_cipher: AES-256-GCM-SHA384
             tls_key_exchange: UNKNOWN
             tls_sess: new

  - name: analytics parsing
    target_processors: 'analytics'
    environment: {}
    input_batch:
      - content: '{"x_analytics":"https=1;client_port=4181;nocookies=1;public_cloud=1;authorization=OAuth;wmfuniq_days=8;wmfuniq_weeks=5;wmfuniq_freq=10;ja3n=4cc9d9021e1f6b341f186aa7fa099388;ja4h=ge11cr130000_e2cffb44404f_b32290e48515;x_is_browser=50;res_proxy=squirrel;trusted_req=req1;rl_class=class1;thumb_generated=1"}'

    output_batches:
      -
        - json_equals:
             https: "1"
             is_debug: "0"
             is_from_public_cloud: "1"
             is_pageview: "-"
             is_thumb_generated: "1"
             requestctl: "0"
             nocookies: "1"
             authorization: "OAuth"
             wmfuniq_days: "8"
             wmfuniq_weeks: "5"
             wmfuniq_freq: "10"
             ja3n: "4cc9d9021e1f6b341f186aa7fa099388"
             ja4h: "ge11cr130000_e2cffb44404f_b32290e48515"
             x_is_browser: "50"
             res_proxy: "squirrel"
             x_trusted_request: "req1"
             x_wmf_ratelimit_class: "class1"

  - name: provenance parsing
    target_processors: 'provenance'
    environment: {}
    input_batch:
      - content: '{"x_provenance":"cloud=aws;cloud=public_cloud_nets;top_historical_webrequest=true;datacenter=true"}'

    output_batches:
      -
        - json_equals:
             top_historical_webrequest: "1"
             datacenter: "1"
