#! /bin/bash
#
#  Copyright © 2013 Marc-André Pelletier <mpelletier@wikimedia.org>
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
##
## THIS FILE IS MANAGED BY PUPPET
##
## Source: modules/toollabs/files/lighttpd-starter
## From:   modules/toollabs/manifests/webnode.pp
##

tool="$1"
port="$2"
prefix=$(/bin/cat /etc/wmflabs-project)
user="$prefix.$tool"
home=$(getent passwd $user | cut -d : -f 6 | sed -e 's/\/$//')
if [ "$(getent group $user | cut -d : -f 1)" != "$user" ]; then
  echo "$0: $1 does not appear to be a tool" >&2
  exit 1
fi
spool="/var/run/lighttpd"
runbase="$spool/$tool"

if [ "$home" = "" -o ! -d "$home/public_html" ]; then
  echo "$1 does not have a public_html" >&2
  exit 1
fi

cat <<EOF >$runbase.conf~
server.modules = (
  "mod_setenv",
  "mod_access",
  "mod_accesslog",
  "mod_alias",
  "mod_compress",
  "mod_redirect",
  "mod_rewrite",
  "mod_fastcgi",
  "mod_cgi",
)

server.port = $port
server.use-ipv6 = "disable"
server.username = "$prefix.$tool"
server.groupname = "$prefix.$tool"
server.core-files = "disable"
server.document-root = "$home/public_html"
server.pid-file = "$runbase.pid"
server.errorlog = "$home/error.log"
server.breakagelog = "$home/error.log"
server.follow-symlink = "enable"
server.max-connections = 300
server.stat-cache-engine = "fam"
server.event-handler = "linux-sysepoll"
ssl.engine = "disable"

alias.url = ( "/$tool" => "$home/public_html/" )

index-file.names = ( "index.php", "index.html", "index.htm" )
dir-listing.encoding = "utf-8"
server.dir-listing = "disable"
url.access-deny = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

accesslog.use-syslog = "disable"
accesslog.filename = "$home/access.log"

cgi.assign = (
  ".pl" => "/usr/bin/perl",
  ".py" => "/usr/bin/python",
  ".pyc" => "/usr/bin/python",
)

EOF

/usr/share/lighttpd/create-mime.assign.pl >>$runbase.conf~

if [ -r $home/.lighttpd.conf ]; then
  cat $home/.lighttpd.conf >>$runbase.conf~
fi

if [ ! -r $home/.lighttpd.conf ] || [[ ! $(cat "$home/.lighttpd.conf" | grep -P '^(?:[ \t]*fastcgi.server[ \t\+\(=]+".php"|#no-default-php)') ]]; then

cat <<EOF >>$runbase.conf~
fastcgi.server += ( ".php" =>
        ((
                "bin-path" => "/usr/bin/php-cgi",
                "socket" => "/tmp/php.socket.$tool",
                "max-procs" => 2,
                "bin-environment" => (
                        "PHP_FCGI_CHILDREN" => "2",
                        "PHP_FCGI_MAX_REQUESTS" => "500"
                ),
                "bin-copy-environment" => (
                        "PATH", "SHELL", "USER"
                ),
                "broken-scriptfilename" => "enable",
                "allow-x-send-file" => "enable"
         ))
)
EOF

fi

mv $runbase.conf~ $runbase.conf

exec /usr/sbin/lighttpd -f $runbase.conf -D >>$home/error.log 2>&1
