#!/usr/bin/python
"""
NodeJS starter script for Wikimedia Tool Labs
"""
import os

import portgrabber

# Attempt to get an open port
port = portgrabber.get_open_port()

# Connect to the proxylistener instances on the web proxies and notify
# them where requests for the tool need to be routed to.
portgrabber.register(port)

os.chdir(os.path.expanduser('~/www/js'))

# Pass in all of our parent environment too
# npm doesn't like it too much if you give it an almost empty environment
os.environ['TOOL_WEB_PORT'] = str(port)
os.environ['PORT'] = str(port)  # Switch things to PORT, same as heroku

os.environ['MYSQL_CREDS_PATH'] = os.path.expanduser('~/replica.my.cnf')

os.execv('/usr/bin/npm', ['/usr/bin/npm', 'start'])
