#!/usr/bin/python
import socket
import os

port = uid = os.getuid()

args = [
    '/usr/bin/uwsgi',
    '--plugin', 'python',
    '--plugin', 'router_rewrite',
    '--http-socket', ':' + str(port),
    '--wsgi-file', 'app.py',
    '--venv', os.path.expanduser('~/www/python/venv'),
    '--chdir', os.path.expanduser('~/www/python/src'),
    '--logto', os.path.expanduser('~/uwsgi.log'),
    '--route', '/([^/]+)/(.*) rewrite:/$2',
    '--callable', 'app',
    '--die-on-term',
    '--strict',
    '--master'
]

if os.path.exists(os.path.expanduser('~/www/python/uwsgi.ini')):
    args += ['--ini', os.path.expanduser('~/www/python/uwsgi.ini')]

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect(('tools-webproxy', 8282))
sock.send(".*\nhttp://%s:%s\n" % (socket.getfqdn(), port))

os.execv('/usr/bin/uwsgi', args)
