#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Shell wrapper for the home version of multiversion/MWScript.php.
# This script belongs in /usr/local/bin/ and should be in PATH.
. /etc/profile.d/mediawiki.sh

# On mwmaint hosts, when stderr is a terminal, announce impending decom.
if [ "${HOSTNAME:0:7}" == "mwmaint" ] && [ -t 2 ]; then
	echo >&2 "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	echo >&2 "@@@                                                                       @@@"
	echo >&2 "@@@  Running mwscript on mwmaint hosts is no longer supported.            @@@"
	echo >&2 "@@@                                                                       @@@"
	if [ "${1%.php}" == "sql" ] || [ "${1%.php}" == "mysql" ] || [ "${1%.php}" == "importImages" ] ; then
		# Send users of the following to the active deployment host on
		# a temporary basis:
		# * (T375910) mysql.php or sql.php
		# * (T377497) importImages.php
		echo >&2 "@@@  You are using a maintenance script that is not yet supported on      @@@"
		echo >&2 "@@@  Kubernetes. Until further notice, please use the active deployment   @@@"
		echo >&2 "@@@  host (deployment.eqiad.wmnet) to run your script.                    @@@"
	else
		echo >&2 "@@@  Maintenance scripts have moved to Kubernetes. Please submit feedback @@@"
		echo >&2 "@@@  right away if maintenance scripts on Kubernetes do not work for your @@@"
		echo >&2 "@@@  use case (T341553).                                                  @@@"
	fi
	echo >&2 "@@@                                                                       @@@"
	echo >&2 "@@@  Please see https://w.wiki/E68b for the announcement and              @@@"
	echo >&2 "@@@  https://wikitech.wikimedia.org/wiki/Maintenance_scripts for details. @@@"
	echo >&2 "@@@                                                                       @@@"
	echo >&2 "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
	exit 1
fi

# Use the source version of the script if the source directory is present.
# This only matters if the source dir is shared or when run on the deployment server.
if [ -d "$MEDIAWIKI_STAGING_DIR" ]; then
	MEDIAWIKI_DEPLOYMENT_DIR_DIR_USE=$MEDIAWIKI_STAGING_DIR
else
	MEDIAWIKI_DEPLOYMENT_DIR_DIR_USE=$MEDIAWIKI_DEPLOYMENT_DIR
fi

# PHP spits errors on unknown terminals before falling back to "dumb"
if [ -z "$TERM" ] || [ "$TERM" = unknown ] || [ "$TERM" = dumb ]; then
	export TERM=dumb
fi

# Allow overriding of PHP version or flags 
[ "$PHP" = "" ] && PHP=php

if [ "`whoami`" != "$MEDIAWIKI_WEB_USER" ] ; then
	sudo -u "$MEDIAWIKI_WEB_USER" $PHP "$MEDIAWIKI_DEPLOYMENT_DIR_DIR_USE/multiversion/MWScript.php" "$@"
else
	$PHP "$MEDIAWIKI_DEPLOYMENT_DIR_DIR_USE/multiversion/MWScript.php" "$@"
fi
