--   Copyright (C) 2020 Arturo Borrero Gonzalez <aborrero@wikimedia.org>
--
--  This program is free software: you can redistribute it and/or modify
--  it under the terms of the GNU General Public License as published by
--  the Free Software Foundation, either version 3 of the License, or
--  (at your option) any later version.
--
--  This program is distributed in the hope that it will be useful,
--  but WITHOUT ANY WARRANTY; without even the implied warranty of
--  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--  GNU General Public License for more details.
--
--  You should have received a copy of the GNU General Public License
--  along with this program.  If not, see <https://www.gnu.org/licenses/>.
--

--- Helper function to build the set of strings
-- @param list List of strings
function Set(list)
   local set = {}
   for _, l in ipairs(list) do set[l] = true end
   return set
end

--- Check the tool is allowed to have a redirect
-- @param toolname Name of the tool
function toolname_allowed(toolname)
    -- static list of allowed tools. To generate this list, see:
    -- https://wikitech.wikimedia.org/wiki/User:Arturo_Borrero_Gonzalez#wmcs-generate-legacy-redirector-list.py
    local allowed = Set {
        'a', 'aaaaaa', 'aaabot', 'abbe98tools', 'abbreviso', 'abcgames',
        'abdumubot', 'abibot', 'abigor', 'abohadi', 'abohadi1', 'abot',
        'abricot', 'abshir', 'abusereport', 'account', 'account-creator',
        'acc-utilities', 'ace2018', 'acoustid', 'activity', 'actrial', 'adas',
        'add', 'addbot', 'add-information', 'addscholartopics', 'addshore',
        'addshore-dev', 'add-text', 'admin', 'admin-beta', 'adminstats',
        'admin-test', 'advertisedetector', 'aemisinfo', 'afcbot', 'afch',
        'afch-updater', 'afc-research', 'afdstats', 'afrobot', 'aftabbot',
        'aftabbotbnwiki', 'aharonitelegrambot002', 'ahechtbot',
        'aiko-citationhunt', 'air7538tools', 'aivanalysis', 'aivhelperbot',
        'ajapaik2commons', 'akkakkbot', 'alaabot', 'alan', 'alanajjar',
        'alberobot', 'alchimista', 'aleph', 'alessiobot', 'alex', 'alfa80',
        'algo-news', 'alkamidbot', 'alphatest', 'alphawakt', 'altobot',
        'altostratus', 'alvaro', 'am', 'amarbot', 'amdb', 'ameen',
        'ameisenbot', 'amorybot', 'amstats', 'anagrimes', 'analytalks',
        'analytics', 'ananthrk-test', 'ancestors2', 'andrewtesttool',
        'android-maven-repo', 'android-sdk-builds', 'andxor', 'aneun-sandbox',
        'ankitbot', 'anni-me', 'anno', 'anomiebot', 'anon', 'anorange',
        'anticompositebot', 'anticompositetest', 'anticompositetools',
        'antigng', 'antigng-bot', 'aobo', 'apersonbot', 'api-citations',
        'apps-gallery', 'apt-browser', 'arambot', 'arbclerkbot', 'arcanist',
        'archaeo', 'archiveleaf', 'archivesearch', 'archive-things',
        'archive-things-1', 'archive-things-2', 'archive-things-3',
        'archive-things-4', 'archiving', 'arelph', 'arkivbot', 'arnaubot',
        'arowf', 'artemisia', 'article', 'article2',
        'article-creation-mapper', 'article-ideas-generator',
        'article-interactions', 'article-locations', 'articleplaceholderwiki',
        'articlerequest', 'articlerequest-dev',
        'articles-by-lat-lon-without-images', 'articles-needing-links',
        'articles-recommender', 'article-suggestion', 'artlist',
        'artuploader', 'arturo-test-tool', 'asaifmbot', 'ascal', 'asdf',
        'ashbot', 'ash-dev', 'ash-django', 'ashotbot', 'ashottools',
        'as-info', 'as-info-dev', 'askbot-01', 'assamesecalendar',
        'assamesetool', 'assessor', 'asurabot', 'aswnbot', 'atiro', 'ato',
        'atriskwiki', 'attribution', 'aude', 'audetools', 'auth',
        'author-disambiguator', 'authorlang-game', 'authors', 'autodesc',
        'autolist', 'autometrics', 'autopromote-status', 'avicbot', 'awb',
        'awmd-stats', 'awstats', 'axel', 'a-z-p', 'a-z-p-0-9-z', 'badges',
        'bajo', 'balasankarc', 'baljeetdhaliwal', 'baljeetsingh', 'bambots',
        'basebot', 'base-encode', 'base-php-cli', 'basetool', 'bash',
        'basyounybot', 'batchrevert', 'bawolff', 'bays', 'bbc-tv-cite',
        'bcxfu75kbot', 'bd808-k8smigrate', 'bd808-pywikibot', 'bd808-ruby',
        'bd808-test', 'bd808-test2', 'bd808-test3', 'bd808-test4',
        'beastiebot', 'become', 'beleg-tally', 'beleg-test-14568913402',
        'bene', 'benin1', 'bennofsplay', 'best-image', 'betabot',
        'betacommand-dev', 'betaweb', 'bibleversefinder', 'bibleversefinder2',
        'bibliodata', 'bikeshed', 'bingle', 'bing-maps', 'bingo', 'bkllc',
        'bkstats-test', 'blablabla', 'blahma', 'blankpages', 'bl-assist',
        'bldrwnsch', 'blockcalc', 'blocklog', 'blocksearch', 'blockyquery',
        'blog', 'blogconverter', 'blubber', 'bn-googleocr', 'bnwiki8',
        'bomwiki', 'book2scroll', 'bookmanagerv2', 'bookreader',
        'books-for-binding', 'booksplitter', 'bookworm', 'booster',
        'borracho', 'bot24', 'bot873', 'botadventures', 'bot-ash-nazg',
        'boteas', 'bothasava', 'botleo', 'botomatik', 'botorder', 'botqa',
        'botriconferme', 'botsister', 'botundo', 'botvegas', 'botwatch',
        'botwikiawk', 'boty', 'bovlbbot', 'bowleerin', 'bracketbot',
        'brandonstools', 'brgroup', 'bridgebot', 'bsaut', 'bstorm-tool',
        'bstorm-tool2', 'bub', 'bub2', 'bugello', 'bunykbot', 'bytesadded',
        'calakbot', 'calak-dev', 'calling-card', 'camelbot', 'canary',
        'canarybot', 'captcha', 'captcha-dev', 'cargo-hierarchy', 'catbot',
        'catcompare', 'categorie', 'category-by-uploaders', 'catfood',
        'catgraph', 'catgraph-jsonp', 'catimages', 'catlive', 'catmonitor',
        'catnap', 'catrename', 'catscan2', 'catscan3', 'catscan-pop',
        'catscore', 'catsize', 'cats-php', 'catwatchbot', 'cauchy', 'cauchy7',
        'cbench', 'cbench2', 'cbng-sql-1', 'cbng-sql-2', 'cbng-sql-3',
        'cbng-sql-4', 'cbng-sql-5', 'cbng-sql-6', 'ccm', 'cdnjs',
        'cdnjs-beta', 'cdrini-dev', 'centralnotice-bannergenerator',
        'cerabot', 'cewbot', 'cgstat', 'chaoyueltry', 'charttableconverter',
        'chat', 'checkdictation-fa', 'checker', 'checklinks',
        'checkpersondata', 'checkwiki', 'chemobot', 'chie-bot', 'chobot',
        'chocobot', 'churches', 'ci', 'cil2', 'cipherbot', 'citationbase',
        'citation-bot', 'citationdetective', 'citationgraph', 'citationhunt',
        'citations', 'citations-dev', 'citation-template-filling',
        'citeimage', 'cite-o-meter', 'citeplato', 'citer', 'cite-web-helper',
        'citing-bot', 'citytime', 'cleanup', 'clickstream-api', 'cloudvps',
        'clpo13-flask', 'cluebot', 'cluebot3', 'cluebotng',
        'cluebotng-staging', 'cluestuff', 'clunk', 'cobain', 'cobot',
        'cocubot', 'cocytus', 'code-essay', 'codelookup', 'codeqc',
        'codexbot', 'coh', 'coi', 'coibot', 'comidentgen', 'common-interests',
        'commons', 'commons-aiuser', 'commons-android-app',
        'commons-app-stats', 'commons-app-web', 'commonsarchive',
        'commons-campaign-commander', 'commonscategorycount',
        'commons-coverage', 'commons-delinquent', 'commons_describer',
        'commonsedge', 'commonsfairuseupload', 'commonshelper',
        'commonshelper2', 'commonsinterwiki', 'commons-maintenance-bot',
        'commons-mass-description', 'commons-mass-description-test',
        'commons-mass-upload', 'commonsnotificationbot', 'commons-poty',
        'commonsuploadsum', 'commons-video-clicks', 'commtech-commons',
        'communityguidelines', 'community-tech-tools', 'compare-accounts',
        'completer', 'comprende', 'congressedits', 'connectivity', 'contact',
        'contentcontributor', 'content-gap', 'continuitybot', 'contraband',
        'contrabandapp', 'contribgraph', 'contribstats',
        'contributions-summary', 'contributionsurveyor', 'contropedia',
        'convenient-discussions', 'convert', 'coord', 'copyclear',
        'copypatrol', 'copyvios', 'copywhat', 'corenlp', 'corhist', 'costar',
        'countcountbot', 'countcounttest', 'countryip', 'coursestats',
        'coverage', 'coverme', 'covid', 'covid-obit', 'cp', 'cpb', 'cradle',
        'crazyometer', 'creatorlinks', 'crisis-response', 'crocodylia',
        'cropbot', 'cropcrop', 'croptool', 'crossactivity', 'crosswatch',
        'crosswatch2019', 'crosswatch-monitoring', 'csbot', 'csfd',
        'csp-report', 'cssk', 'cuddle', 'currentevents', 'custom-utils',
        'cvn', 'cvrminer', 'cyberbot', 'cybertools', 'cyberworm', 'cydebot',
        'daahbot', 'dabsolver', 'dal', 'danilo', 'danmicholobot',
        'dannys712-bot', 'danorton-dev', 'dapete-dev', 'dashboard',
        'database-reports', 'datacon-schedule-app', 'data-design-demo',
        'datasets', 'dataviz', 'datbot', 'datbotcommons', 'dateien',
        'david-tool', 'davod', 'dawiki', 'dawikibot', 'dawikitool', 'db',
        'dbbot', 'dbreps', 'dbreps-uk', 'ddescriptions', 'deadlinkfinder',
        'deadlinks', 'death-anomalies', 'declare', 'deep-learning-services',
        'defconbot', 'dekel', 'delinker', 'dellie', 'deltabot',
        'deltaquad-bots', 'demibot', 'demo-unicorn', 'denisa', 'denkmalbot',
        'denkmalliste', 'depiction-game', 'depictions', 'depicts',
        'deprecated-fixer-bot', 'derivative', 'desh',
        'design-research-methods', 'deskana', 'deskana2', 'detox',
        'detoxresearch', 'devlibrarycard', 'devyasha', 'devys',
        'dewikigreetbot', 'dewikinews-rss', 'dewikivpncheck', 'dewkin',
        'dewpmonobookupdater', 'dexbot', 'dexibotnet', 'dibot', 'dibyadutta',
        'dicompte', 'digero', 'digitaltmuseum', 'dijkstrasproject',
        'dimastbkbot', 'dimensioner', 'dioceses', 'directory', 'disambinator',
        'disclaim', 'discogs2pistes', 'discord-irc', 'discordwiki',
        'dispatcher', 'dispenser', 'dixondbot', 'dixtosa', 'dluxbot', 'dna',
        'dnbtools', 'dockerregistry', 'docker-registry', 'doi-bot',
        'douglasbot', 'dow', 'dpkg', 'dplbot', 'draftifyhistory',
        'draft-uncategorize-script', 'dramaboard', 'drawshield', 'drbot',
        'dreamyjazzbot', 'drewbot', 'dribper', 'drini', 'droog',
        'drtrigonbot', 'drvstats', 'dschwenbot', 'dspull', 'dtz',
        'dumpcattree', 'dumpscan', 'dump-torrents', 'dupdet',
        'duplicate-coords', 'duplicatehunter', 'durl-shortener', 'dutchbot',
        'dvorapabot', 'dvtbot', 'dykautobot', 'dykbot', 'dykfeed',
        'dykmoverbot', 'dykstats', 'dynamicbot', 'dynbot-srv1', 'dynbot-srv2',
        'eagerbot', 'eagleeye', 'earwigbot', 'earwig-dev', 'eatchabot',
        'eathom', 'ebrahim-dev', 'ebraminio-dev', 'ecmabot', 'edcounter',
        'edgars', 'edgarsdev', 'edin', 'edinbot', 'edinc', 'editathonstat',
        'editcompare', 'edit-counter', 'editcount-fr', 'editcountitis',
        'editful', 'editgroups', 'editor-retention-dashboard', 'edits',
        'editsynergy', 'efenbot', 'elasticdash', 'elobot', 'elph', 'elvisor',
        'emausbot', 'embeddeddata', 'embeddedincount', 'emijrpbot',
        'emoociev', 'enbbsb', 'enboten', 'endumen', 'energybot', 'enet',
        'enett', 'enhourly', 'enterpriseybot-rs', 'entsuggest',
        'enwiki-user-edits', 'enwiktdefns', 'enwnbot', 'enwp10', 'eranbot',
        'erex-yomi', 'erwin85', 'esbackup', 'esfichataxon', 'etools',
        'etwelvetest', 'etwikibots', 'etwikt', 'etytree', 'eulenwiki',
        'eulenwiki2', 'eulenwiki3', 'event-live-session', 'event-streams',
        'every', 'every-other-wiki-has', 'everythingisconnected', 'exambot',
        'excel2wiki', 'experimental-embeddings', 'exportpdf', 'expose-data',
        'extdist', 'extensionservice', 'externalitemsuggester',
        'extjsonuploader', 'ext-lnk-discover', 'extreg-wos', 'extreme', 'fab',
        'fab-proxy', 'facebook-messenger-chatbot', 'faces', 'fa-checkwiki',
        'faebot', 'fajrbot', 'family', 'farhangestan', 'farotbot', 'farticle',
        'fastilybot', 'fastilybot-reports', 'fatameh', 'fatemi', 'fatg',
        'fawikiauto', 'fawiki-editathon', 'fb-translate-bot', 'fc-importer',
        'featured-article', 'femiwiki', 'fengtools', 'ferdibot', 'ffbot',
        'fikarummet', 'filedupes', 'file-reuse', 'file-reuse-piwik',
        'file-reuse-review', 'file-reuse-test', 'filesearch', 'file-siblings',
        'find-and-replace', 'findit', 'fingerprint', 'fireflydev',
        'firefly-maintainer1', 'fireflytools', 'firmenbuch',
        'first-paragraph-readability', 'fischbot', 'fist', 'five-million',
        'fiwiki-tools', 'fixdatebot', 'flaggedrevspromotioncheck', 'flaky-ci',
        'flickr', 'flickr2commons', 'flickrdash', 'flickr-rss',
        'flossbrowser', 'fn', 'fontcdn', 'footygen', 'forrestbot',
        'foundation', 'fountain', 'fountain-test', 'fourohfour', 'fpbot',
        'fpcbot', 'fpcstats', 'framabot', 'freddy2001', 'freebase',
        'freefiles', 'fretties', 'friskobot', 'friybot', 'fronds',
        'fr-wikiversity', 'fr-wikiversity-ns', 'fscbot', 'fshbibbot', 'ft',
        'ftl', 'ftools', 'fubar', 'fun', 'fundraising-tools', 'furutani',
        'fvcbot', 'g13bot', 'gabrielchihonglee-bot', 'gaelan-bot', 'gallery',
        'gallica', 'galobot', 'ganreportbot', 'gblrenamemon',
        'gdk-artists-research', 'geekbot', 'gendergapdashboard', 'genealogy',
        'genedb', 'gennfs', 'geocommons', 'geodata', 'geograph2commons',
        'geohack', 'geoloc', 'geonotice', 'geophotoreq', 'geoplotter',
        'gerakibot', 'gerakitools', 'germancon-mobile',
        'germancontributioncounts', 'gerrit-avatar-uploader',
        'gerrit-newcomer-bot', 'gerrit-patch-uploader', 'gerrit-reports',
        'gerrit-reviewer-bot', 'gerrit-to-redis', 'getsentry', 'ggu',
        'giftbot', 'giftpast', 'giovannitool', 'gir', 'giraffe', 'github',
        'github-notif-bot', 'github-pr-closer', 'githubstats', 'glaisher',
        'glam2commons', 'glamalign', 'glamify', 'glamingest',
        'glamorous-maintenance', 'glamtools', 'globalcsd',
        'globaleditcounter', 'global-pandas', 'globalprefs', 'globalsearch',
        'global-search', 'global-search-test', 'globalusagecount',
        'global-wiki-tools', 'gmt', 'gns', 'gnubotmarcoo', 'goatid',
        'goblinbot4', 'goodarticle', 'goodarticlebot', 'goodbot',
        'google-drive-photos-to-commons', 'goransmtool', 'gorlingor',
        'governance-timeline', 'gpsexif', 'gpy', 'grafana',
        'grafana-json-datasource', 'graham87', 'graminbot', 'granitstein',
        'grantmaking', 'grantmetrics', 'grantmetrics-test', 'grantsbot',
        'grapedog', 'graphql', 'gratitude', 'grep', 'gridengine-status',
        'grid-jobs', 'grillitus', 'grouplens', 'gsoc', 'gsoc-dev',
        'gsociftttdev', 'gsoc-ifttt-dev', 'gsoc-petscan-query-articles',
        'gsoc-worklist-tool', 'gtirloni-sandbox', 'guc', 'gulp', 'gun-wd',
        'gurmukhispell', 'gutrs', 'gyan', 'h2bot', 'hackmd', 'hackprowiki',
        'hall-of-fame', 'hamishbot', 'harejtest', 'hartman',
        'harvesting-data-rafinery', 'harvesting-data-refinery', 'hashtags',
        'hashtags-hub', 'hashtags-test', 'hashtagwatcher', 'hassen',
        'hastagwatcher', 'hasteurbot', 'hat-collector', 'hatjitsu', 'hauki',
        'hawk-eye-bot', 'hay', 'hazard-bot', 'hcclab', 'hd', 'hebbot',
        'heimdall', 'heinterwiki', 'hello-play', 'help', 'helpearwigbot',
        'helperbot', 'helperpad', 'hennalabs', 'herculebot', 'heritage',
        'hermes', 'hersfold-hacb', 'hersfold-irc', 'hersfold-web',
        'hewiki-tools', 'he-wiktionary-rule-checker', 'hexacore', 'hgztools',
        'himo', 'hinotetools', 'hippietest', 'hirise', 'historicmaps',
        'historyview', 'histsearch', 'hiw-bot', 'hiwiki', 'hjhhg',
        'hkjacksonhk-bot', 'hll', 'holidays-viewer', 'honeypot95', 'hoo',
        'hoo-propertysuggester-test', 'hostbot', 'hotarticles', 'hroest',
        'hroest2', 'hroest3', 'hrwiki', 'hsfbot', 'hss', 'htools', 'hub',
        'huggle', 'huji', 'hujibot', 'huntleybots', 'huwiki', 'hylabels',
        'hypobot', 'iabot', 'iacrop', 'iamnetx-test', 'ia-upload', 'ib2test',
        'ibrahim', 'ibrahimid', 'icalendar', 'icelab', 'ichijo', 'icommons',
        'icu-transliterate', 'ideasbot', 'ideedarticles', 'idsgen',
        'idwiki-gpu', 'idwiki-marathon', 'iepcbm-bot1', 'iepcbm-bot-2',
        'ifttt', 'ifttt-dev', 'ifttt-testing', 'igl', 'igloo', 'ignator',
        'iluvatarbot', 'imagechecker', 'imagemapedit',
        'image-metadata-viewer', 'image-resize-calc', 'imagery', 'images',
        'imagetracer', 'img-usage', 'import-500px', 'import-freemind',
        'inactiveadmins', 'inactive-admins', 'inactive-bureaucrats',
        'inaturalistreviewer', 'incolabot', 'index-page-mover', 'indic-ocr',
        'indic-techcom', 'indic-techcom-wiki', 'indic-wd', 'indicwiki',
        'indic-wscontest', 'indic-wsstats', 'info-farmer', 'infogeo',
        'inforobbot', 'inkobot', 'inkowik', 'inkpen', 'integraality',
        'intelibot', 'intelirc', 'interaction-timeline', 'interactoa',
        'interact-oa', 'interbot', 'interlang', 'interpagelinker',
        'intersect-contribs', 'intuition', 'invadibot', 'ios-crashes',
        'ipa-speaker', 'ipchanges', 'ipcheck', 'ipcheck-dev', 'ipinfo',
        'iplookup', 'ipp', 'ip-range-calc', 'ipwatcher', 'ipython', 'irc',
        'ircclient', 'irc-cloaks', 'irc-cloudbot', 'irclogbot', 'irclogs',
        'ircredirect', 'ircredirector', 'irc-wmt', 'ireas', 'irfan',
        'irishbot', 'isa', 'isbn', 'isbn2tpl', 'isbn2wiki', 'isbn-tmptest',
        'isbn-usage', 'is-deployed', 'isin', 'isitdeployed', 'isprangefinder',
        'italian-wikipedia-bar', 'itemfinder', 'itemlister', 'itsource',
        'itwiki', 'itwikiarticlebot', 'itwikinews-rss',
        'it-wiki-users-leaflet', 'itwp-deletions', 'iw', 'jackbot', 'james',
        'jamesur-usergroupsearch', 'janet', 'jarallah', 'jarallah-ii',
        'jarbot', 'jarbot-ii', 'jarbot-iii', 'jarry-common', 'jata',
        'javatest', 'jawi', 'jayprakashbot', 'jbbot', 'jbbot2', 'jeh-dev',
        'jeltebot', 'jembot', 'jeremy', 'jeremyb', 'jimmy', 'jira-bugimport',
        'jitrixis-test', 'jitse-bot', 'jjmc89-bot', 'jjmc89-bot-dev',
        'joanjoc', 'joaquinito01', 'jogobot', 'jogotools', 'johnlewis',
        'joinedventure', 'jorobot', 'josve05a-test', 'jouncebot', 'jshint',
        'jtools', 'jurgennl', 'jury', 'justincbot', 'k8s-status', 'kaare',
        'kaleem-bot', 'kaleem-bot-i', 'kanjybot', 'kanzatgroup',
        'karsilayici', 'kaspar2commons', 'kasparbot',
        'kasper-data-translator', 'kdb', 'kenrick95bot', 'ket-bot',
        'keystone-browser', 'khanamalumat', 'khanomalumat', 'kharbot',
        'khebi', 'kian', 'kirstentest', 'klossebot', 'kmlexport',
        'kmlexport-cswiki', 'knowledgegrapher', 'kokolores', 'kolbert',
        'kolega', 'kolega2357', 'kotools', 'kowikitools', 'krdbot',
        'krinklebot', 'krinkle-redirect', 'ksamsok-rest', 'ktc',
        'kuwaity-tool', 'l235-bot', 'l235-irc', 'laaknortools', 'labelimgohs',
        'labstore-profiling', 'lahitools', 'lalm', 'lambdabot',
        'languagebar-ui', 'languageproofing', 'languageproofing-ui',
        'languagetool', 'langviews', 'langviews-test', 'largedatasetbot',
        'lastactiveadms', 'lastpics', 'lbenedix', 'lcm-dashboard', 'ldap',
        'ldap-beta', 'lebot', 'legobot', 'legobot-2', 'legoktm-adminbots',
        'leptibot', 'lestaty', 'lets-translate', 'lexeme-forms',
        'lexeme-senses', 'liangent', 'liangent-django',
        'liangent-migration-test', 'liangent-misc', 'liangent-php',
        'liangent-py', 'liangent-shared', 'liangent-toolserver', 'lib',
        'librarybase-db', 'librarybase-updater', 'libraryupgrader',
        'librewiki', 'liepp', 'lifeweb', 'lighttpd-test', 'lijebot', 'lilbit',
        'lil-cvn', 'limesmap', 'lincolnbot', 'linedwell', 'lingua-libre',
        'linkedpageviews', 'linkscount', 'linksearch', 'linkspam',
        'linkstranslator', 'linkwatcher', 'linkybot', 'linkypedia', 'list',
        'listeria', 'listpages', 'lists', 'listunpatrolledpages',
        'livingstyleguide-prototype', 'lkftools', 'local-awb',
        'local-library-fulltext', 'local-maps', 'local-oclc-reference',
        'local-reference-api', 'local-root', 'local-southparkfan',
        'local-wikipedia-library-reference', 'locator', 'locatorbot',
        'locator-tool', 'locktool', 'logger', 'logojudge', 'logoscope',
        'logs', 'lolrrit-wm', 'loltools', 'loltools-testing', 'loltrs',
        'lonelylinks', 'low', 'lp-tools', 'lrbot', 'lrtools', 'lst-guard',
        'lta', 'ltfeedchecker', 'lua-catscan2', 'luke081515bot',
        'luke081515bot-beta', 'luke081515bot-dev', 'lyan', 'lynxbot', 'lziad',
        'lziad-cvnbot', 'mabot', 'macfanbot', 'macfanlogbot', 'machtsinn',
        'machtsinn-dev', 'macommune', 'magnustools', 'magnus-toolserver',
        'magog', 'mahdiz', 'maintainers', 'maintenance-bot', 'maintgraph',
        'maintun', 'maiwiki-editathon', 'majavah-bot', 'makeref',
        'manishearth', 'manypedia', 'map', 'mapillary-commons',
        'maplayers-demo', 'maplink-generator', 'map-of-monuments', 'maps',
        'map-search', 'mapycz', 'mardetanha-dev', 'maria', 'masscamps',
        'massmailer', 'masssly-test-tool', 'massviews', 'massviews-test',
        'math', 'mathbot', 'mathqa', 'matilda', 'matsubot', 'matthewrbot',
        'matthewrbot-dev', 'matthewrbowker', 'matthewrbowker-dev',
        'matthobot', 'matvaretabellen', 'maurelio', 'mavrikant', 'mbh',
        'mbrt1', 'mc8', 'mdaniels-acc-dev', 'mdanielsbot',
        'mdaniels-licencehelper', 'mdaniels-ogrebot', 'mdaniels-refill-ng',
        'mdaniels-refill-ng-api', 'mdann52bot', 'mdvt', 'mediacounts',
        'media-dubiety', 'mediaplaycounts', 'media-reports', 'mediaviews',
        'mediaviews-api', 'mediawiki2latex', 'mediawiki-feeds',
        'mediawiki-mc', 'mediawiki-mirror', 'medusatest', 'meetbot',
        'meetingtimes', 'megacron', 'mehrdadbot', 'memberbot', 'menobot',
        'merge2pdf', 'merlbot', 'merlbot2', 'merlbot-read', 'merlbot-web',
        'merl-dev', 'merliwbot', 'messenger-chatbot', 'meta', 'meta2',
        'meta-dev', 'metamine', 'metaviews', 'metmuseum', 'metricslibrary',
        'metricslibrary-dev', 'mfnf-export', 'mfw-bww', 'mg-bot',
        'mh-signbot', 'mhwikibot', 'mide', 'mide-dev', 'mifterbot',
        'mifterbot-en', 'milhistbot', 'mirador', 'miraheze-discord-irc',
        'miraheze-notifico', 'mirusbot', 'misc2svg', 'missing-from-wikipedia',
        'missingpages', 'missingtopics', 'missing-value', 'mitmachen',
        'mix-n-match', 'mjbmr', 'mjbmrbot', 'mjbmr-tools', 'mjlbot', 'mlbt',
        'mlwikidbupdate', 'mlwikisource', 'mmt', 'mobile', 'moedata',
        'mohammedbot', 'mohib', 'mohiburdu', 'monaco', 'mono', 'montage',
        'montage-beta', 'montage-dev', 'monumental', 'monumental-glam',
        'morebots', 'morfeusz', 'mormegil', 'morph', 'morphtool', 'mortar',
        'mostlinkedmissing', 'most-readable-pages', 'most-wanted', 'move',
        'movecat', 'movestats', 'mp', 'mpaatools', 'mrakinsey', 'mrbluebot',
        'mrmetadata', 'msbits', 'mscbot', 'mstools', 'msynbot', 'mtc-rest',
        'mu', 'multichill', 'multicompare', 'multidesc', 'muninnbot',
        'murbot', 'musikanimal', 'musikanimal-test', 'musikbot', 'mw2sparql',
        'mwcoreteam', 'mwhook-bot', 'mwlint', 'mwp', 'mwpackages', 'mwph-api',
        'mwp-testing', 'mwstew', 'mwversion', 'mybot',
        'my-first-django-oauth-app', 'my-first-django-tool',
        'my-first-flask-oauth-tool', 'my-first-flask-tool',
        'my-first-pywikibot-tool', 'my_first_tool', 'myrcx',
        'mysql-php-session-test', 'my-threads', 'mywikitool', 'mzmcbride',
        'nada', 'nagf', 'nakon', 'namakemono', 'napalmbot', 'napalmbot-sah',
        'napalmtools', 'nara', 'nasirkhanbot', 'nasirkhantools',
        'navlink-recommendation', 'nearby-places-viewer', 'neechal',
        'neechalbot', 'negative24-bottesting', 'neuraltricity', 'neuromat',
        'newbie-uploads', 'newfiles', 'newiki-editathon', 'new-q5',
        'new-uploads-refresher', 'newusers', 'newwebtest', 'newyorkadam',
        'nfcbot', 'nicepedia', 'ninjastrikers', 'ninobot', 'ninobott',
        'ninthcircuit', 'niosh', 'nitlow', 'nitolw', 'njsbot', 'nli-wiki',
        'nlwikibots', 'nlwikt-tools', 'nn1l2bot', 'noaabot', 'noclaims',
        'nodejs-mw-oauth-tool', 'nodetree', 'nomad', 'nominatim',
        'nordic-museum-depicts', 'noref', 'notebooks', 'notif-bot',
        'not-in-the-other-language', 'npp', 'nppbrowser', 'nppdash', 'npp-lv',
        'nrhpservice', 'nsfw', 'nullbot', 'nullzero', 'nullzerobot',
        'nyandata', 'oabot', 'oabot-wd-game', 'oar', 'oauth-hello-world',
        'oauthtest', 'obaid', 'ocgepub', 'ocounter', 'ocr4wikisource',
        'ocrtoy', 'octodata', 'octrabot', 'odder-dev', 'oddol', 'okmaps',
        'olsibot', 'olympics', 'omarghridabot', 'oncall', 'onetools',
        'oojs-ui', 'ooui-debug', 'opendatasets', 'openhatch-wiki',
        'openipmap', 'openrefine-wikidata', 'openstack-browser',
        'openstack-browser-dev', 'oqtools', 'orator-matcher',
        'order-user-by-reg', 'ordia', 'orejasbot', 'ores', 'ores-afc',
        'ores-demos', 'ores-support-checklist', 'orphan-groups', 'orphantalk',
        'orpheus', 'orwell01', 'orwell02', 'os', 'oscoor', 'os-deprecation',
        'osm', 'osm4wiki', 'osm-add-tags', 'osmbstat', 'osmcounts',
        'osm-gadget', 'osm-gadget-leaflet', 'osmkmlmap', 'osmlint',
        'otrs-helper', 'otrsreports', 'oubli-signature-bot', 'ouda',
        'oudabot', 'outofband', 'outreachy-hiteshpr',
        'outreachy-recent-edits-tool', 'outreachy-sagorika1996',
        'outreachy-sayani-tool', 'outreachy-shipra',
        'outreachy-user-contribution-tool', 'outreachy-useredits',
        'outreachy-userrank', 'outreachy-user-ranking-tool',
        'outreachy-wikicv', 'outreacy-wikicv', 'owintes', 'p4-linkie',
        'pacetrack', 'pagecount', 'pagecounts', 'pagepile',
        'pagepile-visual-filter', 'pageshift', 'pageviews', 'pageviews-test',
        'paid', 'palmleaf-transcriber', 'pandata', 'panderine', 'panoviewer',
        'para', 'parliamentdiagram', 'parliament-diagram-generator', 'parsec',
        'passlicense', 'paste', 'pastebin', 'paste-test', 'pathbot-test-1',
        'pathoschild-contrib', 'pathway-viewer', 'patrall', 'patrollerinfo',
        'patrolstats', 'patrubot', 'pavlochembot', 'paws', 'paws-beta',
        'paws-dev', 'paws-public', 'paws-published', 'paws-stats',
        'paws-status', 'paws-support', 'payravi', 'pb', 'pbbot', 'peachy',
        'peachy-docs', 'pearbot', 'pearbot2', 'peek', 'perebot', 'perfectbot',
        'perfect-venn-diagram-generator', 'perflogbot', 'periodibot',
        'periodssuck', 'permission-denied-test', 'perrybot', 'personabot',
        'persondata', 'petscan-md', 'pg2ws', 'pgrmeval', 'phab-ban',
        'phabbot', 'phabricator-bug-status', 'phabricator-reporter',
        'phab-search', 'phabsearchemail', 'phabulous', 'phamhi-tool',
        'phantombot', 'phetools', 'phoenix9', 'phpcs', 'phpinfo', 'phragile',
        'piagetbot', 'piagetenwiki', 'pibot', 'pib-upload', 'pileviews',
        'ping08bot', 'pinyin-wiki', 'pipeng', 'pirsquared', 'pisgbot',
        'pitsilemu', 'plagiabot', 'plaigsossbot', 'plaintexteditcounter',
        'planettoearth', 'plantel2wiki', 'plasmahelp', 'platypus-qa',
        'plnode', 'plstools', 'pltools', 'pmidtool', 'poiimport',
        'popularpages', 'popularpages-dev', 'portal', 'portalbox',
        'portal-stats', 'position-holder-history', 'potd', 'potd-feed',
        'potd-viewer', 'potrace', 'poty', 'povoconta', 'powow', 'ppp-sparql',
        'precise-tools', 'prefbot', 'primary-sources-v2', 'primebot',
        'prime-draftnocat', 'primerpedia', 'prism', 'projanalysis',
        'project-fa', 'projector', 'projektneuheiten-feed', 'projetpp',
        'prometheus', 'prompter', 'proneval', 'proneval-gsoc17',
        'propertyuse', 'prop-explorer', 'prosjektbot', 'proxies',
        'prvnotifications', 'ptable', 'ptbot', 'ptbots', 'ptools', 'ptwikis',
        'pub', 'pubchem-wikidata-updates', 'purger',
        'push-notifications-helper', 'pv', 'pybot', 'pyshexy', 'pywikibot',
        'pywikibot-grrtbt', 'pywikibot-test', 'pywikibot-testwiki',
        'pywikibot-tw', 'pywikipedia', 'pywowbot', 'qedkbot', 'qic',
        'qrcode-generator', 'qsgenerator', 'quality-analyzer',
        'quality-assisted-editor', 'quarry', 'quarrybot-enwiki', 'quarry-dev',
        'quentintools', 'quentinv57-bots', 'quentinv57-common',
        'quentinv57-tools', 'query', 'query2map', 'query-universe',
        'quickcategories', 'quick-intersection', 'quickpreset-migrate',
        'quickquery', 'quickstatements', 'quips', 'quotable', 'quotenbot',
        'r96340-bot', 'raehhamsang', 'ragesossbot', 'railways', 'ralgisbot',
        'ramp', 'ramp2', 'random', 'random-featured', 'randomincategory',
        'rang', 'rangeblockfinder', 'rangecalc-improved', 'rangecontrib',
        'rank', 'rank1', 'rank4', 'raun', 'raunbot', 'raymond',
        'raymondyee-test', 'rchv', 'rcm', 'rcquery', 'rc-vikidia', 'reader',
        'readmore', 'reasomics', 'reasonator', 'rebot', 'recitation-bot',
        'recoin', 'recoin-sample', 'recommendation', 'recom-tool',
        'redirecter', 'redirectviews', 'redirtest', 'redpanda', 'redwarn',
        'refcreator', 'referee', 'referencebot', 'refill', 'refill-api',
        'reflinks', 'refswikipedia', 'reftoolbar', 'registro-cancellazioni',
        'reise-reise', 'relgen', 'remarkup2wikitext', 'rembot', 'reminderbot',
        'render', 'render-tests', 'repi', 'replacer', 'replag', 'repo',
        'reports', 'reportsbot', 'reports-bot', 'request', 'retractionbot',
        'revdiffsearch', 'revertstat', 'revi', 'revibot', 'revibot-i',
        'revibot-ii', 'revibot-iii', 'revibot-iv', 'reviewer', 'reviewers',
        'review-stats', 'reviewtools', 'revisions-blacklist', 'revisionstats',
        'revitalizebot', 'rezabot', 'reza-dev', 'rfahelper', 'rfastats',
        'rfa-tool', 'rfc-analyzer', 'rfx', 'rfx-dev', 'rhinosf1-afdclose',
        'ricordisamoa', 'ri-diff-fixture-updater', 'rightstool', 'rileybot',
        'rillke', 'rillke-node', 'rluts', 'rmstats', 'rm-stats', 'robin',
        'robokobot', 'roccerbot', 'roccerbot-new', 'rotatebot', 'rotbot',
        'rotpunkt-bot', 'roundtripping', 'roysmith-test', 'ruarbcom',
        'ruarbcom-js', 'rubinbot', 'rubinbot2', 'rubinbot3', 'ru_monuments',
        'ruprecht', 'ruptho-interaction-classifier', 'russbot',
        'rust-hello-world', 'ru-unreliable-music-sources', 'ruwikisource',
        'ruwn-misc', 'rxy', 'ryanbot', 'ryu', 'saami', 'sal', 'sammour',
        'samoabot', 'sanaa', 'saper', 'sau226test', 'sau226-wiki-bug-testing',
        'sbl', 'sbot', 'scaldingbot', 'scfc-test-can-be-deleted-anytime',
        'schema2code', 'scholia', 'scholiaanalytics', 'scholia-analytics',
        'scholia-dev', 'schoolwiki', 'schubota', 'scottytools',
        'scotus-recordings', 'scratch', 'scribe', 'scrotbot', 'sdbot', 'sdm',
        'sdzerobot', 'search', 'searchdiff', 'searchsbl', 'section-links',
        'section-redirect', 'section-watchlist', 'security', 'secwatch',
        'seealsology', 'seijabot', 'sejmedits', 'selim', 'sequencer',
        'sergobot-statistics', 'serobot', 'service001', 'serviceawards',
        'sficbot', 'sge-jobs', 'sge-status', 'shbibbot', 'shbot',
        'shex-author', 'shexia', 'shex-simple', 'shexstatements',
        'shextranslator', 'shfbot', 'shields', 'shilad', 'shortnames',
        'shorturls', 'shotbot', 'shri', 'shrinitools', 'shrugbot', 'shtest',
        'shuaib', 'shuaib-bot', 'shumariyat', 'sibu', 'sibutest', 'sighting',
        'sigma', 'signature-checker', 'signature-manquante-bot', 'signatures',
        'sign-language-browser', 'signpost', 'signpostlab', 'similarity',
        'simple', 'simplecommonstransfer', 'simplewd', 'simplewikt',
        'sistercities', 'sit', 'sitematrix', 'sites', 'siteviews', 'siwiki',
        'sixdegrees', 'slakrtools', 'sleepybot', 'slf', 'slipjack',
        'slow-parse', 'slumpartikel', 'smv-description-translations',
        'sn1pebot', 'snaevar-bot', 'snapshots', 'snowolf', 'socksfinder',
        'sonarqubebot', 'soni', 'sonitool', 'sourcemd', 'southparkfan',
        'soweego', 'sowhy', 'sp1', 'spacemedia', 'spamforbreakfast',
        'spamwatch', 'sparqlblocks', 'sparrow', 'spbot', 'spdx',
        'speedpatrolling', 'speed-patrolling', 'speedydeletionwikia',
        'spellbot', 'spellbot-dev', 'spellcheck', 'sphinxcapt-leaderboard',
        'spiarticleanalyzer', 'spi-tools', 'spi-tools-dev', 'splinetools',
        'sqid', 'sql-optimizer', 'sqoop-tool', 'squirrelnestbot',
        'squirrelnest-upf', 'srish', 'srr-sandbox', 'srwiki', 'srwiki-dev',
        'stabilizerbot', 'stang', 'stashbot', 'static', 'static-browser',
        'static-bz', 'statistics', 'statistics-api', 'statisticsbot', 'stats',
        'status', 'steinsplitter', 'steinsplitter2', 'stemmeberettigelse',
        'stereoskopie', 'stewardbots', 'stewbots', 'stimmberechtigung',
        'stockholm-mania', 'stradbot', 'strephit', 'strikertest2017-08-23',
        'stub', 'studiesworld', 'stwalkerster', 'styleguide', 'stylize',
        'submitter', 'suchaserver', 'suggestbot', 'suggestor', 'suha',
        'sulinfo', 'summary-generator', 'super-admin-bot', 'supercount',
        'superyetkin', 'superzerocool', 'suyash-sandarbh', 'svenbot',
        'svgcheck', 'svgedit', 'svgedit-dashboard', 'svg-map-maker',
        'svgtranslate', 'svgtranslate-test', 'svgworkaroundbot',
        'svwikihostbot', 'svwiktionary', 'swedishforsamling', 'swviewer',
        'sybot51', 'symabot', 'symacbot', 'sync-badges', 't13bot',
        't187305-demo', 't1943bot', 'tabernacle', 'tabletop',
        'tabular-wikidata', 'tabulist', 'tahir', 'taim-bot', 'tamilwikitools',
        'tantan-www', 'taqpol-test', 'tarrow-dev', 'tasmania', 'taweetham',
        'taxobot', 'taxoboxalyzer', 'taxonbot', 'taxonbota', 'taxonkatbot',
        'tb-dev', 'tbloemink', 'tc-rc', 'tedbot', 'teg', 'tei2wikitext',
        'telefabot', 'telegrambot', 'telegram-wikilinksbot', 'telnet',
        'templatecheck', 'templatecount', 'templatedata-filler',
        'templatehoard', 'templatetiger', 'templatetransclusioncheck',
        'templator', 'tenst', 'tessdata', 'tesseract-ocr-service', 'test',
        'test0', 'test001', 'test2', 'test3', 'test999',
        'test-generic-webservice', 'testingtool', 'test-lighttpd-precise',
        'test-lighttpd-trusty', 'test-music1201', 'test-stats',
        'test-t188680', 'test-tool', 'testtool-101', 'test-vvv',
        'test-webservice-generic', 'testwiki', 'testwikis', 'testwikistats',
        'tewptrends', 'texbot', 'text2hash', 'textcatdemo', 'tfaprotbot',
        'tgwikibot', 'thanatos', 'thankyou', 'thebook', 'thedavetool',
        'thedavetools', 'thehelpfulbot', 'themesquitobot', 'theoslittlebot',
        'thesandbot', 'thibaut120094', 'thibtools', 'thparkthsql',
        'threed2commons', 'tichy', 'tilde', 'tilescraper', 'time-convertor',
        'timerelengteam', 'timescale', 'title-search', 'tivenbot', 'tmg',
        'toc', 'tom29739-testing', 'tombot3', 'tomthirteen', 'tool',
        'tool123', 'tool-account', 'tool-db-usage', 'toolflow', 'toolforge',
        'toolforge-gallery', 'tool-gallery', 'toolhub', 'tool-log-stats',
        'toolpilot', 'tools', 'toolschecker', 'toolschecker-ge-ws',
        'toolschecker-k8s-ws', 'toolscript', 'tools-dashboard', 'toolserver',
        'toolserverdb', 'toolserver-home-archive', 'tools-gallery',
        'tools-info', 'tooltranslate', 'toolviews', 'top500importer',
        'topic-finder', 'topicmatcher', 'topviews', 'topviews-test',
        'torintool', 'torproxy', 'totoazero', 'tour', 'tpbot', 'tptools',
        'traffic-grapher', 'train-blockers', 'translate', 'translate-bot',
        'translate-category', 'translatemplate', 'translation-server',
        'tree-of-life', 'trend', 'tristessa', 'tronbot', 'trusty-deprecation',
        'trusty-tools', 'tsbot', 'tsreports', 'tsreports-dev', 'tts',
        'tts-comparison', 'ttt', 'tulsibot', 'tusc', 'tweep', 'twinkle',
        'twitterbot', 'twitter-retweet-bot', 'twitter-to-commons', 'twl',
        'twl17', 'twlbot', 'twltools', 'typo-categorizer', 'typos',
        'typoscan', 'uaachecker', 'ukbot', 'ukwiki-analysis', 'unblock',
        'unblockbot', 'unique', 'universalviewer', 'un-ocha-maps',
        'unpatrollededitstats', 'unpaywall-importer', 'unpkg',
        'uploadhelper-ir', 'upload-stats-bot', 'urbanecmbot',
        'urbanecm-test-1', 'urdubot', 'urdusign', 'urduspellchecker',
        'url2commons', 'url-converter', 'urlinktranslator', 'us', 'usage',
        'user', 'user-activity', 'user-contributions-feed', 'useredit',
        'useredit2', 'useredits', 'useredits1', 'usergraph', 'user-id',
        'userimpact', 'usernamesearch', 'userrank', 'usersearch',
        'user-stats', 'userviews', 'usrd-tools', 'usualsuspects', 'ut-bot',
        'ut-interwiki-bot', 'ut-iw-bot', 'vagrant2', 'vagrant-test',
        'valhallasw-testing-tool', 'validator', 'valstat', 'valutabot',
        'vcat', 'veblenbot', 'vector-dark', 'vectorizer', 'veertje-tools',
        'vendor', 'verb-import-game', 'verification-pages', 'versions',
        'viafbot', 'vic', 'video2commons', 'video2commons-socketio',
        'video2commons-test', 'video-cat-bot', 'videoconvert',
        'videoconvertion', 'video-cut-tool', 'video-cut-tool-back-end',
        'video-cut-tool-front-end', 'videotutorials', 'vipbot',
        'vip-space-media', 'vishwin', 'visualcategories', 'visualeditor',
        'vitalarticlesbot', 'vizbot', 'vltools', 'vocabulary-index',
        'voiceintro', 'volby2wiki', 'voxelbot', 'vrb', 'vtwo', 'vuln-checker',
        'vvoters', 'v-wiki', 'wafaashohdy', 'wahldiagramm', 'wahrani', 'wakt',
        'wakt-beta', 'wam', 'wam-article-suggestions', 'wanderwiki',
        'wantedpages', 'warped-to-iframe', 'watchr', 'watch-translations',
        'watroles', 'wawewewi', 'wb2rdf', 'wbwcalculator', 'wcam-bot', 'wcdo',
        'wcna-2018-registration', 'wd-analysis', 'wd-analyst', 'wdapi',
        'wd-art', 'wdbeoupdate', 'wd-books-cleaner', 'wdcat',
        'wd-constraints-precheck', 'wd-depicts', 'wdgraph', 'wdic',
        'wdimagecheck', 'wd-image-positions', 'wdmap', 'wdml', 'wdmm',
        'wdprop', 'wdpv', 'wdq2sparql', 'wdq_checker', 'wdq-checker',
        'wdqs-tutorial', 'wdqs-wmil-tutorial', 'wd-query-builder', 'wd-rank',
        'wdrdr', 'wdreconcile', 'wd-ref-island', 'wd-shex-infer', 'wdumps',
        'wdvaliditycheck', 'wdvd', 'wd-word-cloud',
        'weapon-of-mass-description', 'weapon-of-mass-description-test',
        'weather', 'webarchivebot', 'webchat', 'weeklypedia', 'welcomebot',
        'welcomebots-bn', 'wembedder', 'wfind', 'whichsub', 'whodunnit',
        'whois', 'whois-referral', 'whois-referral-dev', 'whymbot', 'widar',
        'wigi', 'wiki', 'wiki13', 'wiki17an-watcher', 'wiki2email',
        'wiki2html', 'wiki2prop', 'wiki3d', 'wiki-android-apps',
        'wikiarthistory', 'wiki-as-git', 'wikiatlas2014',
        'wikibase-databridge-storybook', 'wikibase-nearest-neighbors',
        'wikibase-preview', 'wikibase-termbox-storybook', 'wikibattle',
        'wikiblame', 'wikibookassamese', 'wikibot', 'wikibugs', 'wikicaptcha',
        'wikicite-dashboard', 'wikicitevis', 'wikicontest', 'wikicontrib',
        'wikicup', 'wikidata-analysis', 'wikidata-annotation-tool',
        'wikidata-compare', 'wikidata-delinker', 'wikidata-edits',
        'wikidata-exports', 'wikidata-externalid-url', 'wikidata-game',
        'wikidatagroup', 'wikidata-janitor', 'wikidata-map',
        'wikidata-nolabels', 'wikidata-primary-sources', 'wikidata-reconcile',
        'wikidata-redirects-conflicts-reports', 'wikidata-slicer',
        'wikidata-terminator', 'wikidata-timeline', 'wikidata-todo',
        'wikidata-trends', 'wikidiff2-dev-test', 'wikidipendenza',
        'wikiedudashboard', 'wikiedudashboard-test', 'wikiemojibot',
        'wikifactmine-api', 'wikifactmine-pipeline', 'wikifeeds',
        'wikifile-transfer', 'wiki-geo', 'wikigrade', 'wikigraph', 'wikigrok',
        'wikihistory', 'wikihoaxbuster', 'wikiholic', 'wikiinfo',
        'wikiintent', 'wiki-irc', 'wikijourney', 'wikilaeum', 'wikilinkbot',
        'wikilint', 'wikilist', 'wikilogos', 'wikiloop',
        'wikiloop-testflight', 'wikiloves', 'wikilovesdownloads',
        'wiki-loves-earth-2019', 'wikiloveslove', 'wikimap', 'wikimediadc',
        'wikimedia-france', 'wikimediaui-styleguide', 'wikiment',
        'wikimetrics', 'wikimetrics-development', 'wikimetrics-production',
        'wikimetrics-staging', 'wikiminiatlas', 'wiki-needs-pictures',
        'wikinews', 'wikinews-importer', 'wikinews-pagestats', 'wikinity',
        'wikinity-test', 'wikintu', 'wiki-osm-markers', 'wikioverdata',
        'wikipagestats', 'wikipathways2wiki', 'wikipedia-android-builds',
        'wikipedia-contributor-locations', 'wikipedia-fetch-content',
        'wikipedia-library', 'wikipedia-readability',
        'wikipedia-zh-irc-query', 'wikipedia-zh-message-transport',
        'wikipheme', 'wikiplayer', 'wikiportretdev', 'wikiprovenance',
        'wikipulse', 'wikiradio', 'wikiresearch', 'wiki-retweet-bot',
        'wikiscanner', 'wikisense', 'wikishield', 'wikishootme', 'wikisoba',
        'wikisource-api', 'wikisource-bot', 'wikisource-penguin-classics',
        'wikisource-tweets', 'wikistats', 'wikistreak', 'wikistream',
        'wikistreams', 'wikitable', 'wikitabs', 'wiki-talk', 'wiki-talk2',
        'wikitanvirbot', 'wiki-task-locator', 'wikitasks', 'wikitei',
        'wiki-tennis', 'wikitest-rtl', 'wikitext-deprecation', 'wikitime',
        'wiki-todo', 'wikitool', 'wikitools', 'wiki-topic', 'wikitranslator',
        'wikitree', 'wikitrends', 'wikitrip', 'wikitweets', 'wikiviewstats',
        'wikiviewstats2', 'wikivisualization', 'wikiviz', 'wikivoyage',
        'wikiwatchdog', 'wikiwhatsappbot', 'wikiwho', 'wiki-zulip-bot',
        'wiktioutils', 'wikt-mwtest', 'wikyrillomat', 'william-avery-bot',
        'winput', 'winter', 'wiper', 'wiper-languagetool', 'withoutaname',
        'wits', 'wiwosm', 'wizarbot', 'wle', 'wlm', 'wlm-analytics',
        'wlm-de-redirect', 'wlm-de-utils', 'wlmin', 'wlm-italy',
        'wlmitaly2019', 'wlmjudging', 'wlm-jury-at', 'wlm-jury-yarl',
        'wlm-maps', 'wlm-nl-table-gen', 'wlmpacommonscat', 'wlm-stats',
        'wlmtrafo', 'wlmuk', 'wlmus', 'wlm-us', 'wlxjury', 'wm-bot',
        'wm-cee-spring', 'wmcharts', 'wm-commons-emoji-bot', 'wmcounter',
        'wmcsbot', 'wmcz', 'wmde-access', 'wmde-editconflict-test',
        'wmde-graphql-demo', 'wmde-inline-movedparagraphs',
        'wmde-reference-previews', 'wmde-uca-test', 'wmde-wd-team',
        'wmfdbbot', 'wmflabs-collection', 'wmf-sitematrix', 'wmf-task-samtar',
        'wmf-wiki-info', 'wmit', 'wmk-dev', 'wmk-tools', 'wm-metrics',
        'wmopbot', 'wmpt', 'wmtran', 'wmukevents', 'wmve', 'wmve-dev',
        'wm-ve-needcheck-reporter', 'wnegar', 'women-in-red', 'wordcount',
        'wordpile', 'wordtowiki', 'wordtowiki-dev', 'worklist-tool', 'wpb',
        'wpcleaner', 'wpp', 'wprequests', 'wp-signpost', 'wptestblog',
        'wptestblog2', 'wpv', 'wp-world', 'wrating', 'wrcp', 'ws2wd',
        'ws-cat-browser', 'wscontest', 'wsdetool', 'wsexport',
        'wsexport-test', 'ws-google-ocr', 'w-slackbot', 'wsm', 'ws-search',
        'wudele', 'wugbot', 'www', 'www-portal-builder', 'www-portal-staging',
        'wyimportbot', 'xdebugtesting', 'xdebugtesting1', 'xdebugtesting2',
        'xecfork', 'xfd-stats', 'xiplus', 'xlinkbot', 'xmlfeed',
        'xn--dk8hv9g', 'xoxoxo-dev', 'xqtools', 'xslack', 'xstools', 'xtools',
        'xtools-articleinfo', 'xtools-autoedits', 'xtools-dev', 'xtools-ec',
        'xtools-mab-dev', 'xtools-pages', 'xxn-testtool', 'xxn-tools',
        'xyzbot', 'yabbr', 'yabot', 'yacbot', 'yadfa', 'yadkard', 'yapperbot',
        'yarl', 'yashe', 'yellowbot', 'yellowcard', 'yemen', 'yichengtry',
        'yifeibot', 'yjsw', 'youtube-channel', 'ytcleaner', 'ytrb', 'yunomi',
        'zayenbot', 'zbot', 'zedlikbot', 'zenithbot', 'zerabot',
        'zhaofeng-test', 'zhdeletionpedia', 'zhnotofu', 'zhtest',
        'zhuyifei1999-test', 'zhwiki', 'zhwiki-qualifications-check',
        'zhwiki-teleirc', 'zhwiki-username-check', 'zimmerbot', 'zkbot',
        'zonestamp', 'zoomable-images', 'zoomproof', 'zoomviewer',
        'zoranzoki21bot', 'zoranzoki21wiki', 'zppixbot', 'zppixbot-test',
        'zumraband', 'zurichpopulation', 'zygimantus-dev', 'zygserv',
    }

    if allowed[toolname] then
        return true
    end

    return false
end

--- Generate the redirect URL
-- @param toolname Name of the tool
-- @param path Path fragment of URL
function compute_redirect_url(toolname, path)
    -- toolname and path were checked in the previous function
    local is_args = ''
    if ngx.var.is_args then
        is_args = ngx.var.is_args
    end
    local args = ''
    if ngx.var.args then
        args = ngx.var.args
    end

    return 'https://' .. toolname .. '.toolforge.org' .. path .. is_args .. args
end

--- Look up a canonical redirect target for a given tool
-- @param toolname Name of the tool
-- @param path Path fragment of the URL
function try_redirect_and_exit_if_ok(toolname, path)
    if not toolname or not path then
        return
    end

    if not toolname_allowed(toolname) then
        return
    end

    -- We are redirecting the following:
    --- from  tools.wmflabs.org/$tool/index.php?param=foo
    --- to    $tool.toolforge.org/index.php?param=foo
    -- redirect happens right here; nothing else is evaluated in the nginx conf
    return ngx.redirect(compute_redirect_url(toolname,path), 308)
end

local captures = ngx.re.match(ngx.var.uri, "^/([^/]*)(/.*)?$")
local toolname = captures[1]
local path = captures[2] or "/"
try_redirect_and_exit_if_ok(toolname, path)

-- general error case:
return ngx.redirect('https://www.toolforge.org/')
