import json


def should_insert_mysql(e):
    """
    Given an Event dict e, returns true if this event should be inserted into the
    EventLogging analytics MySQL database, or false otherwise.  This is used
    to keep events generated by unwanted bots out of MySQL.
    """
    user_agent_dict = json.loads(e['userAgent'])
    try:
        return (not user_agent_dict['is_bot']) or (user_agent_dict['is_mediawiki'])
    except (ValueError, KeyError):
        return True
