import json
import logging


def should_insert_event(e):
    """
    Given an Event dict e, returns true if this event should be inserted into the
    EventLogging storage (MySQL), or false otherwise.  This is used
    to filter out events generated by unwanted bots.
    """
    # If no userAgent information, then insert anyway.
    if 'userAgent' not in e:
        return True

    if isinstance(e['userAgent'], dict):
        user_agent_dict = e['userAgent']
    else:
        try:
            user_agent_dict = json.loads(e['userAgent'])
        except Exception as ex:
            logging.warn('userAgent is a {}.  Skipping insertion. userAgent: {}. ({})'.format(
                type(e['userAgent']), e['userAgent'], ex
            ))
            return False

    is_bot = user_agent_dict.get('is_bot', False)
    is_mediawiki = user_agent_dict.get('is_mediawiki', False)

    # Don't insert events generated by bots unless they are mediawiki bots.
    if is_bot and not is_mediawiki:
        return False
    else:
        if isinstance(e['userAgent'], dict):
            e['userAgent'] = json.dumps(e['userAgent'])
        return True
