import json


def should_insert_event(e):
    """
    Given an Event dict e, returns true if this event should be inserted into the
    EventLogging storage (MySQL), or false otherwise.  This is used
    to filter out events generated by unwanted bots.
    """
    user_agent_dict = json.loads(e['userAgent'])

    is_bot = user_agent_dict.get('is_bot', false)
    is_mediawiki = user_agent_dict.get('is_mediawiki', false)

    # Don't insert events generated by bots unless they are mediawiki bots.
    if is_bot and not is_mediawiki:
        return false
    else:
        return true
