class profile::openstack::codfw1dev::keystone::service(
    $version = lookup('profile::openstack::codfw1dev::version'),
    $region = lookup('profile::openstack::codfw1dev::region'),
    Array[Stdlib::Fqdn] $openstack_controllers = lookup('profile::openstack::codfw1dev::openstack_controllers'),
    $osm_host = lookup('profile::openstack::codfw1dev::osm_host'),
    $db_host = lookup('profile::openstack::codfw1dev::keystone::db_host'),
    $token_driver = lookup('profile::openstack::codfw1dev::keystone::token_driver'),
    $db_pass = lookup('profile::openstack::codfw1dev::keystone::db_pass'),
    $nova_db_pass = lookup('profile::openstack::codfw1dev::nova::db_pass'),
    $ldap_hosts = lookup('profile::openstack::codfw1dev::ldap_hosts'),
    $ldap_user_pass = lookup('profile::openstack::codfw1dev::ldap_user_pass'),
    $wiki_status_consumer_token = lookup('profile::openstack::codfw1dev::keystone::wiki_status_consumer_token'),
    $wiki_status_consumer_secret = lookup('profile::openstack::codfw1dev::keystone::wiki_status_consumer_secret'),
    $wiki_status_access_token = lookup('profile::openstack::codfw1dev::keystone::wiki_status_access_token'),
    $wiki_status_access_secret = lookup('profile::openstack::codfw1dev::keystone::wiki_status_access_secret'),
    $wiki_consumer_token = lookup('profile::openstack::codfw1dev::keystone::wiki_consumer_token'),
    $wiki_consumer_secret = lookup('profile::openstack::codfw1dev::keystone::wiki_consumer_secret'),
    $wiki_access_token = lookup('profile::openstack::codfw1dev::keystone::wiki_access_token'),
    $wiki_access_secret = lookup('profile::openstack::codfw1dev::keystone::wiki_access_secret'),
    Array[Stdlib::Fqdn] $designate_hosts = lookup('profile::openstack::codfw1dev::designate_hosts'),
    $labweb_hosts = lookup('profile::openstack::codfw1dev::labweb_hosts'),
    $puppetmaster_hostname = lookup('profile::openstack::codfw1dev::puppetmaster_hostname'),
    $auth_port = lookup('profile::openstack::base::keystone::auth_port'),
    $public_port = lookup('profile::openstack::base::keystone::public_port'),
    Stdlib::Fqdn $keystone_fqdn           = lookup('profile::openstack::codfw1dev::keystone_api_fqdn'),
    Boolean $daemon_active = lookup('profile::openstack::codfw1dev::keystone::daemon_active'),
    String $wsgi_server = lookup('profile::openstack::codfw1dev::keystone::wsgi_server'),
    Stdlib::IP::Address::V4::CIDR $instance_ip_range = lookup('profile::openstack::codfw1dev::keystone::instance_ip_range', {default_value => '0.0.0.0/0'}),
    String $wmcloud_domain_owner = lookup('profile::openstack::codfw1dev::keystone::wmcloud_domain_owner'),
    String $bastion_project_id = lookup('profile::openstack::codfw1dev::keystone::bastion_project_id'),
    Boolean $enforce_policy_scope = lookup('profile::openstack::codfw1dev::keystone::enforce_policy_scope'),
    Boolean $enforce_new_policy_defaults = lookup('profile::openstack::codfw1dev::keystone::enforce_new_policy_defaults'),
    Stdlib::Port $admin_bind_port = lookup('profile::openstack::codfw1dev::keystone::admin_bind_port'),
    Stdlib::Port $public_bind_port = lookup('profile::openstack::codfw1dev::keystone::public_bind_port'),
    Array[String] $service_domains = lookup('profile::openstack::codfw1dev::keystone::service_domains'),
    ) {

    class {'::profile::openstack::base::keystone::service':
        daemon_active               => $daemon_active,
        version                     => $version,
        region                      => $region,
        openstack_controllers       => $openstack_controllers,
        osm_host                    => $osm_host,
        db_host                     => $db_host,
        token_driver                => $token_driver,
        db_pass                     => $db_pass,
        nova_db_pass                => $nova_db_pass,
        ldap_hosts                  => $ldap_hosts,
        ldap_user_pass              => $ldap_user_pass,
        wiki_status_consumer_token  => $wiki_status_consumer_token,
        wiki_status_consumer_secret => $wiki_status_consumer_secret,
        wiki_status_access_token    => $wiki_status_access_token,
        wiki_status_access_secret   => $wiki_status_access_secret,
        wiki_consumer_token         => $wiki_consumer_token,
        wiki_consumer_secret        => $wiki_consumer_secret,
        wiki_access_token           => $wiki_access_token,
        wiki_access_secret          => $wiki_access_secret,
        designate_hosts             => $designate_hosts,
        labweb_hosts                => $labweb_hosts,
        wsgi_server                 => $wsgi_server,
        instance_ip_range           => $instance_ip_range,
        wmcloud_domain_owner        => $wmcloud_domain_owner,
        bastion_project_id          => $bastion_project_id,
        enforce_policy_scope        => $enforce_policy_scope,
        enforce_new_policy_defaults => $enforce_new_policy_defaults,
        keystone_fqdn               => $keystone_fqdn,
        public_bind_port            => $public_bind_port,
        admin_bind_port             => $admin_bind_port,
        service_domains             => $service_domains,
    }
    contain '::profile::openstack::base::keystone::service'

    class {'::profile::openstack::base::keystone::hooks':
        version     => $version,
        wsgi_server => $wsgi_server,
    }
    contain '::profile::openstack::base::keystone::hooks'

    class {'::openstack::keystone::monitor::services':
        active      => true,
        auth_port   => $auth_port,
        public_port => $public_port,
    }
    contain '::openstack::keystone::monitor::services'
}
