global : {
    custom-dir : ["/var/lib/puppet/lib/facter"]
    # We don't use external facts distributed via puppet, but harmless to
    # retain support
    external-dir : ["/var/lib/puppet/facts.d"]
}
# Disable cloud.provider lookup. This takes almost 30 seconds
# on cloud-vps hosts, and we don't use the fact anywhere.
# Due to an upstream issue, we have to disable the EC2 group
# for the other block to take effect. This is discussed here:
#
#  https://github.com/puppetlabs/facter/issues/2690
#
facts : {
    blocklist : [ "EC2", "cloud.provider" ],
}
