# SPDX-License-Identifier: Apache-2.0
# @summary provisions the puppet-merge cli tools used in production to This is a private class called
#   by profile::puppetserver::git
# @param ca_server the configured ca server
# @param servers The list of servers in the custer
class merge_cli (
    Stdlib::Host        $ca_server,
    Array[Stdlib::Host] $servers = []
) {
    # Not sure this helps much as im pretty sure it only restricts to the same module

    $_servers = $servers - $facts['networking']['fqdn']

    # TODO: refactor so everything is treated equally appart from the ca_server
    $puppet_merge_conf = @("CONF")
    # Generated by Puppet
    MASTERS="${_servers.join(' ')}"
    WORKERS="${_servers.join(' ')}"
    CA_SERVER="${ca_server}"
    | CONF

    file { '/etc/puppet-merge.conf':
        ensure  => file,
        owner   => 'root',
        group   => 'root',
        mode    => '0555',
        content => $puppet_merge_conf,
    }

    # TODO: move the source to this module
    file { '/usr/local/bin/puppet-merge':
        ensure => file,
        owner  => 'root',
        group  => 'root',
        mode   => '0555',
        source => 'puppet:///modules/merge_cli/puppet-merge.sh',
    }

    file { '/usr/local/bin/puppet-merge.py':
        ensure => file,
        owner  => 'root',
        group  => 'root',
        mode   => '0555',
        source => 'puppet:///modules/merge_cli/puppet-merge.py',
    }
}
