#!/usr/bin/python
import re
import sys
from optparse import OptionParser
sys.path.append('/var/lib/gerrit2/review_site/etc')
import scriptconfig

def main():
	parser = OptionParser(conflict_handler="resolve")
	parser.set_usage("change-merged --change <change id> --change-url <change url> --project <project name> --branch <branch> --submitter <submitter> --commit <commit>")
	parser.add_option("--change", dest="change")
	parser.add_option("--change-url", dest="changeurl")
	parser.add_option("--project", dest="project")
	parser.add_option("--branch", dest="branch")
	parser.add_option("--submitter", dest="submitter")
	parser.add_option("--commit", dest="commit")
	(options, args) = parser.parse_args()

	if scriptconfig.logdir and scriptconfig.logdir[-1] == '/':
		scriptconfig.logdir = scriptconfig.logdir[0:-1]
	if options.project in scriptconfig.filenames: 
		filename = scriptconfig.logdir + "/" + scriptconfig.filenames[options.project]
	f = open(filename, 'a')
	f.write("Change merged: " + re.sub(' \(.*', "", options.submitter) + '; [' + options.project + "] (" + options.branch + ") - " + options.changeurl + "\n")
	f.close()

if __name__ == "__main__":
	main()
