#!/usr/bin/python
import re
import sys
from hookhelper import HookHelper
sys.path.append('/var/lib/gerrit2/review_site/etc')

class ChangeRestored(HookHelper):
	def run(self):
		self.parser.set_usage("change-restored --change <change id> --change-url <change url> --project <project name> --branch <branch> --restorer <restorer> --reason <reason>")
		self.parser.add_option("--restorer", dest="restorer")
		self.parser.add_option("--reason", dest="reason")
		(options, args) = self.parser.parse_args()
		reason = options.reason.splitlines()
		if reason:
			reason = reason[0]
			if len(reason) > 103:
				reason = reason[0:100] + "..."
		else:
			reason = "(no reason)"
		message = "Change restored: " + re.sub(' \(.*', "", options.restorer) + '; "' + reason + '" [' + options.project + "] (" + options.branch + ") - " + options.changeurl + "\n"
		self.log_to_file(options.project, options.branch, message)

if __name__ == "__main__":
	hook = ChangeRestored()
	hook.run()
