#!/usr/bin/python
import re
import sys
from hookhelper import HookHelper
sys.path.append('/var/lib/gerrit2/review_site/etc')
import hookconfig

class ChangeMerged(HookHelper):
	def run(self):
		self.parser.set_usage("change-merged --change <change id> --change-url <change url> --project <project name> --branch <branch> --submitter <submitter> --commit <commit> --uploader <uploader>")
		self.parser.add_option("--submitter", dest="submitter")
		self.parser.add_option("--commit", dest="commit")
		self.parser.add_option("--uploader", dest="uploader")
		(options, args) = self.parser.parse_args()
		user = re.sub(' \(.*', "", options.submitter)
		message = "Change merged: " + user + '; [' + options.project + "] (" + options.branch + ") - " + options.changeurl + "\n"
		self.log_to_file(options.project, options.branch, message, user)
		# Resolve any RT tickets that this change mentions as resolved
		self.update_rt(options.change, options.changeurl)

if __name__ == "__main__":
	hook = ChangeMerged()
	hook.run()
