#!/usr/bin/python
import re
from optparse import OptionParser

def main():
	parser = OptionParser(conflict_handler="resolve")
	parser.set_usage("change-merged --change <change id> --change-url <change url> --project <project name> --branch <branch> --submitter <submitter> --commit <commit>")
	parser.add_option("--change", dest="change")
	parser.add_option("--change-url", dest="changeurl")
	parser.add_option("--project", dest="project")
	parser.add_option("--branch", dest="branch")
	parser.add_option("--submitter", dest="submitter")
	parser.add_option("--commit", dest="commit")
	(options, args) = parser.parse_args()

	f = open('/var/lib/gerrit2/review_site/logs/gerrit_bot.log', 'a')
	f.write("Change merged: " + re.sub(' \(.*', "", options.submitter) + ';'  + options.project + "] (" + options.branch + ") - " + options.changeurl + "\n")
	f.close()

if __name__ == "__main__":
	main()
