#!/usr/bin/python
import re
import sys
from hookhelper import HookHelper
sys.path.append('/var/lib/gerrit2/review_site/etc')
import hookconfig


class CommentAdded(HookHelper):
    def run(self):
        self.parser.set_usage("comment-added --change <change id> --project <project name> --branch <branch> --author <comment author> --uploader <uploader> --commit <commit> --comment <comment> [--<approval category id> <score> --<approval category id> <score> ...]")
        self.parser.add_option("--author", dest="author")
        self.parser.add_option("--uploader", dest="uploader")
        self.parser.add_option("--commit", dest="commit")
        self.parser.add_option("--comment", dest="comment")
        self.parser.add_option("--topic", dest="topic")
        self.parser.add_option("--Verified", dest="verified")
        self.parser.add_option("--Code-Review", dest="codereview")
        self.parser.add_option("--is-draft", dest="draft")
        (options, args) = self.parser.parse_args()
        if options.draft == "true":
            return  # Don't report drafts to IRC!
        comment = re.sub(r"^\s*Patch Set \d+:.*$", '', options.comment, flags=re.MULTILINE)
        comment = re.sub(r"^\s*\(\d+ comments\).*$", '', comment, flags=re.MULTILINE).strip().splitlines()
        if comment:
            comment = comment[0]
            if len(comment) > 103:
                comment = comment[0:100] + "..."
        else:
            return
        review = ""
        if options.verified:
            review = review + "; V: " + options.verified
        if options.codereview:
            review = review + " C: " + options.codereview + "; "
        user = re.sub(' \(.*', "", options.author)
        # These users are annoying, ignore them
        if user in hookconfig.spammyusers:
            return
        message = "New review: " + user + '; "' + comment + '" [' + options.project + "] (" + options.branch + ")" + review + " - " + options.changeurl + "\n"
        self.log_to_file(options.project, options.branch, message, user)

if __name__ == "__main__":
    hook = CommentAdded()
    hook.run()
