#!/usr/bin/env python
import sys
import re
from hookhelper import HookHelper

sys.path.append('/var/lib/gerrit2/review_site/etc')
import hookconfig


class PatchsetCreated(HookHelper):
    def run(self):
        self.parser.set_usage("patchset-created --change")
        self.parser.add_option("--uploader", dest="uploader")
        self.parser.add_option("--commit", dest="commit")
        self.parser.add_option("--patchset", dest="patchset", type="int")
        self.parser.add_option("--is-draft", dest="draft")
        self.parser.add_option("--topic", dest="topic")
        (options, args) = self.parser.parse_args()
        if not options.change or not options.change.isalnum():
            self.parser.error("No change id, or changeid invalid")
        if hookconfig.debug:
            sys.stderr.write("Patchset passed in: " + str(options.patchset) + "\n")
        if options.draft == "true":
            return  # Don't report drafts to IRC!
        subject = self.get_subject(options.change)
        user = re.sub(' \(.*', "", options.uploader)
        message = "New patchset: " + user + '; "' + subject + '" [' + options.project + "] (" + options.branch + ") - " + options.changeurl + "\n"
        self.log_to_file(options.project, options.branch, message, user)

if __name__ == '__main__':
    hook = PatchsetCreated()
    hook.run()
