#!/bin/sh

if [ -z $1 ]; then
    echo "Usage $0 <pid of nodepool>"
    exit 1
fi
PID=$1
kill -USR1 $PID

if [ -n "${PID:-}" ]; then
    i=0
    while kill -0 "${PID:-}" 2> /dev/null;  do
        if [ $i -eq '0' ]; then
            echo -n " ... waiting for Nodepool tasks to complete "
        else
            echo -n "."
        fi
        i=$(($i+1))
        sleep 1
    done
    echo "done"
fi
