set termguicolors
set background=dark
colorscheme koehler
set backspace=indent,eol,start
set autoindent
set ts=4
set shiftwidth=4
set expandtab
set showmatch
set ignorecase
set smartcase
set incsearch
set hlsearch
set pastetoggle=
set history=1000
set ruler
set showcmd
set listchars=tab:>-,trail:-
set list
set cmdheight=3
set number
set cursorline
set showmatch
set foldmethod=indent
set foldlevel=99
set encoding=utf-8
let python_highlight_all = 1
syntax on
