# SPDX-License-Identifier: Apache-2.0
# event MPM
#
# This file is managed by puppet, any manual changes will be deleted on the
# next puppet run
#
# StartServers: initial number of server processes to start
# MinSpareThreads: minimum number of worker threads which are kept spare
# MaxSpareThreads: maximum number of worker threads which are kept spare
# ThreadsPerChild: constant number of worker threads in each server process
# MaxRequestWorkers: maximum number of worker threads
# MaxConnectionsPerChild: maximum number of requests a server process serves
StartServers            4
MinSpareThreads         250
MaxSpareThreads         250
ThreadLimit             250
ThreadsPerChild         250
MaxRequestWorkers       1000
MaxConnectionsPerChild  0
AsyncRequestWorkerFactor 8

