#!/bin/bash
# Shell script to install the source code for an installed Debian
# package into /usr/src.
#
# Usage: install-pkg-src [--dry-run] PACKAGE_NAME

if [ "$1" = "--dry-run" ]; then
  dry_run=1
  shift
fi

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 [--dry-run] PACKAGE_NAME"
  exit 1
fi

pkg="$1"
src_dir="/usr/src/${pkg}"
pkg_ver="$(dpkg -s "$pkg" | grep -Po '(?<=Version: ).*')"
src_ver="$(readlink ${src_dir}/.pkg_ver 2>/dev/null)"

if [ "$pkg_ver" = "$src_ver" ]; then
  echo "Already up-to-date."
  exit
fi

echo "Updating source directory to version ${pkg_ver}..."

if [ ! -n "$dry_run" ]; then
  mkdir -p "$src_dir"
  tmp_dir="$(/bin/mktemp -qd)"
  cd "$tmp_dir"
  /usr/bin/apt-get -qq source "$pkg"
  /usr/bin/find . -mindepth 1 -maxdepth 1 -type d -exec /usr/bin/rsync -r -a --delete --force {}/ "$src_dir" \;
  ln -sf "$pkg_ver" "${src_dir}/.pkg_ver"
  /bin/rm -rf "$tmp_dir"
fi
