'\" t
.\"     Title: commandname
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 07/25/2012
.\"    Manual: Wikimedia Manual
.\"    Source: Puppet 1.0
.\"  Language: English
.\"
.TH "COMMANDNAME" "8" "07/25/2012" "Puppet 1\&.0" "Wikimedia Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
commandname \- here you shoud enter a short summary
.SH "SYNOPSIS"
.sp
\fBcommandname\fR [\fIOPTIONS\fR] \fICOMMANDS\fR
.SH "DESCRIPTION"
.sp
That wheres you describe commandname(8), \fBbe bold\fR and take advantage of asciidoc inline formatting\&.
.SH "OPTIONS"
.PP
\fB\-f, \-\-file\fR=\fIATTRIBUTE\fR
.RS 4
Describe the \-\-file parameter usage there as well as the
\fIATTRIBUTE\fR
.RE
.SH "COMMANDS"
.sp
Describe commands, you can give some synospsis there such as:
.sp
.if n \{\
.RS 4
.\}
.nf
commandname OPTIONS command1 ON_FILE [SOME_OPTIONAL_ARG]
commandname OPTIONS help
.fi
.if n \{\
.RE
.\}
.PP
\fBOPTIONS\fR
.RS 4
Oh really amazing :\-]
.RE
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success
.RE
.PP
\fB1\fR
.RS 4
Failure
.RE
.SH "BUGS"
.sp
Any outstanding bug, possible enhancements, design issue, culprits\&.
.SH "AUTHOR"
.sp
Fill in some author name, merely so we know who to contact or blame\&.
.SH "RESOURCES"
.sp
Maybe consider adding a link to wikitech\&.
.SH "COPYING"
.sp
Copyright (C) XXXX\-YYYYY Some Author\&. Free use of this software is granted under the terms of the GNU Genereal Public License (GPL)\&.
