# Class: profile::toolforge::genpp::python_exec_buster
#
# This file was auto-generated by genpp.py using the following command:
# modules/profile/manifests/toolforge/genpp/python.py
#
# Please do not edit manually!

class profile::toolforge::genpp::python_exec_buster {
    require_package(
        'python-babel',         # 2.6.0
        'python3-babel',        # 2.6.0
        # python-beautifulsoup is not available
        # python3-beautifulsoup is not available
        'python-bottle',        # 0.12.15
        'python3-bottle',       # 0.12.15
        'python-bs4',           # 4.7.1
        'python3-bs4',          # 4.7.1
        'python-celery',        # 4.2.1
        'python3-celery',       # 4.2.1
        'python-cffi',          # 1.12.2
        'python3-cffi',         # 1.12.2
        'python-dev',           # 2.7.16
        'python3-dev',          # 3.7.3
        'python-egenix-mxdatetime', # 3.2.9
        # python3-egenix-mxdatetime is not available
        'python-egenix-mxtools', # 3.2.9
        # python3-egenix-mxtools is not available
        'python-enum34',        # 1.1.6
        # python3-enum34 is not available
        'python-flake8',        # 3.6.0
        'python3-flake8',       # 3.6.0
        'python-flask',         # 1.0.2
        'python3-flask',        # 1.0.2
        # python-flask-login is not available
        'python3-flask-login',  # 0.4.1
        'python-flickrapi',     # 2.1.2
        'python3-flickrapi',    # 2.1.2
        'python-flup',          # 1.0.2
        # python3-flup is not available
        'python-gdal',          # 2.4.0
        'python3-gdal',         # 2.4.0
        'python-gdbm',          # 2.7.16
        'python3-gdbm',         # 3.7.3
        'python-genshi',        # 0.7.1
        'python3-genshi',       # 0.7.1
        'python-genshi-doc',    # 0.7.1
        # python3-genshi-doc is not available
        'python-geoip',         # 1.3.2
        'python3-geoip',        # 1.3.2
        'python-gevent',        # 1.3.7
        'python3-gevent',       # 1.3.7
        'python-gi',            # 3.30.4
        'python3-gi',           # 3.30.4
        'python-greenlet',      # 0.4.15
        'python3-greenlet',     # 0.4.15
        'python-httplib2',      # 0.11.3
        'python3-httplib2',     # 0.11.3
        # python-imaging is not available
        # python3-imaging is not available
        'python-ipaddr',        # 2.2.0
        # python3-ipaddr is not available
        # python-irclib is not available
        # python3-irclib is not available
        'python-keyring',       # 17.1.1
        'python3-keyring',      # 17.1.1
        'python-launchpadlib',  # 1.10.6
        'python3-launchpadlib', # 1.10.6
        'python-lxml',          # 4.3.2
        'python3-lxml',         # 4.3.2
        'python-magic',         # 2:0.4.15
        'python3-magic',        # 2:0.4.15
        'python-matplotlib',    # 2.2.3
        'python3-matplotlib',   # 3.0.2
        # python-mysql.connector is not available
        # python3-mysql.connector is not available
        'python-mysqldb',       # 1.3.10
        'python3-mysqldb',      # 1.3.10
        'python-newt',          # 0.52.20
        'python3-newt',         # 0.52.20
        'python-nose',          # 1.3.7
        'python3-nose',         # 1.3.7
        'python-numpy',         # 1:1.16.2
        'python3-numpy',        # 1:1.16.2
        'python-opencv',        # 3.2.0
        'python3-opencv',       # 3.2.0
        'python-pandas',        # 0.23.3
        'python3-pandas',       # 0.23.3
        'python-pathlib2',      # 2.3.3
        # python3-pathlib2 is not available
        'python-pil',           # 5.4.1
        'python3-pil',          # 5.4.1
        # python-problem-report is not available
        # python3-problem-report is not available
        'python-psycopg2',      # 2.7.7
        'python3-psycopg2',     # 2.7.7
        'python-pycountry',     # 17.5.14
        'python3-pycountry',    # 17.5.14
        'python-pydot',         # 1.4.1
        'python3-pydot',        # 1.4.1
        'python-pyexiv2',       # 0.3.2
        # python3-pyexiv2 is not available
        'python-pygments',      # 2.3.1
        'python3-pygments',     # 2.3.1
        'python-pyicu',         # 2.2
        # python3-pyicu is not available
        'python-pyinotify',     # 0.9.6
        'python3-pyinotify',    # 0.9.6
        'python-requests-oauthlib', # 1.0.0
        'python3-requests-oauthlib', # 1.0.0
        # python-rsvg is not available
        # python3-rsvg is not available
        'python-scipy',         # 1.1.0
        'python3-scipy',        # 1.1.0
        'python-sqlalchemy',    # 1.2.18
        'python3-sqlalchemy',   # 1.2.18
        'python-svn',           # 1.9.9
        'python3-svn',          # 1.9.9
        'python-tk',            # 2.7.16
        'python3-tk',           # 3.7.3
        'python-twisted',       # 18.9.0
        'python3-twisted',      # 18.9.0
        'python-twitter',       # 3.3
        'python3-twitter',      # 3.3
        'python-unicodecsv',    # 0.14.1
        'python3-unicodecsv',   # 0.14.1
        'python-unittest2',     # 1.1.0
        'python3-unittest2',    # 1.1.0
        # python-venv is not available
        'python3-venv',         # 3.7.3
        'python-virtualenv',    # 15.1.0
        'python3-virtualenv',   # 15.1.0
        'python-wadllib',       # 1.3.3
        'python3-wadllib',      # 1.3.3
        # python-webpy is not available
        'python3-webpy',        # 1:0.39
        'python-werkzeug',      # 0.14.1
        'python3-werkzeug',     # 0.14.1
        'python-zbar',          # 0.22
        # python3-zbar is not available
        'python-zmq',           # 17.1.2
        'python3-zmq',          # 17.1.2
    )
}
