# Class: profile::toolforge::genpp::python_dev_buster
#
# This file was auto-generated by genpp.py using the following command:
# modules/profile/manifests/toolforge/genpp/python.py
#
# Please do not edit manually!

class profile::toolforge::genpp::python_dev_buster {
    require_package(
        'python-coverage',      # 4.5.2
        'python3-coverage',     # 4.5.2
        'python-stdeb',         # 0.8.5
        'python3-stdeb',        # 0.8.5
    )
}
