# Class: profile::toolforge::genpp::python_dev_stretch
#
# This file was auto-generated by genpp.py using the following command:
# modules/profile/manifests/toolforge/genpp/python.py
#
# Please do not edit manually!

class profile::toolforge::genpp::python_dev_stretch {
    ensure_packages([
        'python-coverage',      # 4.2
        'python3-coverage',     # 4.2
        'python-stdeb',         # 0.8.5
        'python3-stdeb',        # 0.8.5
    ])
}
