# == Class profile::analytics::cluster::rsyncd
#
# Set up an rsync module at certain paths to
# allow read only rsync access to analytics generated data.
#
class profile::analytics::cluster::rsyncd(
    $hosts_allow = hiera('statistics_servers'),
) {
    # This will allow $hosts_allow to host public data files
    # generated by the analytics cluster.
    # Note that this requires that cdh::hadoop::mount
    # be present and mounted at /mnt/hdfs
    rsync::server::module { 'hdfs-archive':
        path        => "${::cdh::hadoop::mount::mount_point}/wmf/data/archive",
        read_only   => 'yes',
        list        => 'yes',
        # Set uid/gid to false to override rsync::server::module's default of 0/0
        uid         => false,
        gid         => false,
        hosts_allow => $hosts_allow,
        require     => Class['cdh::hadoop::mount'],
        auto_ferm   => true,
    }
}
