class admin::groups::deployment {

    @admin::group { 'deployment':
        gid        => 514,
        members    => [
                        'aaron',
                        'abaso',
                        'andrew',
                        'anomie',
                        'aude',
                        'awight',
                        'awjrichards',
                        'bd808',
                        'brion',
                        'bsitu',
                        'cmcmahon',
                        'csteipp',
                        'demon',
                        'ebernhardson',
                        'gdubuc',
                        'gjg',
                        'gwicke',
                        'halfak',
                        'hashar',
                        'kaldari',
                        'kartik',
                        'khorn',
                        'krinkle',
                        'manybubbles',
                        'maxsem',
                        'mflaschen',
                        'mholmquist',
                        'mhoover',
                        'milimetric',
                        'mlitn',
                        'mwalker',
                        'neilk',
                        'nikerabbit',
                        'nimishg',
                        'olivneh',
                        'pdhanda',
                        'pgehres',
                        'raindrift',
                        'reedy',
                        'rmoen',
                        'robla',
                        'spage',
                        'ssastry',
                        'sumanah',
                        'tfinc',
                        'yurik',
                        'zak',
                      ],
    }
}
