---
profile::admin::groups:
  - wmcs-roots

contactgroups: wmcs-team-email

cluster: wmcs

# See T224828
raid::md::timer_ensure: absent
profile::contacts::role_contacts: ["WMCS"]

profile::openstack::base::pdns::default_soa_content: ns0.openstack.eqiad1.wikimediacloud.org
profile::openstack::base::pdns::recursor::bgp_vip: [172.20.255.1, 2a02:ec80:a000:2ff::1]
profile::openstack::eqiad1::pdns::recursor::use_new_pdns_cfg: true

profile::dbbackups::mydumper::enabled: true
profile::dbbackups::mydumper::calendar: '*-*-* 00:00:00'
profile::dbbackups::mydumper::config: 'profile/openstack/base/dbbackups/pdns.cnf.erb'

profile::bird::advertise_vips:
  # NOTE: this is a shared BGP-based anycast VIP. There also a non-shared per-host adddress
  ns-recursor.openstack.eqiad1.wikimediacloud.org:
    ensure: present
    service_type: "pdns recursor"
    address: 172.20.255.1
    check_cmd: "/usr/lib/nagios/plugins/check_dns_query -H 172.20.255.1 -d www.wikimedia.org -t 1"
    address_ipv6: 2a02:ec80:a000:2ff::1
    check_cmd_ipv6: "/usr/lib/nagios/plugins/check_dns_query -H 2a02:ec80:a000:2ff::1 -d www.wikimedia.org -t 1"
