#!/bin/bash
script=$(basename "$0")
user_agent="wmf-icinga/${script} (root@wikimedia.org)"
/usr/lib/nagios/plugins/negate -s -c WARNING /usr/lib/nagios/plugins/check_http -H www.wikidata.org -S -u "/w/api.php?action=query&meta=siteinfo&format=json&siprop=statistics" --linespan --ereg '"median":[^}]*"lag":([1-5]?[0-9]?[0-9]),' -A "${user_agent}"
