#!/bin/bash
/usr/lib/nagios/plugins/check_http -H www.wikidata.org -I 91.198.174.192 -S -u "/w/api.php?action=query&meta=siteinfo&format=json&siprop=statistics" --linespan --ereg '"median":[^}]*"lag":[1-5]?[0-9],'
