#!/bin/bash
# change the password of a DRAC mgmt interface
# (c) Papaul Tshibamba, Wikimedia Foundation Inc. 2016
# sshpass needs to be installed on the host from where this script will run

echo -n "Enter iDRAC root password (password will not be displayed):"
read -s DRACPASS
echo
echo -n "Enter IDRAC root new password (password will not be displayed):"
read -s DRAC_NEW_PASS
echo

# Host ip list file location
host_list=ip_list.txt
# Logfile to keep the logs of the execution
execlog=pwchange-exec.log
# Logfile for IP addresses of hosts where the password change was succesful
successlog=pwchange-success.log
# Logfile for IP addresses of hosts where the password change failed
faillog=pwchange-failed.log

#get a list of IPs for the servers
function getServers () {
    cat $host_list
}

# check if the file with the hosts IPs exists
if [ ! -r $host_list ]; then
    echo "IP address file $host_list not found or cannot be read"
    exit
# Make a log file. The logfile gets overwritten at each execution
else
    echo "Starting Bash configuration of Dell Drac for file $host_list" >$execlog
    echo "" > $successlog
    echo "" > $faillog
fi

for host_ip in $(getServers); do
    echo "========================================" >> $execlog
    echo "Changing DRAC password for  $host_ip " >> $execlog

    # Dell Racadm command
    sshpass -p "$DRACPASS" ssh -o StrictHostKeyChecking=no root@$host_ip racadm config -g cfgUserAdmin -o cfgUserAdminPassword -i 2 "$DRAC_NEW_PASS" >>$execlog 2>&1

    if [ $? -ne 0 ]; then
        echo "Failed. See logfile for details"
        echo $host_ip >> $faillog
    else
        echo "DRAC configured successfully on $host_ip"
        echo $host_ip >> $successlog
    fi
done <$host_list

echo " complete"

