#!/bin/bash
# Update facts from all puppet masters to the puppet compiler machine
#
# This script must be run from the root of the operations/puppet repository
# locally from a computer that has root access to all puppet masters and the
# puppet compiler machine.

set -e
set -u

COMPILER=${PUPPET_COMPILER:-compiler02.puppet3-diffs.eqiad.wmflabs}
RUBY_SCRIPT=$(cat <<'RUBY_SCRIPT'
require 'safe_yaml'
SafeYAML::OPTIONS[:default_mode] = :safe
a = YAML.load(STDIN.read)['puppetmaster::servers']
puts a.map{|k, v| a[k].map {|v| v['worker']}}.flatten().join(' ')
RUBY_SCRIPT
)

MASTERS=${PUPPET_MASTERS:-$(ruby -e "${RUBY_SCRIPT}" < hieradata/common/puppetmaster.yaml)}

ssh "$COMPILER" 'sudo rm -rf /tmp/facts; sudo mkdir -p /tmp/facts'
# Gather all the facts from one of the masters.
master=$MASTERS[0]
echo -e "\n### Syncing facts from $master"
ssh "$master" 'sudo /usr/local/bin/puppet-facts-export 1>/dev/null'
# tunnel via your localhost without ever the file touching the disk
ssh "$master" cat /tmp/puppet-facts-export.tar.xz | ssh "$COMPILER" 'cat > puppet-facts-export.tar.xz'
ssh "$master" 'sudo rm /tmp/puppet-facts-export.tar.xz'
ssh "$COMPILER" 'tar Jxf puppet-facts-export.tar.xz --directory /tmp/facts && sudo chown -R jenkins-deploy:wikidev /tmp/facts/yaml'
# Finally, copy all the facts to destination and cleanup
ssh "$COMPILER" 'sudo rsync --delete -au /tmp/facts/yaml/ /var/lib/catalog-differ/puppet/yaml/ && sudo rm -rf /tmp/facts'
