#!/bin/bash

# NOTE: This file is managed by Puppet.

#
# Runs hdfs balancer as long as another is not already running.
#

(
    # make sure balancer is not already running.
    lockfile-check /tmp/hdfs-balancer && \
    echo "$(date '+%y/%m/%d %H:%M:%S') WARN Not starting hdfs balancer, it is already running (or the lockfile exists)."
) || \
(
    # Create a lockfile
    lockfile-create /tmp/hdfs-balancer && \
    # Set the balancer bandwidth
    hdfs dfsadmin -setBalancerBandwidth $((40*1048576)) && \
    # Run the hdfs balancer with a 5% threshold.
    /usr/bin/hdfs balancer -threshold 5

    # Remove the lockfile
    lockfile-remove /tmp/hdfs-balancer
)
