-- SPDX-License-Identifier: Apache-2.0
-- This stanza has 1 "default" section that lists rules applied anyway to all
-- wikis and the possibility for N stanzas that are meant to be wiki specific
-- rules. Keep the N small, we don't want this to blow up
-- For a specific wiki, rules are merged on 1-st level key basis, which
-- is as dumb as it gets. Since this is a lua table, order isn't guaranteed. So
-- if for any reason you end up wanting ordering, reconsider the approach
-- altogether
--
-- Each rule is a table with 3 elements:
-- 1. The URL pattern to match
-- 2. The destination host and port
-- 3. The load_fraction probability of routing to the gateway
-- The load_fraction probability is a float between 0 and 1.
-- If the load_fraction probability is 1, then all requests will be routed to
-- the destination host:port.
--
-- The "ignore" section can be used to make a dict of host:[URL..]
-- pairs, which are used to ignore all rules defined here. This can be
-- useful for exempting specific hosts/URLs from the larger patterns
-- set in default for whatever reason.
-- NOTE: ignore rules take precendence over default and per-wiki rules.

return {
    ["default"] = {
        ["/api/rest_v1/metrics/(.+)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/(.+)/pdf/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/feed/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/page/random/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        --  T374683
        ["/api/rest_v1/page/title/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/page/html/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        -- T361576
        ["/api/rest_v1/data/citation/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        -- T372746: mobileapps restbaseless migration rollout
        ["/api/rest_v1/page/mobile%-html/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/page/summary/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/page/media%-list/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/page/mobile%-html%-offline%-resources/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/page/talk/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/page/definition/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/data/css/mobile/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/data/javascript/mobile/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/data/i18n/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/transform/wikitext/to/mobile%-html/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/transform/wikitext/to/html(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/transform/html/to/wikitext(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/api/rest_v1/data/lists/(.*)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
    },
    ["test2.wikipedia.org"] = {
        ["/w/rest.php"] = {"rest-gateway.discovery.wmnet", 4113, 1},
        ["/w/rest.php/(.+)"] = {"rest-gateway.discovery.wmnet", 4113, 1},
    },
    -- Exceptions to both per-wiki and default rules can be made by using the ignore dictionary
    -- ["ignore"] = {
    --     ["en.wikipedia.org"] = {
    --       "/api/rest_v1/page/mobile%-html/(.*)",
    --       "/api/rest_v1/page/summary/(.*)",
    --       "/api/rest_v1/page/media%-list/(.*)",
    --     },
    -- },
    -- Rules per wiki can be added below in a format like the following
    -- ["test.wikipedia.org"] = {
    --      ["/path/to/api1"] = "rest-gateway.discovery.wmnet", 4113, 1},
    --      ["/path/to/api2"] = "rest-gateway.discovery.wmnet", 4113, 0.5},
    -- },
}
