-- SPDX-License-Identifier: Apache-2.0
-- This stanza has 1 "default" section that lists rules applied anyway to all
-- wikis and the possibility for N stanzas that are meant to be wiki specific
-- rules. Keep the N small, we don't want this to blow up
-- For a specific wiki, rules are merged on 1-st level key basis, which
-- is as dumb as it gets. Since this is a lua table, order isn't guaranteed. So
-- if for any reason you end up wanting ordering, reconsider the approach
-- altogether
return {
    ["default"] = {
        ["/api/rest_v1/metrics/(.+)"] = {"rest-gateway.discovery.wmnet", 4113},
        ["/api/rest_v1/(.+)/pdf/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
        ["/api/rest_v1/feed/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
        ["/api/rest_v1/page/random/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
        --  T374683
        ["/api/rest_v1/page/title/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
        ["/api/rest_v1/page/html/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
    },
    -- T361576, T385719
    ["test.wikipedia.org"] = {
        ["/api/rest_v1/data/citation/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
        ["/api/rest_v1/page/mobile-html/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
        ["/api/rest_v1/page/summary/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
        ["/api/rest_v1/page/media-list/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
    },
    -- T372746
    ["he.wikipedia.org"] = {
        ["/api/rest_v1/data/citation/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
        ["/api/rest_v1/page/mobile-html/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
        ["/api/rest_v1/page/summary/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
        ["/api/rest_v1/page/media-list/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
    },
    -- T361576: mimicking group0, group1 rollout
    ["test.wikidata.org"] = {
        ["/api/rest_v1/data/citation/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
    },
    ["www.mediawiki.org"] = {
        ["/api/rest_v1/data/citation/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
    },
    ["office.wikimedia.org"] = {
        ["/api/rest_v1/data/citation/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
    },
    ["commons.wikimedia.org"] = {
        ["/api/rest_v1/data/citation/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
    },
    ["meta.wikimedia.org"] = {
        ["/api/rest_v1/data/citation/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
    },
    ["ca.wikipedia.org"] = {
        ["/api/rest_v1/data/citation/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
    },
    ["it.wikipedia.org"] = {
        ["/api/rest_v1/data/citation/(.*)"] = {"rest-gateway.discovery.wmnet", 4113},
    },
-- Rules per wiki can be added below in a format like the following
-- ["test.wikipedia.org"] = {
--      ["/path/to/api1"] = "rest-gateway.discovery.wmnet", 4113},
--      ["/path/to/api2"] = "rest-gateway.discovery.wmnet", 4113},
-- },
}
