-- SPDX-License-Identifier: Apache-2.0
--
-- This file is managed by Puppet.
return {
    -- Whether next-routing logic is enabled. If false, the script immediately
    -- returns TS_LUA_REMAP_NO_REMAP, without inspecting the request at all.
    enabled = true,
    -- Fraction of enrolled requests to route to the next services.
    load_fraction = 1.0,
    -- The specific cookie pattern to match in order to enroll a given request.
    cookie_pattern = "PHP_ENGINE=8.3",
}
