# SPDX-License-Identifier: Apache-2.0
# https://github.com/cloudflare/cfssl/blob/master/config/config.go#L639
type Cfssl::Usage = Enum[
    'any',
    'signing',
    'digital signature',
    'content commitment',
    'key encipherment',
    'key agreement',
    'data encipherment',
    'cert sign',
    'crl sign',
    'crl sign',
    'encipher only',
    'decipher only',
    'server auth',
    'client auth',
    'code signing',
    'email protection',
    's/mime',
    'ipsec end system',
    'ipsec tunnel',
    'ipsec user',
    'timestamping',
    'ocsp signing',
    'microsoft sgc',
    'netscape sgc',
]
