# SPDX-License-Identifier: Apache-2.0

[project]
name = "pontoon"
version = "0.4.1"
dependencies = ["ruamel.yaml", "click"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["pontoon"]

[tool.pytest.ini_options]
markers = [
    "integration: Marks tests as integration tests"
]

[project.scripts]
pontoon-enc = "pontoon.enc:main"
pontoonctl = "pontoon.ctl:main"

[project.optional-dependencies]
ctl = ["python-novaclient", "keystoneauth1", "python-keystoneclient"]
dev = ["bpython", "pytest", "pytest-cov"]
