#!/bin/sh
# Script to do automated discovery of torrus data sources, based on
# a set of DDX files

TREES="Network Storage"

for ddx in /etc/torrus/discovery/*.ddx
do
	torrus devdiscover --in=$ddx --forcebundle
done

for tree in $TREES
do
	torrus compile --tree=$tree
done
