#!/bin/sh

if [ $( php /home/w/common/php-1.5/maintenance/showJobs.php enwiki ) -gt 50000 ]; then
	echo "JOBQUEUE CRITICAL - enwiki has more than 50 000 entries in its job queue"
	exit 2
fi

for a in commonswiki enwiktionary dewikinews itwiki ptwiki dewiki plwiki frwiki eswiki jawiki svwiki ; do
	echo $(php /home/w/common/php-1.5/maintenance/showJobs.php $a ) $a;
done | sort -n | tail -3 | head -1 | while read count wiki ; do
	if [ $count -gt 10000 ]; then
		echo "JOBQUEUE CRITICAL - $wiki has $count entries in its job queue - 3rd biggest job queue"
		exit 2
	fi
	echo "JOBQUEUE OK - $wiki has the 3rd biggest job queue, $count entries"
	exit 0
done
