#!/bin/bash

instance_name=$1
conf_file=/etc/udp2log/$instance_name

if [ ! -f $conf_file ]; then
	echo "UNKNOWN: $conf_file cannot be found"
	exit 3
fi

minus_three_hours=/tmp/minus_three
minus_six_hours=/tmp/minus_six
touch -d "3 hours ago" $minus_three_hours
touch -d "6 hours ago" $minus_six_hours

warn_count=0
crit_count=0
warn_list=""
crit_list=""

for log_file in `egrep "^(pipe|file)" $conf_file | egrep -o "/[^ \.]*\.log"`; do
	if [ $log_file -ot $minus_six_hours ]; then
		((crit_count++))
		crit_list=`echo "$log_file, $crit_list"`
	elif [ $log_file -ot $minus_three_hours ]; then
		((warn_count++))
		warn_list=`echo "$log_file, $warn_list"`
	fi
done

rm $minus_three_hours&&rm $minus_six_hours

if [ $crit_count -gt 0 ];then
	echo "CRITICAL: log files $crit_list have not been written to in 6 hours"
	exit 2
elif [ $warn_count -gt 0 ];then
	echo "WARNING: log files $warn_list have not been written to in 3 hours"
	exit 1
else 
	echo "OK: all log files active"
	exit 0
fi
