prometheus::instances_defaults:
  retention_time: 4032h
  retention_size: ~
  thanos_upload: true
  k8s_cluster_name: ~
  hosts: ~
  provision_lv_size: "50g"
  # Changes to this key, or to the same key in the prometheus::instances variable,
  # must be deployed through the sre.o11y.thanos-compact-relabel cookbook.
  designated_compactor: "titan2001.codfw.wmnet"
  cardinality_exporter:
    polling_interval: 0.1 # hours

prometheus::instances:
  ops:
    port: 9900
    retention_size: 3300GB
    provision_lv_size: "3.6t"
    hosts:
      - prometheus1005.eqiad.wmnet
      - prometheus1006.eqiad.wmnet
      - prometheus2005.codfw.wmnet
      - prometheus2006.codfw.wmnet
      - prometheus3004.esams.wmnet
      - prometheus4003.ulsfo.wmnet
      - prometheus5003.eqsin.wmnet
      - prometheus6002.drmrs.wmnet
      - prometheus7002.magru.wmnet
    designated_compactor: "titan1001.eqiad.wmnet"
    cardinality_exporter:
      port: 9400

  services:
    port: 9903
    provision_lv_size: "250g"
    hosts:
      - prometheus1005.eqiad.wmnet
      - prometheus1006.eqiad.wmnet
      - prometheus2005.codfw.wmnet
      - prometheus2006.codfw.wmnet
    designated_compactor: "titan1002.eqiad.wmnet"
    cardinality_exporter:
      port: 9403

  cloud:
    port: 9904
    hosts:
      - prometheus1005.eqiad.wmnet
      - prometheus1006.eqiad.wmnet
      - prometheus2005.codfw.wmnet
      - prometheus2006.codfw.wmnet
    designated_compactor: "titan1002.eqiad.wmnet"
    cardinality_exporter:
      port: 9404

  analytics:
    port: 9905
    provision_lv_size: "110g"
    hosts:
      - prometheus1005.eqiad.wmnet
      - prometheus1006.eqiad.wmnet
      - prometheus2005.codfw.wmnet
      - prometheus2006.codfw.wmnet
    designated_compactor: "titan1002.eqiad.wmnet"
    cardinality_exporter:
      port: 9405

  k8s:
    port: 9906
    retention_size: 1160GB
    provision_lv_size: "1.4t"
    k8s_cluster_name: "%{::site}"
    hosts:
      - prometheus1007.eqiad.wmnet
      - prometheus1008.eqiad.wmnet
      - prometheus2007.codfw.wmnet
      - prometheus2008.codfw.wmnet
    designated_compactor: "titan2001.codfw.wmnet"
    cardinality_exporter:
      port: 9406

  k8s-staging:
    port: 9907
    k8s_cluster_name: "staging-%{::site}"
    provision_lv_size: "100g"
    hosts:
      - prometheus1007.eqiad.wmnet
      - prometheus1008.eqiad.wmnet
      - prometheus2007.codfw.wmnet
      - prometheus2008.codfw.wmnet
    designated_compactor: "titan2002.codfw.wmnet"
    cardinality_exporter:
      port: 9407

  k8s-mlserve:
    port: 9909
    k8s_cluster_name: "ml-serve-%{::site}"
    provision_lv_size: "350g"
    hosts:
      - prometheus1007.eqiad.wmnet
      - prometheus1008.eqiad.wmnet
      - prometheus2007.codfw.wmnet
      - prometheus2008.codfw.wmnet
    designated_compactor: "titan2002.codfw.wmnet"
    cardinality_exporter:
      port: 9409

  k8s-dse:
    port: 9910
    k8s_cluster_name: "dse-k8s-%{::site}"
    provision_lv_size: "80g"
    hosts:
      - prometheus1007.eqiad.wmnet
      - prometheus1008.eqiad.wmnet
      - prometheus2007.codfw.wmnet
      - prometheus2008.codfw.wmnet
    designated_compactor: "titan2002.codfw.wmnet"
    cardinality_exporter:
      port: 9410

  k8s-aux:
    port: 9911
    k8s_cluster_name: "aux-k8s-%{::site}"
    hosts:
      - prometheus1007.eqiad.wmnet
      - prometheus1008.eqiad.wmnet
      - prometheus2007.codfw.wmnet
      - prometheus2008.codfw.wmnet
    designated_compactor: "titan2002.codfw.wmnet"
    cardinality_exporter:
      port: 9411

  k8s-mlstaging:
    port: 9912
    k8s_cluster_name: "ml-staging-%{::site}"
    hosts:
      - prometheus2007.codfw.wmnet
      - prometheus2008.codfw.wmnet
    designated_compactor: "titan2002.codfw.wmnet"
    cardinality_exporter:
      port: 9412

  ext:
    port: 9908
    provision_lv_size: "10g"
    retention_time: 730h
    hosts:
      - prometheus1005.eqiad.wmnet
      - prometheus1006.eqiad.wmnet
      - prometheus2005.codfw.wmnet
      - prometheus2006.codfw.wmnet
    designated_compactor: "titan1002.eqiad.wmnet"
    cardinality_exporter:
      port: 9408

# Pick this instance as the "homepage" for e.g. prometheus-eqiad.w.o
prometheus::default_web_instance: "ops"

# Same as prometheus::instances, but for cleaning up instances.
# Having the same instance + host combination here and prometheus::instances
# will result in catalog compilation failure.
prometheus::instances_cleanup:
  k8s-mlstaging:
    hosts:
      - prometheus2005.codfw.wmnet
      - prometheus2006.codfw.wmnet
  k8s-aux:
    hosts:
      - prometheus1005.eqiad.wmnet
      - prometheus1006.eqiad.wmnet
      - prometheus2005.codfw.wmnet
      - prometheus2006.codfw.wmnet
  k8s-mlserve:
    hosts:
      - prometheus1005.eqiad.wmnet
      - prometheus1006.eqiad.wmnet
      - prometheus2005.codfw.wmnet
      - prometheus2006.codfw.wmnet
  k8s-staging:
    hosts:
      - prometheus1005.eqiad.wmnet
      - prometheus1006.eqiad.wmnet
      - prometheus2005.codfw.wmnet
      - prometheus2006.codfw.wmnet
  k8s:
    hosts:
      - prometheus1005.eqiad.wmnet
      - prometheus1006.eqiad.wmnet
      - prometheus2005.codfw.wmnet
      - prometheus2006.codfw.wmnet
  k8s-dse:
    hosts:
      - prometheus1005.eqiad.wmnet
      - prometheus1006.eqiad.wmnet
      - prometheus2005.codfw.wmnet
      - prometheus2006.codfw.wmnet
