# == Define: rsyslog::logged_daemon
#
# This resource provisions a common rsyslog pattern: capturing log
# messages from a particular application, diverting them to a separate
# file, and configuring log rotation for that file.
#
# === Parameters
#
# [*daemon*]
#   Capture log messages generated by this program.
#   Defaults to the resource title.
#
# [*logfile*]
#   Path to target log file. The default behavior is to place a .log
#   file with the same name as the resource in /var/log.
#
# === Examples
#
#  rsyslog::logged_daemon { 'ganglia': }
#
define rsyslog::logged_daemon(
    ensure  = present,
    daemon  = $title,
    logfile = "/var/log/${title}.log",
) {
    include ::rsyslog

    rsyslog::rotated_log { $logfile:
        ensure => $ensure,
    }

    rsyslog::conf { $daemon:
        ensure   => $ensure,
        content  => template('rsyslog/daemon.conf.erb'),
        priority => 40,  # before the catchall 50-default.conf
    }
}
