# SPDX-License-Identifier: Apache-2.0
# Please note: if you add multiple blocks of the same action (include/exclude)
# docker-report will perform a logical AND on all of them.

[broken_report_T432824]
name = contains:repos/data-engineering/eventstreams
action = exclude
