# SPDX-License-Identifier: Apache-2.0
# Please note: if you add multiple blocks of the same action (include/exclude)
# docker-report will perform a logical AND on all of them.

[skip_restricted]
name = regex:^(/restricted)
action = exclude
