# SPDX-License-Identifier: Apache-2.0
# Please note: if you add multiple blocks of the same action (include/exclude)
# docker-report will perform a logical AND on all of them.

[broken_debian_snapshot_T440697]
name = regex:(wikimedia/mediawiki-services-citoid|wikimedia/mediawiki-services-cxserver).*
action = exclude
