class base::puppet::params(
    # Use srv domain to discover the puppetmaster
    $use_srv_record = false
    ) {
    ## run puppet by cron and
    ## rotate puppet logs generated by cron
    ## This is in mins. Do not set this to 0 or > 60
    $interval = 30
    $crontime = fqdn_rand(60, 'puppet-params-crontime')
    # Calculate freshness interval in seconds (hence *60)
    $freshnessinterval = $interval * 60 * 6
}
