# the following passwords are defined in private repo:
#profile::maps::osm_master::kartotherian_pass: some_password
#profile::maps::osm_master::replication_pass: some_password
#profile::maps::osm_master::swift_key_id: "tegola:prod"
#profile::maps::osm_master::swift_password: some_password
#profile::maps::osm_master::tegola_pass: some_password

profile::admin::groups:
  - maps-roots

cluster: 'maps'

profile::maps::apps::use_proxy: true

profile::base::production::role_description: 'Maps staging database (postgresql)'

profile::maps::osm_master::log_min_duration_statement: 10000 # 10 seconds
profile::maps::osm_master::use_replication_slots: true
profile::maps::osm_master::replication_slots: []
profile::maps::osm_master::enable_tile_invalidation: false
profile::maps::osm_master::disable_replication_timer: false
profile::maps::osm_master::disable_waterlines_import_timer: false

profile::maps::osm_master::planet_sync_hours: '0/12'

# Performance tuning for Postgres 15 and Tegola - T381565
profile::maps::postgresql_common::shared_buffers: '12800MB'
profile::maps::postgresql_common::max_connections: 200
profile::maps::postgresql_common::max_worker_processes: 16
profile::maps::postgresql_common::effective_cache_size: '64GB'

profile::maps::osm_master::tegola_swift_container: "TODO"
profile::maps::osm_master::eventgate_endpoint: "TODO"
profile::maps::osm_master::tiles_change_eventgate_stream: "TODO"

profile::firewall::provider: nftables

profile::puppet::agent::force_puppet7: true

profile::maps::hosts:
  - 'maps-test2001.codfw.wmnet'

profile::maps::osm_master::replicas: # This also includes the master
  maps-test2001:
    ip_address: 10.192.12.22

do_paging: false
