#!/bin/bash
# This script belongs in /usr/local/bin/.
BINDIR=/usr/local/bin
MWMULTIDIR=/home/wikipedia/common/multiversion
SVNDIR=/var/tmp/l10nupdatesvn/trunk
SVNURL=http://svn.wikimedia.org/svnroot/mediawiki/trunk
SVNPATHS="phase3 extensions"

umask 0002
echo "Starting l10nupdate at `date`."

# SVN up i18n messages to /trunk HEAD, or create the checkout if it doesn't exist yet
echo "Updating SVN checkout ..."
for path in $SVNPATHS
do
	if [ -d $SVNDIR$path ]
	then
		# Checkout exists, update it
		if svn up --ignore-externals $SVNDIR/$path
		then
			echo "Updated $path"
		else
			$BINDIR/dologmsg "!log LocalisationUpdate failed: SVN update of $path failed"
			echo "Updating $path FAILED."
			exit 1
		fi
	else
		# Create the checkout's parent directory
		if mkdir -p `dirname $SVNDIR/$path` &&
			svn checkout --ignore-externals $SVNURL/$path $SVNDIR/$path
		then
			echo "Checked out $path"
		else
			$BINDIR/dologmsg "!log LocalisationUpdate failed: SVN checkout of $path failed"
			echo "Checking out $path FAILED."
			exit 1
		fi
	fi
done
echo "SVN checkout updated."

# Get all MW message cache versions (and a wiki DB name for each)
mwVerDbSets=$($BINDIR/mwversionsinuse --extended --withdb)
if [ -z "$mwVerDbSets" ]; then
	$BINDIR/dologmsg "!log LocalisationUpdate failed: mwversionsinuse returned empty list"
	echo "Obtaining MediaWiki version list FAILED"
	exit 1
fi

# Update l10n cache and clear the message cache for these versions
for i in ${mwVerDbSets[@]}
do
	mwVerNum=${i%=*}
	mwDbName=${i#*=}
	echo "Running updates for $mwVerNum (on $mwDbName)"
	# l10nupdate-2 is a wrapper for mwscript extensions/LocalisationUpdate/update.php
	if l10nupdate-2 \
		  --wiki="$mwDbName" \
		  --outdir=/home/wikipedia/common/php-"$mwVerNum"/cache/l10n \
		  --svnurl=$SVNDIR \
		  --all \
		  --quiet
	then
		echo "Completed. Syncing to Apaches"
		$BINDIR/sync-l10nupdate-1 "$mwVerNum"
		echo "Clearing message blobs"
		# l10nupdate-3 is a wrapper for mwscript maintenance/wmf/clearMessageBlobs.php
		l10nupdate-3 --wiki="$mwDbName"
		$BINDIR/dologmsg "!log LocalisationUpdate completed ($mwVerNum) at `date`"
		echo "All done"
	else
		$BINDIR/dologmsg "!log LocalisationUpdate failed ($mwVerNum) at `date`"
		echo "FAILED"
	fi
done
