#!/bin/bash
# This script belongs in /usr/local/bin/.
MWVER="$1"

if [ -z "$MWVER" ]; then
	echo "FAILED: MediaWiki version not provided"
	exit 1
fi

echo "Synchronizing /home/wikipedia/common/php-$MWVER/cache/l10n to /usr/local/apache/common-local/php-$MWVER/cache/l10n..."
echo "mediawiki-installation:"

dsh -o -oPasswordAuthentication=no -F 30 -cM -g mediawiki-installation \
  "sudo -u mwdeploy rsync -a 10.0.5.8::common/php-$MWVER/cache/l10n/ /usr/local/apache/common-local/php-$MWVER/cache/l10n"
