type Trafficserver::Paths = Struct[{
    'base_path'     => Optional[Stdlib::Absolutepath],
    'prefix'        => Stdlib::Absolutepath,
    'exec_prefix'   => Stdlib::Absolutepath,
    'bindir'        => Stdlib::Absolutepath,
    'sbindir'       => Stdlib::Absolutepath,
    'sysconfdir'    => Stdlib::Absolutepath,
    'datadir'       => Stdlib::Absolutepath,
    'includedir'    => Stdlib::Absolutepath,
    'libdir'        => Stdlib::Absolutepath,
    'libexecdir'    => Stdlib::Absolutepath,
    'localstatedir' => Stdlib::Absolutepath,
    'runtimedir'    => Stdlib::Absolutepath,
    'logdir'        => Stdlib::Absolutepath,
    'cachedir'      => Stdlib::Absolutepath,
    'records'       => Stdlib::Absolutepath,
    'ssl_multicert' => Stdlib::Absolutepath,
}]
