#!/bin/bash
#
# Disable puppet and ensure it's not running before returning
#
if [ -z "$1" ]; then
    echo "A message is required."
    exit 1
fi
MESSAGE="${1}"
if [ -n "${SUDO_USER}" ]
then
  MESSAGE="${MESSAGE} - ${SUDO_USER}"
fi
ATTEMPTS=${2:-30}

# shellcheck disable=SC1091
. /usr/local/share/bash/puppet-common.sh

# This will NOT overwrite an existing message, if already disabled
puppet agent --disable "$MESSAGE"

# Do not return until puppet has finished running
wait_for_puppet "$ATTEMPTS"
exit $?
