#!/bin/sh
# Script displaying a message if Puppet agent is disabled.

set -eu

PATH=/bin:/usr/bin

lockfile="/var/lib/puppet/state/agent_disabled.lock"

if test -f $lockfile; then
    reason="$(jq -r '.disabled_message' $lockfile 2>/dev/null)"
    echo "Puppet is disabled. $reason"
    exit 1
fi

exit 0
