#!/bin/bash
OPTIND=1
verbose_opts="--verbose"

while getopts "q" opt; do
    case "$opt" in
        q)  verbose_opts=""
            ;;
    esac
done

shift $((OPTIND-1))

if ! wait_for_puppet 3; then
    echo "Waited 30 seconds and a preceding puppet run is still ongoing, aborting"
    exit 1
fi
puppet agent --onetime --no-daemonize $verbose_opts --no-splay --show_diff \
       --ignorecache --no-usecacheonfailure
