#!/bin/sh
# Used to update the instance puppet master repository from a repository in a
# non-canonical location, e.g. to push branches for testing

# this dance is necessary because git doesn't like pushing to non-bare
# repositories (the index gets confused)
set -e
set -u

source_dir=$PWD
cd /var/lib/git/operations/puppet
sudo git fetch $source_dir
sudo git checkout FETCH_HEAD
