#!/bin/bash
set -o errexit
set -o nounset
VERSION="$1"

# If the default vd lvm group that labs_Lvm sets up still exists
# remove it, since we will set up our own
if vgdisplay vd; then
    vgremove --force vd
fi

# Create a docker vg, then create individual volumes in there
vgcreate docker /dev/vda4

lvcreate --wipesignatures y -n data docker -l 95%VG
lvcreate --wipesignatures y -n metadata docker -l 5%VG

# Run an apt-get update to make sure we have the docker repo
apt-get update

# Install a particular version of docker engine, but do not start it!
RUNLEVEL=1 apt-get install --yes docker-engine=${VERSION}

# Clean out the current /var/lib/docker for good measure, to prevent
# any remnants of the loopback config from staying on
rm -rf /var/lib/docker