# Class: toollabs::genpp::python_dev_precise
#
# This file was auto-generated by genpp.py using the following command:
# python.py
#
# Please do not edit manually!

class toollabs::genpp::python_dev_precise {
    require_package(
        'python-coverage',      # 3.4
        # python3-coverage is not available
        'python-dev',           # 2.7.3
        'python3-dev',          # 3.2.3
        'python-stdeb',         # 0.6.0
        # python3-stdeb is not available
    )
}
