# Class: toollabs::genpp::python_dev_precise
#
# This file was auto-generated by genpp.py using the following command:
# ./python.py
#
# Please do not edit manually!

class toollabs::genpp::python_dev_precise {
    package { [
        'python-coverage',
        'python-dev',
        'python-stdeb',
        'python3-dev',
    ]:
        ensure => latest,
    }
}