# enchant and myspell dictionaries
# for machine learning and natural language processing

class statistics::enchant {

    package { [
        'enchant',
        'myspell-af',
        'myspell-bg',
        'myspell-ca',
        'myspell-cs',
        'myspell-da',
        'myspell-de',
        'myspell-de',
        'myspell-de',
        'myspell-de',
        'myspell-el',
        'myspell-en',
        'myspell-en',
        'myspell-en',
        'myspell-en',
        'myspell-eo',
        'myspell-es',
        'myspell-et',
        'myspell-fa',
        'myspell-fo',
        'myspell-fr',
        'myspell-fr',
        'myspell-ga',
        'myspell-gd',
        'myspell-gv',
        'myspell-he',
        'myspell-hr',
        'myspell-hu',
        'myspell-hy',
        'myspell-it',
        'myspell-ku',
        'myspell-lt',
        'myspell-lv',
        'myspell-nb',
        'myspell-nl',
        'myspell-nn',
        'myspell-nr',
        'myspell-ns',
        'myspell-pl',
        'myspell-pt',
        'myspell-pt',
        'myspell-pt',
        'myspell-ru',
        'myspell-sk',
        'myspell-sl',
        'myspell-ss',
        'myspell-st',
        'myspell-sv',
        'myspell-sw',
        'myspell-th',
        'myspell-tl',
        'myspell-tn',
        'myspell-to',
        'myspell-ts',
        'myspell-uk',
        'myspell-ve',
        'myspell-xh',
        'myspell-zu',
    ]:
        ensure => 'installed',
    }

}
