#! /bin/bash
set -e

cat <<EOM

[1;31m      ^[0m
[1;31m     / \[0m     Before you start the NFS service on this server you must be
[1;31m    / [37m|[31m \[0m    [1;4mabsolutely[0m certain that the other server is completely stopped
[1;31m   /  [37m*[31m  \[0m   and that none of the filesystems are mounted!
[1;31m  /_______\[0m
[1;33m   DANGER![0m

The exportred filesystem between labstore1001 and labstore1002 are on a
single directly attached storage array.  Having both run at the same time
WILL break things!  Only start NFS here if the other server is powered
down or in single-user mode *and* has not mounted any of the attached
filesystems.

To proceed, type: I am absolutely certain!
EOM
echo -n "                : "
read sure
if [ "x$sure" != "xI am absolutely certain!" ]; then
  echo
  echo "Bailing out.  Nothing was done."
  echo
  exit 1
fi

/bin/systemctl stop nfs-kernel-server

# Activate all volumes!
# FIXME: Investigate ways to selectively activate them.
# Possibly involving lvm.conf or explicitly listing snapshots
/sbin/vgchange -aay -v
/bin/mount /srv/project/tools
/bin/mount /srv/project/maps
/bin/mount /srv/others
/bin/mount /srv/scratch
/bin/systemctl start nfs-exports
/sbin/ip addr add dev eth0 10.64.37.10/24
/bin/systemctl start nfs-kernel-server
