# SPDX-License-Identifier: LicenseRef-Terrapin-Open-Source-License
# https://www.openhub.net/licenses/terrapin
# Opengear
opengear;script;ograncid
opengear;login;oglogin

# SR-Linux
srlinux;script;rancid -t srlinux
srlinux;login;srllogin
srlinux;module;srlinux
srlinux;inloop;srlinux::inloop
srlinux;command;srlinux::ShowVersion;show version | as yaml
srlinux;command;srlinux::ShowPlatform;show platform fan-tray | as yaml
srlinux;command;srlinux::ShowPlatform;show platform linecard | as yaml
srlinux;command;srlinux::ShowPlatform;show platform power-supply | as yaml
srlinux;command;srlinux::RunningConfig;info flat from running