#!/bin/bash

######################################
# This file is managed by puppet!
######################################

set -e

ANALYTICS_PRIVATEDATA_USERS=$(getent group analytics-privatedata-users | cut -d ":" -f 4 | tr "," " ")
for user in $(ls /srv/home)
do
    if [ -e /srv/home/$user ]; then
        echo "chown $user:analytics-privatedata-users /srv/home/$user"
        echo "chmod 750 /srv/home/$user"
    fi
done