#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
#
# symlink to /usr/bin/<util>-<instance> to address the respective cassandra
# instance

set -e
set -u

# We expect to invoke this via an instance-specific symlink; Error out if
# invoked directly.
if test ! -L "$0"; then
    echo "$0 was not meant to be invoked directly!" >&2
    exit 1
fi

IFS="-" read -ra parts <<< "$(basename $0)"

cmd=${parts[0]}
cid=${parts[1]}


export CASSANDRA_INCLUDE=/etc/cassandra.in.sh
export CASSANDRA_CONF=/etc/cassandra-${cid}
export CASSANDRA_LOG_DIR=/var/log/cassandra

exec "$(dirname $0)"/$cmd "$@"
