# SPDX-License-Identifier: Apache-2.0
groups:
- name: nodejs
  rules:
  # service_runner_request_duration_seconds is being deprecated by new metric express_router_request_duration_seconds
  # These rules can be removed once all services use an updated service-template-node and expose
  # metrics directly through prometheus (instead of via prometheus-statsd-exporter bridge).
  - record: service_uri:service_runner_request_duration_seconds:50pct5m
    expr: histogram_quantile(0.5, sum by(uri, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_uri:service_runner_request_duration_seconds:90pct5m
    expr: histogram_quantile(0.9, sum by(uri, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_uri:service_runner_request_duration_seconds:99pct5m
    expr: histogram_quantile(0.99, sum by(uri, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_method:service_runner_request_duration_seconds:50pct5m
    expr: histogram_quantile(0.5, sum by(method, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_method:service_runner_request_duration_seconds:90pct5m
    expr: histogram_quantile(0.9, sum by(method, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_method:service_runner_request_duration_seconds:99pct5m
    expr: histogram_quantile(0.99, sum by(method, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_status:service_runner_request_duration_seconds:50pct5m
    expr: histogram_quantile(0.5, sum by(status, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_status:service_runner_request_duration_seconds:90pct5m
    expr: histogram_quantile(0.9, sum by(status, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))
  - record: service_status:service_runner_request_duration_seconds:99pct5m
    expr: histogram_quantile(0.99, sum by(status, le, service) (rate(service_runner_request_duration_seconds_bucket[5m])))

  # express_router_request_duration_seconds is emitted by services that use service-template-node.
  - record: service_uri:express_router_request_duration_seconds:50pct5m
    expr: histogram_quantile(0.5, sum by(path, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_uri:express_router_request_duration_seconds:90pct5m
    expr: histogram_quantile(0.9, sum by(path, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_uri:express_router_request_duration_seconds:99pct5m
    expr: histogram_quantile(0.99, sum by(path, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_method:express_router_request_duration_seconds:50pct5m
    expr: histogram_quantile(0.5, sum by(method, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_method:express_router_request_duration_seconds:90pct5m
    expr: histogram_quantile(0.9, sum by(method, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_method:express_router_request_duration_seconds:99pct5m
    expr: histogram_quantile(0.99, sum by(method, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_status:express_router_request_duration_seconds:50pct5m
    expr: histogram_quantile(0.5, sum by(status, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_status:express_router_request_duration_seconds:90pct5m
    expr: histogram_quantile(0.9, sum by(status, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))
  - record: service_status:express_router_request_duration_seconds:99pct5m
    expr: histogram_quantile(0.99, sum by(status, le, service) (rate(express_router_request_duration_seconds_bucket[5m])))

# The following rules are heavy in evaluation, and thus split in different
# groups for concurrent evaluation https://phabricator.wikimedia.org/T387965
- name: envoy-upstream-rq
  rules:
  - record: "app_envoy_cluster_namespace:envoy_cluster_upstream_rq_time:50pct2m"
    expr: |
      histogram_quantile(0.5, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name!="admin_interface"}[2m])))
  - record: "app_envoy_cluster_namespace:envoy_cluster_upstream_rq_time:75pct2m"
    expr: |
      histogram_quantile(0.75, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name!="admin_interface"}[2m])))
  - record: "app_envoy_cluster_namespace:envoy_cluster_upstream_rq_time:90pct2m"
    expr: |
      histogram_quantile(0.90, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name!="admin_interface"}[2m])))
  - record: "app_envoy_cluster_namespace:envoy_cluster_upstream_rq_time:99pct2m"
    expr: |
      histogram_quantile(0.99, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name!="admin_interface"}[2m])))

- name: envoy-downstream-rq
  rules:
  - record: "app_envoy_cluster_namespace:envoy_cluster_downstream_rq_time:50pct2m"
    expr: |
      histogram_quantile(0.5, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_downstream_rq_time_bucket{envoy_cluster_name!="admin_interface"}[2m])))
  - record: "app_envoy_cluster_namespace:envoy_cluster_downstream_rq_time:75pct2m"
    expr: |
      histogram_quantile(0.75, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_downstream_rq_time_bucket{envoy_cluster_name!="admin_interface"}[2m])))
  - record: "app_envoy_cluster_namespace:envoy_cluster_downstream_rq_time:90pct2m"
    expr: |
      histogram_quantile(0.90, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_downstream_rq_time_bucket{envoy_cluster_name!="admin_interface"}[2m])))
  - record: "app_envoy_cluster_namespace:envoy_cluster_downstream_rq_time:99pct2m"
    expr: |
      histogram_quantile(0.99, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_downstream_rq_time_bucket{envoy_cluster_name!="admin_interface"}[2m])))

- name: envoy-upstream-cx-connect
  rules:
  - record: "app_envoy_cluster_namespace:envoy_cluster_upstream_cx_connect_ms:50pct2m"
    expr: |
      histogram_quantile(0.5, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name!="admin_interface"}[2m])))
  - record: "app_envoy_cluster_namespace:envoy_cluster_upstream_cx_connect_ms:75pct2m"
    expr: |
      histogram_quantile(0.75, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name!="admin_interface"}[2m])))
  - record: "app_envoy_cluster_namespace:envoy_cluster_upstream_cx_connect_ms:90pct2m"
    expr: |
      histogram_quantile(0.90, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name!="admin_interface"}[2m])))
  - record: "app_envoy_cluster_namespace:envoy_cluster_upstream_cx_connect_ms:99pct2m"
    expr: |
      histogram_quantile(0.99, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_upstream_cx_connect_ms_bucket{envoy_cluster_name!="admin_interface"}[2m])))

- name: envoy-upstream-cx-length
  rules:
  - record: "app_envoy_cluster_namespace:envoy_cluster_upstream_cx_length_ms:50pct2m"
    expr: |
      histogram_quantile(0.5, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name!="admin_interface"}[2m])))
  - record: "app_envoy_cluster_namespace:envoy_cluster_upstream_cx_length_ms:75pct2m"
    expr: |
      histogram_quantile(0.75, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name!="admin_interface"}[2m])))
  - record: "app_envoy_cluster_namespace:envoy_cluster_upstream_cx_length_ms:90pct2m"
    expr: |
      histogram_quantile(0.90, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name!="admin_interface"}[2m])))
  - record: "app_envoy_cluster_namespace:envoy_cluster_upstream_cx_length_ms:99pct2m"
    expr: |
      histogram_quantile(0.99, sum by (le, app, kubernetes_namespace, envoy_cluster_name) (
        rate(envoy_cluster_upstream_cx_length_ms_bucket{envoy_cluster_name!="admin_interface"}[2m])))

- name: mediawiki
  rules:
    ## aggregate edit rate https://phabricator.wikimedia.org/T383963

    # by entry point
    - record: entry_kubernetes_namespace:mediawiki_WikimediaEvents_editResponseTime_seconds_count:rate5m
      expr: sum by (entry, kubernetes_namespace) (rate(mediawiki_WikimediaEvents_editResponseTime_seconds_count[5m]))

    # by wiki
    - record: wiki_kubernetes_namespace:mediawiki_WikimediaEvents_editResponseTime_seconds_count:rate5m
      expr: sum by (wiki, kubernetes_namespace) (rate(mediawiki_WikimediaEvents_editResponseTime_seconds_count[5m]))

    # by wiki and user
    - record: wiki_user_kubernetes_namespace:mediawiki_WikimediaEvents_editResponseTime_seconds_count:rate5m
      expr: sum by (wiki, user, kubernetes_namespace) (rate(mediawiki_WikimediaEvents_editResponseTime_seconds_count[5m]))

    # by bucket for histogram_quantile()
    - record: le_kubernetes_namespace:mediawiki_WikimediaEvents_editResponseTime_seconds_bucket:rate5m
      expr: sum by (le, kubernetes_namespace) (rate(mediawiki_WikimediaEvents_editResponseTime_seconds_bucket[5m]))

- name: temp_phpfpm_workers_recording
  rules:
    # Precompute sums
    - record: temp_phpfpm_workers:active:sum
      expr: sum(phpfpm_processes_total{app="mediawiki", state="active"}) by (site, deployment, release)

    - record: temp_phpfpm_workers:total:sum
      expr: sum(phpfpm_processes_total{app="mediawiki"}) by (site, deployment, release)

    # get active workers percent
    - record: temp_phpfpm_workers:active_percent
      expr: (temp_phpfpm_workers:active:sum * 100) / temp_phpfpm_workers:total:sum

    # Smoothed averages
    - record: temp_phpfpm_workers:active_percent:avg1m
      expr: avg_over_time(temp_phpfpm_workers:active_percent[1m])

    - record: temp_phpfpm_workers:active_percent:avg5m
      expr: avg_over_time(temp_phpfpm_workers:active_percent[5m])

    - record: temp_phpfpm_workers:active_percent:avg10m
      expr: avg_over_time(temp_phpfpm_workers:active_percent[10m])

    - record: temp_phpfpm_workers:active_percent:avg1h
      expr: avg_over_time(temp_phpfpm_workers:active_percent[1h])

- name: authentication_metrics
  rules:
    - record: accountType_entrypoint_event_subtype_sul3:mediawiki_WikimediaEvents_authmanager_success:rate5m
      expr: sum by (accountType, entrypoint, event, subtype, sul3) (rate(mediawiki_WikimediaEvents_authmanager_success_total[5m]))

    - record: accountType_entrypoint_event_reason_subtype_sul3:mediawiki_WikimediaEvents_authmanager_error:rate5m
      expr: sum by (accountType, entrypoint, event, reason, subtype, sul3) (rate(mediawiki_WikimediaEvents_authmanager_error_total[5m]))

    - record: accountType_entrypoint_event_subtype_sul3:mediawiki_WikimediaEvents_authmanager_event:rate5m
      expr: sum by (accountType, entrypoint, event, subtype, sul3) (rate(mediawiki_WikimediaEvents_authmanager_event_total[5m]))

- name: mediawiki_centralauth
  rules:
    - record: le:mediawiki_CentralAuth_session_read_seconds_bucket:rate5m
      expr: sum by (le) (rate(mediawiki_CentralAuth_session_read_seconds_bucket[5m]))

- name: self
  rules:
    - record: job:up:avail
      expr: sum by (job) (up) / count by (job) (up)
