class profile::openstack::base::manila::service (
    String              $version                      = lookup('profile::openstack::base::version'),
    String              $region                       = lookup('profile::openstack::base::region'),
    Array[Stdlib::Fqdn] $openstack_controllers        = lookup('profile::openstack::base::openstack_controllers'),
    Stdlib::Fqdn        $keystone_api_fqdn            = lookup('profile::openstack::base::keystone_api_fqdn'),
    String              $ldap_user_pass               = lookup('profile::openstack::base::ldap_user_pass'),
    Stdlib::Port        $api_bind_port                = lookup('profile::openstack::base::manila::api_bind_port'),
    Boolean             $manila_service_enabled       = lookup('profile::openstack::base::manila::service_enabled'),
    String              $cinder_volume_type           = lookup('profile::openstack::base::manila::cinder_volume_type'),
    String              $db_user                      = lookup('profile::openstack::base::manila::db_user'),
    String              $db_pass                      = lookup('profile::openstack::base::manila::db_pass'),
    String              $db_name                      = lookup('profile::openstack::base::manila::db_name'),
    Stdlib::Fqdn        $db_host                      = lookup('profile::openstack::base::manila::db_host'),
    String              $rabbit_user                  = lookup('profile::openstack::base::manila::rabbit_user'),
    String              $rabbit_pass                  = lookup('profile::openstack::base::manila::rabbit_pass'),
    String              $user_pass                    = lookup('profile::openstack::base::manila::user_pass'),
    String              $nova_flavor_id               = lookup('profile::openstack::base::manila::nova_flavor_id'),
    String              $network_id                   = lookup('profile::openstack::base::manila::network_id'),
    String              $subnet_id                    = lookup('profile::openstack::base::manila::subnet_id'),
    String              $service_image                = lookup('profile::openstack::base::manila::service_image'),
    String              $service_instance_user        = lookup('profile::openstack::base::manila::service_instance_user'),
    String              $service_instance_pass        = lookup('profile::openstack::base::manila::service_instance_pass'),
    String              $metadata_proxy_shared_secret = lookup('profile::openstack::base::neutron::metadata_proxy_shared_secret'),
    ) {

    class { 'openstack::manila::configuration':
        version                      => $version,
        region                       => $region,
        openstack_controllers        => $openstack_controllers,
        keystone_api_fqdn            => $keystone_api_fqdn,
        ldap_user_pass               => $ldap_user_pass,
        api_bind_port                => $api_bind_port,
        cinder_volume_type           => $cinder_volume_type,
        db_user                      => $db_user,
        db_pass                      => $db_pass,
        db_name                      => $db_name,
        db_host                      => $db_host,
        rabbit_user                  => $rabbit_user,
        rabbit_pass                  => $rabbit_pass,
        user_pass                    => $user_pass,
        nova_flavor_id               => $nova_flavor_id,
        network_id                   => $network_id,
        subnet_id                    => $subnet_id,
        service_image                => $service_image,
        service_instance_user        => $service_instance_user,
        service_instance_pass        => $service_instance_pass,
        metadata_proxy_shared_secret => $metadata_proxy_shared_secret,
    }

    class { 'openstack::manila::service':
        enabled => $manila_service_enabled,
        version => $version,
    }
}
