# SPDX-License-Identifier: Apache-2.0
[tox]
envlist = py{39,311,313}-{flake8,unit}
skipsdist = true
skip_missing_interpreters = True


[testenv]
basepython =
           py39: python3.9
           py311: python3.11
           py313: python3.13
allowlist_externals =
                    unit: bash
commands =
         unit: bash -c "cd {toxinidir}/files && pytest --cov=build_envoy_config ."
         flake8: flake8 {toxinidir}/files/
deps =
    pyyaml
    pytest
    pytest-cov
    flake8

[flake8]
statistics = True
ignore = W503
exclude = files/hot_restarter
max-line-length=100
