# SPDX-License-Identifier: Apache-2.0
require_relative "../../../../rake_modules/spec_helper"

describe "nftables::set" do
  on_supported_os(WMFConfig.test_on).each do |os, facts|
    context "on #{os}" do
      let(:facts) { facts }
      let(:title) { "testing_define" }
      let(:params) { { hosts: %w[192.0.2.1 2001:db8::1 not.an.ip.org] } }
      let(:pre_condition) do
        "include nftables
        function dnsquery::lookup($host, $force_ipv6) {
          ['192.0.2.42', '2001:db8::42']
        }
        "
      end
      describe "default run files" do
        it { is_expected.to compile.with_all_deps }
        it do
          is_expected.to contain_file(
            "/etc/nftables/sets/testing_define_ipv4.nft"
          ).with_content(<<~'EOF')
            # Autogenerated by puppet
            set testing_define_ipv4 {
                type ipv4_addr
                elements = { 192.0.2.1,
                         192.0.2.42
                }
            }
          EOF
        end
        it do
          is_expected.to contain_file(
            "/etc/nftables/sets/testing_define_ipv6.nft"
          ).with_content(<<~'EOF')
            # Autogenerated by puppet
            set testing_define_ipv6 {
                type ipv6_addr
                elements = { 2001:db8::1,
                         2001:db8::42
                }
            }
          EOF
        end
        context "with prefix" do
          let(:params) { { hosts: %w[192.0.2.1/24 2001:db8::1/64] } }
          it { is_expected.to compile.with_all_deps }
          it do
            is_expected.to contain_file(
              "/etc/nftables/sets/testing_define_ipv4.nft"
            ).with_content(<<~'EOF')
              # Autogenerated by puppet
              set testing_define_ipv4 {
                  type ipv4_addr
                  flags interval
                  auto-merge
                  elements = { 192.0.2.1/24
                  }
              }
            EOF
          end
          it do
            is_expected.to contain_file(
              "/etc/nftables/sets/testing_define_ipv6.nft"
            ).with_content(<<~'EOF')
              # Autogenerated by puppet
              set testing_define_ipv6 {
                  type ipv6_addr
                  flags interval
                  auto-merge
                  elements = { 2001:db8::1/64
                  }
              }
            EOF
          end
        end
      end
    end
  end
end
