class profile::openstack::eqiad1::cinder(
    String $version = lookup('profile::openstack::eqiad1::version'),
    Array[OpenStack::ControlNode] $openstack_control_nodes = lookup('profile::openstack::eqiad1::openstack_control_nodes'),
    Array[Stdlib::Fqdn] $rabbitmq_nodes = lookup('profile::openstack::eqiad1::rabbitmq_nodes'),
    Stdlib::Fqdn $keystone_fqdn = lookup('profile::openstack::eqiad1::keystone_api_fqdn'),
    String $db_pass = lookup('profile::openstack::eqiad1::cinder::db_pass'),
    Stdlib::Fqdn $db_host = lookup('profile::openstack::eqiad1::cinder::db_host'),
    Stdlib::Port $api_bind_port = lookup('profile::openstack::eqiad1::cinder::api_bind_port'),
    String $ceph_pool = lookup('profile::openstack::eqiad1::cinder::ceph_pool'),
    String $rabbit_pass = lookup('profile::openstack::eqiad1::cinder::rabbit_pass'),
    String $ldap_user_pass = lookup('profile::openstack::eqiad1::ldap_user_pass'),
    String $region = lookup('profile::openstack::eqiad1::region'),
    Hash   $cinder_backup_volumes = lookup('profile::openstack::eqiad1::cinder_backup_volumes'),
    String[1]           $ceph_rbd_client_name  = lookup('profile::openstack::eqiad1::cinder::ceph_rbd_client_name'),
    Array[Stdlib::Fqdn] $haproxy_nodes         = lookup('profile::openstack::eqiad1::haproxy_nodes'),
    Array[String] $all_backend_names           = lookup('profile::openstack::eqiad1::cinder::all_backend_names'),
    Boolean $enforce_policy_scope = lookup('profile::openstack::eqiad1::keystone::enforce_policy_scope'),
    Boolean $enforce_new_policy_defaults = lookup('profile::openstack::eqiad1::keystone::enforce_new_policy_defaults'),
) {
    class {'::profile::openstack::base::cinder':
        version                     => $version,
        openstack_control_nodes     => $openstack_control_nodes,
        rabbitmq_nodes              => $rabbitmq_nodes,
        keystone_fqdn               => $keystone_fqdn,
        region                      => $region,
        db_pass                     => $db_pass,
        db_host                     => $db_host,
        api_bind_port               => $api_bind_port,
        ceph_pool                   => $ceph_pool,
        ceph_rbd_client_name        => $ceph_rbd_client_name,
        ldap_user_pass              => $ldap_user_pass,
        rabbit_pass                 => $rabbit_pass,
        active                      => true,
        cinder_backup_volumes       => $cinder_backup_volumes,
        haproxy_nodes               => $haproxy_nodes,
        all_backend_names           => $all_backend_names,
        cinder_volume_nodes         => wmflib::class::hosts('profile::openstack::eqiad1::cinder::volume'),
        enforce_policy_scope        => $enforce_policy_scope,
        enforce_new_policy_defaults => $enforce_new_policy_defaults,
    }
}
