#!/bin/bash
#
# Shell script that pulls zone templates from the origin or master DNS server,
# regenerate zones & configuration and reload the DNS server.
#
# Written by Faidon Liambotis, Jul 2013

set -e

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

CONFFILE=/etc/wikimedia-authdns.conf

# Source the configuration file
[ -f $CONFFILE ] && . $CONFFILE

die() { echo >&2 "E: $*"; exit 1; }

if [ "$(id -u)" -ne "0" ]; then
    die "this script needs root"
fi

if [ ! -d $WORKINGDIR ]; then
    die "$WORKINGDIR is not a directory"
fi

if [ ! -e "/etc/gdnsd/config-options" ]; then
    die "/etc/gdnsd/config-options not found, system misconfigured?"
fi

cd $WORKINGDIR

# setup locking; only one copy of this may be running at the same time
LOCKFILE=/var/lock/authdns-local-update
LOCKFD=9
lock()   { flock -xn $LOCKFD; }
unlock() { rm -f $LOCKFILE; }
eval "exec $LOCKFD>\"$LOCKFILE\""; trap unlock EXIT

if ! flock -xn $LOCKFD; then
    die "failed to lock, another update running?"
fi

DEPLOY_SKIP_RELOAD=""
DEPLOY_INITIAL=""
PULL_ARGS=""
while :; do
    case "$1" in
        --skip-reload)
            DEPLOY_SKIP_RELOAD="--skip-reload"
            shift
            ;;
        --initial)
            DEPLOY_INITIAL="--no-gdnsd"
            shift
            ;;
        --skip-review)
            PULL_ARGS="--skip-review"
            shift
            ;;
        *)
            break
            ;;
    esac
done

REMOTE=""
if [ -z "$1" ]; then
    if [ -z "$ORIGIN" ]; then
        die "no master given and no origin defined in config"
    fi
    REMOTE=$ORIGIN
else
    REMOTE="ssh://${1}${WORKINGDIR}"
    PULL_ARGS="--skip-review"
fi
echo "Pulling the current revision from $REMOTE"
sudo -u authdns authdns-git-pull $PULL_ARGS $REMOTE

echo "Deploying via utils/deploy-check.py..."
utils/deploy-check.py --deploy $DEPLOY_INITIAL $DEPLOY_SKIP_RELOAD
