#!/bin/bash
#
# Shell script that pulls zone templates from the origin or master DNS server,
# regenerate zones & configuration and reload the DNS server.
#
# Written by Faidon Liambotis, Jul 2013

set -e

CONFFILE=/etc/wikimedia-authdns.conf

# Source the configuration file
[ -f $CONFFILE ] && . $CONFFILE

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

die() { echo >&2 "E: $*"; exit 1; }

if [ "$(id -u)" -ne "0" ]; then
    die "this script needs root"
fi

# setup locking; only one copy of this may be running at the same time
LOCKFILE=/var/lock/authdns-local-update
LOCKFD=9
lock()   { flock -xn $LOCKFD; }
unlock() { rm -f $LOCKFILE; }
eval "exec $LOCKFD>\"$LOCKFILE\""; trap unlock EXIT

if ! flock -xn $LOCKFD; then
    die "failed to lock, another update running?"
fi

if [ "$1" = "--skip-reload" ]; then
    SKIP_RELOAD="true"
    shift
fi

REMOTE=""
if [ -z "$1" ]; then
    if [ -z "$ORIGIN" ]; then
        die "no master given and no origin defined in config"
    fi
    REMOTE=$ORIGIN
else
    REMOTE="ssh://$1/etc/gdnsd"
fi

echo "Pulling the current revision"
(cd /etc/gdnsd; authdns-git-pull $REMOTE)

echo "Generating zonefiles from zone templates"
authdns-gen-zones /etc/gdnsd/templates /etc/gdnsd/zones

echo "Generating gdnsd config"
if [ ! -e "/etc/gdnsd/config-head" ]; then
    die "config-head not found, system misconfigured?"
fi
if [ ! -e "/etc/gdnsd/config-geo" ]; then
    die "config-geo not found, system misconfigured?"
fi
cp /etc/gdnsd/config /etc/gdnsd/config~ 2>/dev/null || true
cat /etc/gdnsd/config-head /etc/gdnsd/config-geo > /etc/gdnsd/config

echo "Doing sanity checks"
if [ ! -s "/etc/gdnsd/config" ]; then
    die "config seems empty, aborting"
elif [ `ls /etc/gdnsd/zones |wc -l` -le 10 ]; then
    die "less than 10 zones, probably something's wrong, aborting";
fi

if ! which gdnsd > /dev/null || [ "$SKIP_RELOAD" = "true" ]; then
    rm -f /etc/gdnsd/config~
    exit 0
fi

if ! gdnsd checkconf 2>/dev/null; then
    mv /etc/gdnsd/config~ /etc/gdnsd/config
    die "gdnsd checkconf failed, aborting"
fi

if ! cmp --quiet /etc/gdnsd/config~ /etc/gdnsd/config; then
    rm -f /etc/gdnsd/config~
    echo "Reloading zones & config"
    gdnsd force-reload
else
    rm -f /etc/gdnsd/config~
    echo "Reloading zones"
    gdnsd reload
fi
