#!/bin/bash
#
# Shell script that pulls zone templates from the origin or master DNS server,
# regenerate zones & configuration and reload the DNS server.
#
# Written by Faidon Liambotis, Jul 2013

set -e

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

CONFFILE=/etc/wikimedia-authdns.conf

# Source the configuration file
[ -f $CONFFILE ] && . $CONFFILE

die() { echo >&2 "E: $*"; exit 1; }

if [ "$(id -u)" -ne "0" ]; then
    die "this script needs root"
fi

# setup locking; only one copy of this may be running at the same time
LOCKFILE=/var/lock/authdns-local-update
LOCKFD=9
lock()   { flock -xn $LOCKFD; }
unlock() { rm -f $LOCKFILE; }
eval "exec $LOCKFD>\"$LOCKFILE\""; trap unlock EXIT

if ! flock -xn $LOCKFD; then
    die "failed to lock, another update running?"
fi

while :; do
    case "$1" in
        --skip-reload)
            SKIP_RELOAD="true"
            shift
            ;;
        --skip-review)
            SKIP_REVIEW="true"
            shift
            ;;
        *)
            break
            ;;
    esac
done

REMOTE=""
if [ -z "$1" ]; then
    if [ -z "$ORIGIN" ]; then
        die "no master given and no origin defined in config"
    fi
    REMOTE=$ORIGIN
    if [ "$SKIP_REVIEW" = "true" ]; then
        PULL_ARGS="--skip-review"
    fi
else
    REMOTE="ssh://${1}${WORKINGDIR}"
    PULL_ARGS="--skip-review"
fi
echo "Pulling the current revision from $REMOTE"
(cd $WORKINGDIR; sudo -u authdns authdns-git-pull $PULL_ARGS $REMOTE)

if [ ! -e "/etc/gdnsd/config-options" ]; then
    die "config-options not found, system misconfigured?"
fi
if [ ! -e "$WORKINGDIR/config" ]; then
    die "config not found, system misconfigured?"
fi
if [ ! -e "$WORKINGDIR/templates" ]; then
    die "templates not found, system misconfigured?"
fi
if [ ! -e "$WORKINGDIR/geo-maps" ]; then
    die "geo-maps not found, system misconfigured?"
fi
if [ ! -e "$WORKINGDIR/geo-resources" ]; then
    die "geo-resources not found, system misconfigured?"
fi
if [ ! -e "$WORKINGDIR/admin_state" ]; then
    die "admin_state not found, system misconfigured?"
fi

echo "Generating zonefiles from zone templates"
$WORKINGDIR/utils/authdns-gen-zones.py $WORKINGDIR/templates /etc/gdnsd/zones

echo "Doing sanity checks"
if [ `ls /etc/gdnsd/zones |wc -l` -le 10 ]; then
    die "less than 10 zones, something's probably wrong, aborting";
fi

echo "Copy config bits"
cp -f /etc/gdnsd/config /etc/gdnsd/config~ 2>/dev/null || true
cp -f /etc/gdnsd/geo-maps /etc/gdnsd/geo-maps~ 2>/dev/null || true
cp -f /etc/gdnsd/geo-resources /etc/gdnsd/geo-resources~ 2>/dev/null || true
cp -f $WORKINGDIR/config /etc/gdnsd/
cp -f $WORKINGDIR/geo-maps /etc/gdnsd/geo-maps
cp -f $WORKINGDIR/geo-resources /etc/gdnsd/geo-resources

# initial run, before gdnsd was installed
if ! which gdnsd > /dev/null || [ "$SKIP_RELOAD" = "true" ]; then
    rm -f /etc/gdnsd/config~
    rm -f /etc/gdnsd/geo-maps~
    rm -f /etc/gdnsd/geo-resources~
    exit 0
fi

if ! gdnsd checkconf >/dev/null 2>&1; then
    if [ -f /etc/gdnsd/config~ ]; then
        mv /etc/gdnsd/config~ /etc/gdnsd/config
    fi
    if [ -f /etc/gdnsd/geo-maps~ ]; then
        mv /etc/gdnsd/geo-maps~ /etc/gdnsd/geo-maps
    fi
    if [ -f /etc/gdnsd/geo-resources~ ]; then
        mv /etc/gdnsd/geo-resources~ /etc/gdnsd/geo-resources
    fi
    die "gdnsd checkconf failed, aborting"
fi

echo "Copying admin_state into place; will take effect immediately"
mkdir -p /var/lib/gdnsd
cp -f $WORKINGDIR/admin_state /var/lib/gdnsd/

### reload

if ( ! cmp --quiet /etc/gdnsd/config~ /etc/gdnsd/config ) \
  || ( ! cmp --quiet /etc/gdnsd/geo-maps~ /etc/gdnsd/geo-maps ) \
  || ( ! cmp --quiet /etc/gdnsd/geo-resources~ /etc/gdnsd/geo-resources ); then
    rm -f /etc/gdnsd/config~
    rm -f /etc/gdnsd/geo-maps~
    rm -f /etc/gdnsd/geo-resources~
    if [ -x /usr/bin/gdnsdctl ]; then
        echo "Replacing gdnsd to update config and zones:"
        /usr/bin/gdnsdctl replace
    else
        echo "Restarting to update zones & config"
        service gdnsd restart >/dev/null
    fi
else
    rm -f /etc/gdnsd/config~
    rm -f /etc/gdnsd/geo-maps~
    rm -f /etc/gdnsd/geo-resources~
    echo "Reloading zones"
    if [ -x /usr/bin/gdnsdctl ]; then
        /usr/bin/gdnsdctl reload-zones
    else
        gdnsd reload-zones
    fi
fi
