# SPDX-License-Identifier: Apache-2.0
# Early-stage filter to copy the original log event in whole to event.original
filter {
  # TODO: event.original should be generated closer to the producer
  if ![event][original] or ![event.original] {
    if [ecs][version] or [ecs.version] {
      # Other 'event' fields are dropped when a nested event
      # field exists alongside dot-delimited fields.  This
      # looks like a bug in dot_expander, but under test,
      # dot_expander does the right thing.
      # We'll work around this by setting event.original here
      # to be expanded by dot_expander in the ecs pre-filter.
      ruby {
        code => "event.set('event.original', event.to_json)"
        id => "filter/ruby/event_original/write_event_original"
      }
    }
  }
}
