# SPDX-License-Identifier: Apache-2.0
# Filters for pybal to ECS formatting
filter {
  if [program] == "pybal" {
    # store original copy unindexed
    ruby {
      code => "event.set('[event][original]', event.to_json)"
      id => "filter/ruby/pybal_ecs/write_event_original"
    }

    mutate {
      add_field => {
        "[ecs][version]" => "1.11.0"
        "[service][type]" => "pybal"
      }
      id => "filter/mutate/pybal_ecs/ecs_normalization"
    }
  }
}
