# SPDX-License-Identifier: Apache-2.0
# Thanos-Query ECS formatting filters
filter {
  if [program] == "thanos-query" {
    # store original copy unindexed
    ruby {
      code => "event.set('[event][original]', event.to_json)"
      id => "filter/ruby/thanos_ecs/write_event_original"
    }

    logfmt {
      source => "message"
      target => "labels"
      id => "filter/logfmt/thanos_ecs/parse_logfmt"
    }

    mutate {
      rename => {
        "program" => "[service][type]"
        "[labels][msg]" => "message"
        "[labels][ts]" => "timestamp"
        "[labels][level]" => "level"
        "[labels][err]" => "[error][message]"
        "[labels][address]" => "[destination][address]"
        "[labels][caller]" => "[log][logger]"
      }
      add_field => { "[ecs][version]" => "1.11.0" }
      id => "filter/mutate/thanos_ecs/ecs_normalization"
    }
  }
}
