# SPDX-License-Identifier: Apache-2.0
filter {
  if [program] == "haproxy" {
    # store original copy unindexed
    ruby {
      code => "event.set('[event][original]', event.to_json)"
      id => "filter/ruby/haproxy_ecs/write_event_original"
    }

    mutate {
      add_field => {
        "[ecs][version]" => "1.11.0"
        "[service][type]" => "haproxy"
      }
      id => "filter/mutate/haproxy_ecs/ecs_normalization"
    }
  }
}
