# SPDX-License-Identifier: Apache-2.0
# Icinga ECS Compatibility
filter {
  if [program] == "icinga" {
    # store original copy unindexed
    ruby {
      code => "event.set('[event][original]', event.to_json)"
      id => "filter/ruby/icinga_ecs/write_event_original"
    }

    mutate {
      rename => {
       "program" => "[service][type]"
       "host" => "[host][name]"
       "message" => "[log][original]"
      }
      add_field => {
        "[ecs][version]" => "1.7.0"
      }
      id => "filter/mutate/icinga_ecs/ecs_normalization"
    }
  }
}
