# SPDX-License-Identifier: Apache-2.0
# Thanos-Query and Query-Frontend ECS formatting filters
filter {
  if ([program] == "thanos-query") or ([program] == "thanos-query-frontend") {
    # store original copy unindexed
    ruby {
      code => "event.set('[event][original]', event.to_json)"
      id => "filter/ruby/thanos_ecs/write_event_original"
    }

    if [program] == "thanos-query-frontend" {
      mutate {
        gsub => [ "message", "\[\]=", "=" ]
        id => "filter/mutate/thanos_ecs/query-frontend/remove_square_brackets_from_logfmt_keys"
      }
    }

    logfmt {
      source => "message"
      target => "labels"
      id => "filter/logfmt/thanos_ecs/parse_logfmt"
    }

    mutate {
      rename => {
        "program" => "[service][type]"
        "[labels][msg]" => "message"
        "[labels][ts]" => "timestamp"
        "[labels][level]" => "level"
        "[labels][err]" => "[error][message]"
        "[labels][address]" => "[destination][address]"
        "[labels][caller]" => "[log][logger]"

        "[labels][method]" => "[http][request][method]"
        "[labels][path]" => "[url][path]"

        "[labels][param_start]" => "[query][span][start]"
        "[labels][param_end]" => "[query][span][end]"

        "[labels][param_query]" => "[query][text]"
        "[labels][param_match]" => "[query][text]"

        "[labels][time_taken]" => "[labels][response_time]"
        "[labels][trace_id]" => "[trace][id]"
      }
      convert => {
        "[query][span][start]" => "integer"
        "[query][span][end]" => "integer"
      }
      add_field => { "[ecs][version]" => "1.11.0" }
      id => "filter/mutate/thanos_ecs/ecs_normalization"
    }

    date {
      match => [ "[timestamp]", "ISO8601" ]
      target => "@timestamp"
      id => "filter/date/thanos_ecs/timstamp"
    }
  }

  if [service][type] == "thanos-query-frontend" {

    if [labels][response_time] {
      ruby {
        path => "/etc/logstash/filter_scripts/go_time_duration_to_nanosec.rb"
        script_params => {
          "source" => "[labels][response_time]"
          "target" => "[event][duration]"
        }
        id => "filter/ruby/thanos_ecs/query-frontend/response_time_to_nanosec"
      }

      mutate {
        remove_field => [
          "[labels][response_time]"
        ]
        id => "filter/mutate/thanos_ecs/query-frontend/remove_response_time"
      }

      ruby {
        code => "event.set('[event][start]', LogStash::Timestamp.at(event.get('@timestamp').to_f - (event.get('[event][duration]').to_f / 1000000000.0)))"
        id => "filter/ruby/thanos-ecs/query-frontend/event_start"
      }
    }

    if [query][span][start] {
      date {
        match => [ "[query][span][start]", "UNIX" ]
        target => "[query][span][start]"
        id => "filter/date/thanos_ecs/query-frontend/convert_start"
      }
    }

    if [query][span][end] {
      date {
        match => [ "[query][span][end]", "UNIX" ]
        target => "[query][span][end]"
        id => "filter/date/thanos_ecs/query-frontend/convert_end"
      }
    }

    if [labels][param_time] {
      date {
        match => [ "[labels][param_time]", "ISO8601" ]
        target => "[query][span][end]"
        id => "filter/date/thanos_ecs/query-frontend/convert_time"
      }

      mutate {
        remove_field => [
          "[labels][param_time]"
        ]
      }
    }

    if [query][span][start] and [query][span][end] {
      ruby {
        code => "event.set('[query][span][total]', (event.get('[query][span][end]').to_f - event.get('[query][span][start]').to_f))"
        id => "filter/ruby/thanos_ecs/query-frontend/duration"
      }
    }
  }
}
