# SPDX-License-Identifier: Apache-2.0
# Map LibreChat and LiteLLM JSON logs from the liftwing-studio namespace (Hummingbird) to ECS.
# Runs after 15-filter_kubernetes_docker.conf has parsed the JSON log line. T440198
filter {
  if [kubernetes][namespace_name] == "liftwing-studio" and "k8s_docker_log_field_parsed" in [tags] {
    if [kubernetes][container_name] =~ /-litellm$/ {
      ruby {
        code => "event.set('[event][original]', event.to_json)"
        id => "filter/ruby/kubernetes_liftwing_studio_ecs/litellm_write_event_original"
      }

      if [logger] =~ /^.+:[0-9]+$/ {
        dissect {
          mapping => { "logger" => "%{[log][origin][file][name]}:%{[log][origin][file][line]}" }
          remove_field => [ "logger" ]
          id => "filter/dissect/kubernetes_liftwing_studio_ecs/litellm_logger"
        }
      }

      mutate {
        rename => {
          "component" => "[log][logger]"
          "stacktrace" => "[error][stack_trace]"
          "requester_ip" => "[client][ip]"
        }
        remove_field => [ "color_message" ]
        add_field => {
          "[ecs][version]" => "1.11.0"
          "[service][type]" => "litellm"
        }
        id => "filter/mutate/kubernetes_liftwing_studio_ecs/litellm_ecs_normalization"
      }
    } else if [kubernetes][container_name] !~ /-tls-proxy$/ {
      ruby {
        code => "event.set('[event][original]', event.to_json)"
        id => "filter/ruby/kubernetes_liftwing_studio_ecs/librechat_write_event_original"
      }

      mutate {
        rename => {
          "stack" => "[error][stack_trace]"
          "userId" => "[user][id]"
          "requestId" => "[http][request][id]"
          "tenantId" => "[labels][tenant_id]"
        }
        add_field => {
          "[ecs][version]" => "1.11.0"
          "[service][type]" => "librechat"
        }
        id => "filter/mutate/kubernetes_liftwing_studio_ecs/librechat_ecs_normalization"
      }
    }
  }
}
