# SPDX-License-Identifier: Apache-2.0
filter {
  if [error][stack_trace] {
    # flatten error.stack_trace when it is an array of objects
    # c.f. https://gerrit.wikimedia.org/g/operations/deployment-charts/+/master/charts/mediawiki/rsyslog/templates.conf#105
    # I could not find evidence of the array-of-objects format in Logstash as of 2025-06-25.  This satisfies the tests at least.
    ruby {
      code => 'if event.get("[error][stack_trace]").is_a?(Array); event.set("[error][stack_trace]", event.get("[error][stack_trace]").map { |v| "[" + v["address"] + "] " + v["function"] + " " + v["file"] + ":" + v["line"] }.join("\n")); end'
      id => "filter/ruby/mediawiki_ecs/flatten_stack_trace_objects"
    }
  }
}
