# SPDX-License-Identifier: Apache-2.0
filter {
  if [event][dataset] == "apache.access" {
    mutate {
      replace => { "[@metadata][partition]" => "webrequest" }
      id => "filter/mutate/apache2_access/reroute_access_logs"
    }
  }
}
