# SPDX-License-Identifier: Apache-2.0
filter {
  if "access" in [event][type] {
    mutate {
      replace => { "[@metadata][partition]" => "webrequest" }
      id => "filter/mutate/access_logs/reroute"
    }
  }
}
