# SPDX-License-Identifier: Apache-2.0
# Index routing configuration
filter {
  if [type] == "syslog" and [program] == "php7.4-fpm" {
    mutate {
      add_field => { "[@metadata][index_name]" => 'logstash-deploy' }
      replace   => { "[@metadata][partition]"  => "deploy" }
      id => 'filter/mutate/routing/syslog_deploy_indexes'
    }
  } else if [type] == "mediawiki" and [channel] =~ /(error|exception|fatal)/ {
    mutate {
      add_field => { "[@metadata][index_name]" => 'logstash-deploy' }
      replace   => { "[@metadata][partition]"  => "deploy" }
      id => 'filter/mutate/routing/mw_deploy_indexes'
    }
  } else if [type] == "syslog" and [program] == "input-file-kubernetes" {
    mutate {
      add_field => { "[@metadata][index_name]" => 'logstash-%{[@metadata][partition]}' }
      id => 'filter/mutate/routing/route_via_partition_metadata'
    }
  } else if [type] == "syslog" {
    mutate {
      add_field => { "[@metadata][index_name]" => 'logstash-syslog' }
      replace   => { "[@metadata][partition]"  => "syslog" }
      id => 'filter/mutate/routing/syslog_indexes'
    }
  } else if [type] == "mediawiki" {
    mutate {
      add_field => { "[@metadata][index_name]" => 'logstash-mediawiki' }
      replace   => { "[@metadata][partition]"  => "mediawiki" }
      id => 'filter/mutate/routing/mw_indexes'
    }
  } else {
    mutate {
      add_field => { "[@metadata][index_name]" => 'logstash' }
      id => 'filter/mutate/routing/default_indexes'
    }
  }

  # Generate datestamp format based on rotation frequency setting
  if [@metadata][rotation_frequency] == "daily" {
    mutate {
      replace => { "[@metadata][datestamp_format]" => "%{+YYYY.MM.dd}" }
      id => 'filter/mutate/routing/set_daily_rotation'
    }
  }
  if [@metadata][rotation_frequency] == "weekly" {
    mutate {
      replace => { "[@metadata][datestamp_format]" => "%{+xxxx.ww}" }
      id => 'filter/mutate/routing/set_weekly_rotation'
    }
  }
  if [@metadata][rotation_frequency] == "monthly" {
    mutate {
      replace => { "[@metadata][datestamp_format]" => "%{+YYYY.MM}" }
      id => 'filter/mutate/routing/set_monthly_rotation'
    }
  }
  if [@metadata][rotation_frequency] == "yearly" {
    mutate {
      replace => { "[@metadata][datestamp_format]" => "%{+YYYY}" }
      id => 'filter/mutate/routing/set_yearly_rotation'
    }
  }

  # Populate target index
  mutate {
    replace => {
      "[@metadata][target_index]" => "%{[@metadata][output]}-%{[@metadata][partition]}-%{[@metadata][policy_revision]}-%{[@metadata][template_version]}-N-%{[@metadata][datestamp_format]}"
    }
    id => 'filter/mutate/routing/set_target_index'
  }
}
