#!/bin/bash

# WARNING: make sure to run any PHP scripts coming from MediaWiki under a
# dedicated user such as `mwdeploy`. This script is running as user `root` on
# the beta cluster.

. /usr/local/lib/mw-deployment-vars.sh
BINDIR=/usr/local/bin

function die() {
	if [ -n "$*" ]; then
		echo >&2 "$*"
	else
		echo >&2 "Update of MediaWiki localisation messages failed" 
	fi
	exit 1
}

if [ "`uname -s`" != Linux ]; then
	die "ERROR: This script requires the Linux operating system to function correctly"
fi

QUIET=--quiet
TEMP=`getopt -o '' -l verbose -- "$@"`
if [ $? -ne 0 ]; then
	exit 1
fi
eval set -- "$TEMP"
while true; do
	case "$1" in
		--verbose)
			QUIET=
			shift
			;;
		--)
			shift
			break
	esac
done

# Calculate the number of parallel threads
# Leave a couple of cores free for other stuff
CPUS=`grep -c 'model name' /proc/cpuinfo`
THREADS=`expr $CPUS - 2`

if [ $THREADS -lt 1 ]; then
	THREADS=1
fi

mwExtVerDbSets=$($BINDIR/mwversionsinuse --extended --withdb) || die
# Regenerate the extension message file list for all active MediaWiki versions
for i in ${mwExtVerDbSets[@]}; do
	mwVerNum=${i%=*}
	mwDbName=${i#*=}

	# Only looks at certain MW version if specified
	if [ -n "$MW_VERSIONS_SYNC" ]; then
		skip=1
		for v in ${MW_VERSIONS_SYNC[@]}; do
			if [ "$mwVerNum" == "$v" ]; then
				skip=0
			fi
		done
		if [ "$skip" -eq "1" ]; then
			continue
		fi
	fi

	echo -n "Updating ExtensionMessages-$mwVerNum.php..."
	mwTempDest=$(sudo -u apache mktemp) || die
	sudo -u apache $BINDIR/mwscript mergeMessageFileList.php --wiki="$mwDbName" \
		--list-file=$MW_COMMON_SOURCE/wmf-config/extension-list $QUIET --output="$mwTempDest" \
		|| die
	sudo -u apache chmod 664 "$mwTempDest"  || die
	cp "$mwTempDest" $MW_COMMON_SOURCE/wmf-config/ExtensionMessages-"$mwVerNum".php || die
	sudo -u apache rm "$mwTempDest" || die
	echo "done"

	# Update ExtensionMessages-*.php in the local copy
	# Though only when commons are different files. Beta has everything on the same
	# shared filesystem and thus cp would complain about copying to the same file.
	if [ `readlink -f $MW_COMMON_SOURCE` != `readlink -f $MW_COMMON` ]; then
		echo "Copying to local copy..."
		sudo -u mwdeploy \
			cp $MW_COMMON_SOURCE/wmf-config/ExtensionMessages-"$mwVerNum".php $MW_COMMON/wmf-config/ \
			|| die
		echo "done"
	fi

	# Rebuild all the CDB files for each language
	echo -n "Updating LocalisationCache for $mwVerNum... "
	sudo -u l10nupdate $BINDIR/mwscript rebuildLocalisationCache.php --wiki="$mwDbName" \
		--outdir=$MW_COMMON_SOURCE/php-$mwVerNum/cache/l10n $QUIET \
		--threads=$THREADS \
		|| die

	# Include JSON versions of the CDB files and add MD5 files
	sudo -u l10nupdate $BINDIR/refreshCdbJsonFiles --directory="$MW_COMMON_SOURCE/php-$mwVerNum/cache/l10n" \
		--threads=$THREADS \
		|| die

	echo "done"
done

