#!/bin/bash

# WARNING: make sure to run any PHP scripts coming from MediaWiki under a
# dedicated user such as `mwdeploy`. This script is running as user `root` on
# the beta cluster.

(

set -e
BINDIR=/usr/local/bin
SOURCE=/home/wikipedia/common
DEST=/usr/local/apache/common-local

if [ "`uname -s`" != Linux ]; then
	echo "ERROR: This script requires the Linux operating system to function correctly"
	exit 1
fi

QUIET=--quiet
TEMP=`getopt -o '' -l verbose -- "$@"`
if [ $? -ne 0 ]; then
	exit 1
fi
eval set -- "$TEMP"
while true; do
	case "$1" in
		--verbose)
			QUIET=
			shift
			;;
		--)
			shift
			break
	esac
done

mwExtVerDbSets=$($BINDIR/mwversionsinuse --extended --withdb)
# Regenerate the extension message file list for all active MediaWiki versions
for i in ${mwExtVerDbSets[@]}; do
	mwVerNum=${i%=*}
	mwDbName=${i#*=}
	echo "Updating ExtensionMessages-$mwVerNum.php..."
	mwTempDest="`sudo -u apache mktemp`"
	sudo -u apache $BINDIR/mwscript mergeMessageFileList.php --wiki="$mwDbName" \
		--list-file=$SOURCE/wmf-config/extension-list $QUIET --output="$mwTempDest"
	sudo -u apache chmod a+r "$mwTempDest"
	cp "$mwTempDest" $SOURCE/wmf-config/ExtensionMessages-"$mwVerNum".php
	sudo -u apache rm "$mwTempDest"

	# Update ExtensionMessages-*.php in the local copy
	sudo -u mwdeploy cp $SOURCE/wmf-config/ExtensionMessages-"$mwVerNum".php $DEST/wmf-config/

	echo -n "Updating LocalisationCache for $mwVerNum... "
	sudo -u l10nupdate $BINDIR/mwscript rebuildLocalisationCache.php --wiki="$mwDbName" \
		--outdir=$SOURCE/php-$mwVerNum/cache/l10n $QUIET
	echo "done"
done


) || echo "Update of MediaWiki localisation messages failed"
