#!/bin/sh
# Shell wrapper for the local version of multiversion/activeMWVersions.
# This script belongs in /usr/bin/ and should be in PATH.
if ! /usr/local/apache/common-local/multiversion/activeMWVersions "$@"; then
	exit 1
fi
