#!/bin/bash

BINDIR=/usr/local/bin
PATH=/bin:/usr/bin:/sbin:/usr/sbin:
TERM=dumb

. /usr/local/lib/mw-deployment-vars.sh

SERVER="$1"
if [ -z "$SERVER" ]; then
	SERVER="${MW_RSYNC_HOST}"
fi

RSYNC_ARGS=("${MW_RSYNC_ARGS[@]}")
# Only looks at certain MW version if specified
if [ -n "$MW_VERSIONS_SYNC" ]; then
	for v in ${MW_VERSIONS_SYNC[@]}; do
		RSYNC_ARGS+=("--include='php-$v/'")
	done
	RSYNC_ARGS+=("--exclude='php-*/'")
fi

echo -n Copying to `hostname -s` from "$SERVER"...
if rsync "${RSYNC_ARGS[@]}" "$SERVER"::common/ "${MW_COMMON}"
then
	echo "ok"
else
	echo "failed"
	exit 1
fi

