#!/bin/bash

. /usr/local/lib/mw-deployment-vars.sh
echo "Synchronizing $MW_COMMON_SOURCE/*.dblist to $MW_COMMON/*.dblist..."
echo "mediawiki-installation:"

dsh "${MW_DSH_ARGS[@]}" -- "
  sudo -u mwdeploy rsync -a $MW_RSYNC_HOST::common/*.dblist $MW_COMMON
"

$BINDIR/dologmsg "!log $USER synchronized database lists files: $*"
