#!/bin/bash
## synchronizes a directory from common/ on all apaches

. /usr/local/lib/mw-deployment-vars.sh
BINDIR=/usr/local/bin

[ $# -lt 1 ] && {
	echo >&2 "Usage: sync-dir directory [message]"
	exit 1
}

FILE=$1
shift

# Sanity check
if [ ! -d "$MW_COMMON_SOURCE/$FILE" ]; then
	echo >&2 "Target file is not a directory"
	exit 1
fi

# Perform syntax check
$BINDIR/lint $MW_COMMON_SOURCE/$FILE || {
	echo >&2 "Aborted due to syntax errors"
	exit 1
}

# Actually sync the dir...
$BINDIR/sync-common-file $FILE "$@"
