#!/bin/bash

echo "Synchronizing /home/wikipedia/common/*.dblist to /usr/local/apache/common-local/*.dblist..."
echo "mediawiki-installation:"

ddsh -cM -g mediawiki-installation -o -oSetupTimeout=30 -F30 "
  sudo -u mwdeploy rsync -a 10.0.5.8::common/*.dblist /usr/local/apache/common-local
"

$BINDIR/dologmsg "!log $USER synchronized database lists files: $*"
