#!/bin/bash

cd `dirname $0`
BINDIR=/usr/local/bin

$BINDIR/set-group-write

if [ -n "$1" ]; then
        MESSAGE=" '"$@"'"
else
        MESSAGE=
fi


ddsh -cM -g mediawiki-installation -o -oSetupTimeout=30 -F30 /usr/bin/sync-common

$BINDIR/dologmsg "!log $USER ran sync-common-all $MESSAGE"
$BINDIR/deploy2graphite sync-common-all
