#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
   Check or set Graphite webapp user credentials

   Usage: graphite-auth [check | set] USER PASSWORD

   Copyright (c) 2013 Ori Livneh and Wikimedia Foundation. All Rights Reserved.

"""
import sys
import argparse
import socket
import os

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'graphite.settings')

from django.contrib.auth.models import User


def check_admin(args):
    try:
        user = User.objects.get(username=args.user)
        return user.check_password(args.password)
    except:
        return False


def set_admin(args):
    try:
        user = User.objects.get(username=args.user)
        user.set_password(args.password)
        user.save()
        return True
    except:
        pass

    try:
        User.objects.create_superuser(
            args.user, 'admin@' + socket.gethostname(), args.password)
        return True
    except:
        pass

    return False


parser = argparse.ArgumentParser()
parser.add_argument('command', choices=('check', 'set'))
parser.add_argument('user')
parser.add_argument('password')
args = parser.parse_args()

if args.command == 'check':
    ok = check_admin(args)
else:
    ok = set_admin(args)

print(ok)
sys.exit(0 if ok else 1)
