#!/bin/bash

set -e
set -u

directory=${1:-}
keep_days=${2:-}

if [ -z "$directory" ] || [ -z "$keep_days" ]; then
  echo "usage: $0 <directory> <keep days>"
  echo
  echo "Clean up files in <directory> older than <keep days>"
  echo
  exit 1
fi

if [ -d "${directory}" ]; then
  /usr/bin/find "${directory}" -type f -mtime "+${keep_days}" -delete
  /usr/bin/find "${directory}" -type d -empty -delete
fi
