# SPDX-License-Identifier: Apache-2.0
# rsyslogd(8) configuration file for natlog. This file is managed by Puppet.
:syslogtag, isequal, "NATLOG:"   /var/log/natlog/natlog.log
:syslogtag, isequal, "NATLOG:"   stop
