#!/bin/bash

. /usr/local/lib/mw-deployment-vars.sh
DBLIST=`<$1`
CMD=$2
shift
shift

for x in $DBLIST; do
	echo -----------------------------------------------------------------
	echo $x 
	echo -----------------------------------------------------------------
	php -ddisplay_errors=On $MW_COMMON/multiversion/MWScript.php $CMD --wiki=$x "${@}" | sed -u "s/^/$x:  /"
done
