#!/bin/bash

. /usr/local/lib/mw-deployment-vars.sh

. $MW_COMMON_SOURCE/multiversion/MWRealm.sh

ALL_DBLIST=$(getRealmSpecificFilename $MW_DBLISTS_SOURCE'/all.dblist')

exec "$(dirname "$0")/foreachwikiindblist" "$ALL_DBLIST" "${@}"
