#!/bin/bash
BINDIR=/usr/local/bin
. /usr/local/lib/mw-deployment-vars.sh

mwVersionNums=$(mwversionsinuse)
for mwVerNum in ${mwVersionNums[@]}; do
	find "$MW_COMMON_SOURCE"/php-"$mwVerNum" -group wikidev -not -perm -020 -exec chmod g+w '{}' ';'
done

find "$MW_COMMON_SOURCE"/wmf-config -group wikidev -not -perm -020 -exec chmod g+w '{}' ';'
find "$MW_COMMON_SOURCE"/multiversion -group wikidev -not -perm -020 -exec chmod g+w '{}' ';'
