#!/bin/bash

# This file is managed by Puppet (files/misc/scripts/sql).

# Read configuration.
. /usr/local/lib/mw-deployment-vars.sh
MWMULTIDIR=$MW_COMMON/multiversion

# Database that the user wants to use/query.
db=$1
shift

# Default to enwiki if no database is specified.
if [ -z "$db" ]; then
    db=enwiki
fi

# Look up MySQL host to connect to.  For centralauth the host cannot
# be determined this way, so we need to use fawiki instead as it is
# located on the same server.
if [ "$db" == "centralauth" ]; then
    lookupdb="fawiki"
else
    lookupdb="$db"
fi
host=`echo 'echo wfGetLB()->getServerName(0);' | /usr/local/bin/mwscript eval.php --wiki="$lookupdb"`

# MySQL user credentials.
MU=wikiadmin
MP=`wikiadmin_pass`

# Execute mysql.
exec mysql -u $MU -p$MP -h $host -D $db "$@"
