#!/bin/bash

db=$1
. /usr/local/lib/mw-deployment-vars.sh

MWMULTIDIR=$MW_COMMON/multiversion

if [ -z $db ];then
	db=enwiki
fi
if [ "$db" == centralauth ]; then
	host=`echo 'echo wfGetLB()->getServerName(0);' | /usr/local/bin/mwscript eval.php --wiki=fawiki`
else
	host=`echo 'echo wfGetLB()->getServerName(0);' | /usr/local/bin/mwscript eval.php --wiki="$db"`
fi

MU=wikiadmin
MP=`wikiadmin_pass`
mysql -u $MU -p$MP -h $host -D enwiki "$@"

