#!/bin/bash

. /usr/local/lib/mw-deployment-vars.sh

cd "$MEDIAWIKI_DEPLOYMENT_DIR/multiversion"
for db in `<"$MEDIAWIKI_DEPLOYMENT_DIR/all.dblist"`; do
	echo $db
	php MWScript.php updateSpecialPages.php $db
	echo
	echo
done
