#!/usr/bin/env bash

postgres_master=""

function show_help() {
  echo "initialize-postgres-slave -H <postgres_master>"
  echo "  postgres_master: hostname of the postgresql master"
}

while getopts "hH:" opt; do
  case "${opt}" in
  h)  show_help
      exit 0
      ;;
  H)  postgres_master="${OPTARG}"
      ;;
  esac
done

if [ "${postgres_master}" = "" ]; then
    echo "hostname of postgresql master (-H) is required"
    exit 1
fi

service postgresql@9.4-main stop

rm -rf /srv/postgresql/9.4/main

mkdir /srv/postgresql/9.4/main
chown postgres: /srv/postgresql/9.4/main/
chmod 700 /srv/postgresql/9.4/main/

sudo -u postgres pg_basebackup \
    --xlog-method=stream \
    --pgdata=/srv/postgresql/9.4/main/ \
    --host=${postgres_master} \
    --username=replication \
    --password

service postgresql@9.4-main start
