#!/usr/bin/env python

from elastictool import ElasticTool


class StartReplication(ElasticTool):
    def execute(self):
        self.set_replication_state("all")

if __name__ == "__main__":
    tool = StartReplication("Enable replication of all shards")
    tool.run()
