#!/usr/bin/python3
# SPDX-License-Identifier: Apache-2.0

import unittest
import tempfile
import shutil
import pathlib
import logging

from prometheus_client import generate_latest
from prometheus_client.core import CollectorRegistry

from nrpe2nodexp import NagiosConfig
from nrpe2nodexp import NagiosCollector
from nrpe2nodexp import ECSFormatter


class NagiosConfigTest(unittest.TestCase):
    def setUp(self):
        self._script_directory = pathlib.Path(tempfile.mkdtemp())

    def tearDown(self):
        shutil.rmtree(self._script_directory.as_posix())

    def test_get_command_ok(self):
        with open(self._script_directory / "check_get_command.cfg", "w") as f:
            f.write("command[check_get_command]=echo get_command")

        nagiosconfig = NagiosConfig(self._script_directory, "check_get_command")
        assert nagiosconfig.get_command() == "echo get_command"

    def test_get_command_unable_to_parse_command(self):
        with open(self._script_directory / "check_get_command.cfg", "w") as f:
            f.write("command[check_bad_command]=echo get_command")

        nagiosconfig = NagiosConfig(self._script_directory, "check_get_command")
        assert nagiosconfig.get_command() == ""


class NagiosCollectorTest(unittest.TestCase):
    def setUp(self):
        self._script_directory = pathlib.Path(tempfile.mkdtemp())
        self._cache_directory = pathlib.Path(tempfile.mkdtemp())
        self._alert_rule_hash = "unittest"

    def tearDown(self):
        shutil.rmtree(self._script_directory.as_posix())
        shutil.rmtree(self._cache_directory.as_posix())

    def test_collect_unable_to_parse_command(self):
        expected_output = """# HELP nagios_nrpe_check_config_error True if errors occurred during check initialization.
# TYPE nagios_nrpe_check_config_error gauge
nagios_nrpe_check_config_error{alert_rule_hash="unittest",check_name="check_get_command"} 1.0
"""  # noqa E501

        self._check_command = "check_get_command"
        with open(self._script_directory / "check_get_command.cfg", "w") as f:
            f.write("command[check_bad_command]=echo get_command")

        nagiosconfig = NagiosConfig(self._script_directory, f"{self._check_command}")
        nagioscollector = NagiosCollector(
            self._cache_directory,
            self._check_command,
            nagiosconfig.get_executor(),
            self._alert_rule_hash,
            False,
            False,
            10,
        )

        registry = CollectorRegistry()
        registry.register(nagioscollector)
        output = (generate_latest(registry)).decode("utf-8")

        assert expected_output == output

    def test_collect_timeout(self):
        expected_output = """# HELP nagios_nrpe_check_result Result of Nagios-style check script execution
# TYPE nagios_nrpe_check_result gauge
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_timeout",severity="info",status="OK"} 0.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_timeout",severity="warning",status="WARNING"} 0.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_timeout",severity="critical",status="CRITICAL"} 0.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_timeout",severity="info",status="UNKNOWN"} 1.0
# HELP nagios_nrpe_check_config_error True if errors occurred during check initialization.
# TYPE nagios_nrpe_check_config_error gauge
nagios_nrpe_check_config_error{alert_rule_hash="unittest",check_name="check_timeout"} 0.0
"""  # noqa E501

        self._check_command = "check_timeout"
        with open(self._script_directory / "check_timeout.cfg", "w") as f:
            f.write(f"command[{self._check_command}]=sleep 10")

        nagiosconfig = NagiosConfig(self._script_directory, f"{self._check_command}")
        nagioscollector = NagiosCollector(
            self._cache_directory,
            self._check_command,
            nagiosconfig.get_executor(),
            self._alert_rule_hash,
            False,
            False,
            1,
        )

        registry = CollectorRegistry()
        registry.register(nagioscollector)
        output = (generate_latest(registry)).decode("utf-8")

        assert expected_output == output

    def test_collect_ok_w_perfdata(self):
        expected_output = """# HELP nagios_nrpe_check_result Result of Nagios-style check script execution
# TYPE nagios_nrpe_check_result gauge
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="info",status="OK"} 1.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="warning",status="WARNING"} 0.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="critical",status="CRITICAL"} 0.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="info",status="UNKNOWN"} 0.0
# HELP nagios_nrpe_check_perfdata PerfData generated by Nagios-style check script execution
# TYPE nagios_nrpe_check_perfdata gauge
nagios_nrpe_check_perfdata{alert_rule_hash="unittest",check_name="check_dummy",crit="5",entity="a",max="10",min="0",unit="d",warn="0"} 6.0
# HELP nagios_nrpe_check_config_error True if errors occurred during check initialization.
# TYPE nagios_nrpe_check_config_error gauge
nagios_nrpe_check_config_error{alert_rule_hash="unittest",check_name="check_dummy"} 0.0
"""  # noqa E501

        self._check_command = "check_dummy"
        with open(self._script_directory / "check_dummy.cfg", "w") as f:
            f.write(f"command[{self._check_command}]=echo 'OK dummy | a=6d;0;5;0;10'")

        nagiosconfig = NagiosConfig(self._script_directory, f"{self._check_command}")
        nagioscollector = NagiosCollector(
            self._cache_directory,
            self._check_command,
            nagiosconfig.get_executor(),
            self._alert_rule_hash,
            True,
            False,
            10,
        )

        registry = CollectorRegistry()
        registry.register(nagioscollector)
        output = (generate_latest(registry)).decode("utf-8")

        assert expected_output == output

    def test_collect_page_wo_perfdata(self):
        expected_output = """# HELP nagios_nrpe_check_result Result of Nagios-style check script execution
# TYPE nagios_nrpe_check_result gauge
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="info",status="OK"} 0.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="warning",status="WARNING"} 0.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="page",status="CRITICAL"} 1.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="info",status="UNKNOWN"} 0.0
# HELP nagios_nrpe_check_config_error True if errors occurred during check initialization.
# TYPE nagios_nrpe_check_config_error gauge
nagios_nrpe_check_config_error{alert_rule_hash="unittest",check_name="check_dummy"} 0.0
"""  # noqa E501

        self._check_command = "check_dummy"
        with open(self._script_directory / "check_dummy.cfg", "w") as f:
            f.write(
                f'command[{self._check_command}]=/bin/bash -c "echo CRITICAL; exit 2"'
            )

        nagiosconfig = NagiosConfig(self._script_directory, f"{self._check_command}")
        nagioscollector = NagiosCollector(
            self._cache_directory,
            self._check_command,
            nagiosconfig.get_executor(),
            self._alert_rule_hash,
            False,
            True,
            10,
        )

        registry = CollectorRegistry()
        registry.register(nagioscollector)
        output = (generate_latest(registry)).decode("utf-8")

        assert expected_output == output

    def test_collect_critical_wo_perfdata(self):
        expected_output = """# HELP nagios_nrpe_check_result Result of Nagios-style check script execution
# TYPE nagios_nrpe_check_result gauge
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="info",status="OK"} 0.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="warning",status="WARNING"} 0.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="critical",status="CRITICAL"} 1.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="info",status="UNKNOWN"} 0.0
# HELP nagios_nrpe_check_config_error True if errors occurred during check initialization.
# TYPE nagios_nrpe_check_config_error gauge
nagios_nrpe_check_config_error{alert_rule_hash="unittest",check_name="check_dummy"} 0.0
"""  # noqa E501

        self._check_command = "check_dummy"
        with open(self._script_directory / "check_dummy.cfg", "w") as f:
            f.write(
                f'command[{self._check_command}]=/bin/bash -c "echo CRITICAL; exit 2"'
            )

        nagiosconfig = NagiosConfig(self._script_directory, f"{self._check_command}")
        nagioscollector = NagiosCollector(
            self._cache_directory,
            self._check_command,
            nagiosconfig.get_executor(),
            self._alert_rule_hash,
            False,
            False,
            10,
        )

        registry = CollectorRegistry()
        registry.register(nagioscollector)
        output = (generate_latest(registry)).decode("utf-8")

        assert expected_output == output


class ECSFormatterTest(unittest.TestCase):
    def setUp(self):
        self._cache_directory = pathlib.Path(tempfile.mkdtemp())
        self._check_name = "check_dummy"
        self._ecsf = ECSFormatter(self._cache_directory, self._check_name)

    def tearDown(self):
        shutil.rmtree(self._cache_directory.as_posix())

    def test_format_ok(self):
        record = logging.makeLogRecord(
            {
                "levelname": "INFO",
                "msg": "OK Dummy message",
                "executable": "executable",
                "timestamp": "1970-01-01T00:00:00.000000+00:00",
                "returncode": 0,
            }
        )

        expected_output = '@cee: {"ecs.version": "1.7.0", "log.level": "INFO", "message": "OK Dummy message", "event.category": "process", "event.kind": "state", "event.outcome": "success", "event.type": "change", "event.module": "check_dummy", "process.executable": "executable", "process.exit_code": 0, "timestamp": "1970-01-01T00:00:00.000000+00:00"}'  # noqa E501
        assert expected_output == self._ecsf.format(record)

    def test_format_warn(self):
        record = logging.makeLogRecord(
            {
                "levelname": "INFO",
                "msg": "WARNING Dummy message",
                "executable": "executable",
                "timestamp": "1970-01-01T00:00:00.000000+00:00",
                "returncode": 1,
            }
        )

        expected_output = '@cee: {"ecs.version": "1.7.0", "log.level": "INFO", "message": "WARNING Dummy message", "event.category": "process", "event.kind": "alert", "event.outcome": "failure", "event.type": "change", "event.module": "check_dummy", "process.executable": "executable", "process.exit_code": 1, "timestamp": "1970-01-01T00:00:00.000000+00:00"}'  # noqa E501
        assert expected_output == self._ecsf.format(record)

    def test_format_crit(self):
        record = logging.makeLogRecord(
            {
                "levelname": "INFO",
                "msg": "CRITICAL Dummy message",
                "executable": "executable",
                "timestamp": "1970-01-01T00:00:00.000000+00:00",
                "returncode": 2,
            }
        )

        expected_output = '@cee: {"ecs.version": "1.7.0", "log.level": "INFO", "message": "CRITICAL Dummy message", "event.category": "process", "event.kind": "alert", "event.outcome": "failure", "event.type": "change", "event.module": "check_dummy", "process.executable": "executable", "process.exit_code": 2, "timestamp": "1970-01-01T00:00:00.000000+00:00"}'  # noqa E501
        assert expected_output == self._ecsf.format(record)

    def test_format_unknown(self):
        record = logging.makeLogRecord(
            {
                "levelname": "INFO",
                "msg": "UNKNOWN Dummy message",
                "executable": "executable",
                "timestamp": "1970-01-01T00:00:00.000000+00:00",
                "returncode": 3,
            }
        )

        expected_output = '@cee: {"ecs.version": "1.7.0", "log.level": "INFO", "message": "UNKNOWN Dummy message", "event.category": "process", "event.kind": "event", "event.outcome": "unknown", "event.type": "change", "event.module": "check_dummy", "process.executable": "executable", "process.exit_code": 3, "timestamp": "1970-01-01T00:00:00.000000+00:00"}'  # noqa E501
        assert expected_output == self._ecsf.format(record)

    def test_format_change_alert(self):
        current_status = """# HELP nagios_nrpe_check_result Result of Nagios-style check script execution
# TYPE nagios_nrpe_check_result gauge
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="info",status="OK"} 1.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="warning",status="WARNING"} 0.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="critical",status="CRITICAL"} 0.0
nagios_nrpe_check_result{alert_rule_hash="unittest",check_name="check_dummy",severity="info",status="UNKNOWN"} 0.0
# HELP nagios_nrpe_check_perfdata PerfData generated by Nagios-style check script execution
# TYPE nagios_nrpe_check_perfdata gauge
nagios_nrpe_check_perfdata{alert_rule_hash="unittest",check_name="check_dummy",crit="5",entity="a",max="10",min="0",unit="d",warn="0"} 6.0
# HELP nagios_nrpe_check_config_error True if errors occurred during check initialization.
# TYPE nagios_nrpe_check_config_error gauge
nagios_nrpe_check_config_error{alert_rule_hash="unittest",check_name="check_dummy"} 0.0
"""  # noqa E501

        with open(self._cache_directory / "check_dummy.prom", "w") as f:
            f.write(current_status)

        record = logging.makeLogRecord(
            {
                "levelname": "INFO",
                "msg": "UNKNOWN Dummy message",
                "executable": "executable",
                "timestamp": "1970-01-01T00:00:00.000000+00:00",
                "returncode": 1,
            }
        )

        expected_output = '@cee: {"ecs.version": "1.7.0", "log.level": "INFO", "message": "UNKNOWN Dummy message", "event.category": "process", "event.kind": "alert", "event.outcome": "failure", "event.type": "change", "event.module": "check_dummy", "process.executable": "executable", "process.exit_code": 1, "timestamp": "1970-01-01T00:00:00.000000+00:00"}'  # noqa E501

        assert expected_output == self._ecsf.format(record)
