#!/bin/bash
# statsitectl -- Manage statsite jobs
# Usage: statsitectl {status|check|start|stop|restart}
#
command=$1
shift
case "$command" in
    status)
        status=0
        for config in /etc/statsite/*.ini; do
          instance="$(basename $config .ini)"
          status statsite/instance NAME="$instance" || status=$?
        done
        exit $status
        ;;
    check)
        $0 status >/dev/null 2>&1 || {
            echo "CRITICAL: Not all configured statsite instances are running."
            exit 2
        }
        echo "OK: All defined statsite jobs are runnning."
        exit 0
        ;;
    start)
        /sbin/initctl emit statsite.start
        ;;
    stop)
        /sbin/initctl emit statsite.stop
        ;;
    restart)
        /sbin/initctl emit statsite.stop
        /sbin/initctl emit statsite.start
        ;;
    *)
        echo >&2 "Usage: ${0##*/} {status|check|start|stop|restart}"
        ;;
esac
