# SPDX-License-Identifier: Apache-2.0
# OpenSearch Security Plugin Configuration
#
# This is the main OpenSearch Security configuration file where authentication (authc)
# and authorization (authz) are defined.
#
# You need to configure at least one authentication domain in the authc of this file.
# An authentication domain is responsible for extracting the user credentials from
# the request and for validating them against an authentication backend like Active Directory for example.
#
# If more than one authentication domain is configured, the first one which succeeds wins.
# If all authentication domains fail, then the request is unauthenticated.
# In this case, an exception is thrown and/or the HTTP status is set to 401.
#
# After authentication authorization (authz) will be applied. There can be zero or more authorizers which collect
# the roles from a given backend for the authenticated user.
#
# Both authc and auth can be enabled/disabled separately for REST and TRANSPORT layer. Default is true for both.
#        http_enabled: true
#        transport_enabled: true
#
# For HTTP it is possible to allow anonymous authentication. If that is the case, then the HTTP authenticators try to
# find user credentials in the HTTP request. If credentials are found, then the user gets regularly authenticated.
# If none can be found, the user will be authenticated as an "anonymous" user. This user has always the username "anonymous"
# and one role named "anonymous_backendrole".
# If you enable anonymous authentication, all HTTP authenticators will not challenge.
#
# Note: If you define more than one HTTP authenticator, make sure to put non-challenging authenticators like
# "proxy" or "clientcert" first, and the challenging one last.
# Because it's not possible to challenge a client with two different authentication methods (e.g.,
# Kerberos and Basic), only one can have the challenge flag set to true. You can cope with this situation
# by using pre-authentication, i.e., sending an HTTP Basic authentication header in the request.
#
# The default value of the challenge flag is true.
---
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    kibana:
      multitenancy_enabled: false
      private_tenant_enabled: false
      default_tenant: "global tenant"
      server_username: opensearch_dashboards
      index: '.kibana'
    do_not_fail_on_forbidden: true
    http:
      # See also: https://docs.opensearch.org/latest/security/access-control/anonymous-authentication/
      anonymous_auth_enabled: false
      # Used to configure proxy-based authentication.
      # See also Proxy-based authentication. https://docs.opensearch.org/latest/security/authentication-backends/proxy/
      xff:
        enabled: true
        internalProxies: '.*'  # TODO: this allows all proxies - change this to IP address of localhost before prod
        remoteIpHeader: 'X-Forwarded-For'
    # AUTHentiCation
    authc:
      proxy_auth_domain:
        description: "Accept apache2 authentication"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: "X-Remote-User"
            roles_header: "X-Remote-User-Roles"
        authentication_backend:
          type: noop
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
    # AUTHoriZation
    authz: {}
