profile::etcd::replication::origin:
  cluster_name: codfw.wmnet
  path: /
  servers:
    - conf2004.codfw.wmnet
    - conf2005.codfw.wmnet
    - conf2006.codfw.wmnet
  # spicerack's python-etcd locks are not meaningful to replicate.
  ignore_keys_regex: "/spicerack/locks/etcd(/.*)?"
profile::etcd::replication::destination_path: /
# For nodes with active replication, see hieradata/hosts/conf*.yaml
profile::etcd::replication::active: false
profile::etcd::replication::src_port: 4001
profile::etcd::tlsproxy::read_only: false

# T428495: Explicitly enable the v2 API.
profile::etcd::v3::enable_v2: true

# T428495: Explicitly set cluster_bootstrap to false.
profile::etcd::v3::cluster_bootstrap: false

