# SPDX-License-Identifier: Apache-2.0

# Don't pollute edge caches with docker images.
# Note an approach for CC: max-age=60 or 600 would gives us a small amount
# of caching and protects us in big stormy scenarios. However we have CI
# requiring really small reaction times for now, so avoid all caching.
# Bug: T211719
add_header 'Cache-Control' 'no-cache,must-revalidate' always;
# Re-add Vary header as add_header directives are inherited from the
# previous configuration level if and only if there are no add_header
# directives defined on the current level.
# http://nginx.org/en/docs/http/ngx_http_headers_module.html
add_header 'Vary' 'Accept' always;