require 'rake'
require 'fileutils'

require 'rspec/core/rake_task'

modulename = File.basename(File.expand_path(File.dirname(__FILE__)))


symlinks = {
             'spec/checker/checker.py' => '../../files/checker.py'
           }


task :setup do
  # TODO: create a virtualenv to run this all
  symlinks.each do |x|
    FileUtils.ln_s(x[1], x[0]) if !File.exist?(x[0])
  end
end

task :teardown do
  symlinks.each { |x| FileUtils.rm(x[0], :force => true) }
end

RSpec::Core::RakeTask.new(:realspec) do |t|
  t.fail_on_error = false
  t.pattern = 'spec/*/*_spec.rb'
end

task :test_checker  do
  puts "Testing the python service checker"
  sh "nosetests spec/checker/"
end

task :spec_standalone => [ :setup, :test_checker, :realspec, :teardown]

task :default => :spec_standalone do
end
